/**
 * remotion/PostcardFront4x6.tsx
 *
 * Wave 36 — branded 4×6 postcard FRONT for Lob fulfillment.
 *
 * Spec:
 *   Trim size:       4" × 6"          = 1200 × 1800 px @ 300 DPI
 *   Bleed:           0.125" each side
 *   Bleed canvas:    4.25" × 6.25"    = 1275 × 1875 px @ 300 DPI  ← what we render
 *   Safe zone:       0.1875" inset from trim
 *
 * Lob expects PNG/JPG/PDF at the bleed canvas. We render PNG via
 * @remotion/renderer's renderStill() and upload to Supabase Blob; the
 * public URL is passed to Lob's postcards.create({ front: <url> }).
 *
 * The composition is durationInFrames=1 (pure still — no animation;
 * Remotion needs an anchor frame).
 *
 * Branding sourced through lib/branding/resolve-brokerage-brand.ts so
 * primary/accent colors, logo, license line, and Fair Housing
 * disclosure all flow from one resolver. Compositions never read DB
 * directly — props are passed at renderStill() time.
 *
 * Copy sourced through lib/direct-mail/draft-copy.ts which gates the
 * AI output through evaluateOutbound BEFORE it reaches this prop.
 */
import React from "react"
import { AbsoluteFill, Img } from "remotion"
import { SafeImg } from "./components/SafeImg"

export interface PostcardFront4x6Props {
  headline: string
  body:     string
  cta:      string
  /** QR PNG data URL (data:image/png;base64,...) generated by qrcode
   *  package at render-endpoint time so the file is fully self-
   *  contained and Lob doesn't have to wait for a separate asset. */
  qrCodeDataUrl: string | null
  brand: {
    primaryColor:     string
    accentColor:      string
    logoUrl:          string | null
    brokerageName:    string
    websiteWordmark:  string | null
    phone:            string | null
    licenseLine:      string | null
    shortDisclosure:  string
  }
}

// Layout constants in pixels (300 DPI).
const SAFE_INSET = 56  // ~0.1875" + a hair for safety

export const PostcardFront4x6: React.FC<PostcardFront4x6Props> = ({
  headline, body, cta, qrCodeDataUrl, brand,
}) => {
  return (
    <AbsoluteFill style={{
      backgroundColor: brand.primaryColor,
      fontFamily: "system-ui, -apple-system, 'Segoe UI', sans-serif",
      color: "#fff",
    }}>
      {/* Accent ribbon along top edge — visual brand anchor */}
      <div style={{
        position: "absolute", top: 0, left: 0, right: 0,
        height: 84, backgroundColor: brand.accentColor,
      }} />

      {/* Logo block — top left of safe zone */}
      <div style={{
        position: "absolute", top: SAFE_INSET + 32, left: SAFE_INSET,
        display: "flex", alignItems: "center", gap: 20,
      }}>
        {brand.logoUrl ? (
          <SafeImg src={brand.logoUrl} style={{ height: 80, width: "auto", objectFit: "contain" }} />
        ) : (
          <div style={{
            width: 80, height: 80, borderRadius: 12,
            backgroundColor: brand.accentColor,
            color: brand.primaryColor,
            display: "flex", alignItems: "center", justifyContent: "center",
            fontSize: 48, fontWeight: 800,
          }}>{brand.brokerageName[0]?.toUpperCase() ?? "B"}</div>
        )}
        <div style={{ fontSize: 28, fontWeight: 700, lineHeight: 1.1 }}>
          {brand.brokerageName}
        </div>
      </div>

      {/* Headline — dominant left column */}
      <div style={{
        position: "absolute",
        top: 240, left: SAFE_INSET, right: SAFE_INSET + 380,
      }}>
        <div style={{
          fontSize: 88, fontWeight: 800, lineHeight: 1.05,
          letterSpacing: -1.5,
        }}>
          {headline}
        </div>
      </div>

      {/* Body — under the headline */}
      <div style={{
        position: "absolute",
        top: 620, left: SAFE_INSET, right: SAFE_INSET + 380,
        fontSize: 32, lineHeight: 1.45, color: "rgba(255,255,255,0.92)",
      }}>
        {body}
      </div>

      {/* CTA pill — accent-colored, bottom left */}
      <div style={{
        position: "absolute",
        bottom: SAFE_INSET + 140, left: SAFE_INSET,
        display: "inline-flex", alignItems: "center", gap: 14,
        padding: "20px 36px",
        backgroundColor: brand.accentColor,
        color: brand.primaryColor,
        fontSize: 32, fontWeight: 700,
        borderRadius: 999,
      }}>
        {cta}
        <span style={{ fontSize: 28, lineHeight: 1 }}>→</span>
      </div>

      {/* QR code panel — right column, square */}
      <div style={{
        position: "absolute",
        right: SAFE_INSET, top: 240,
        width: 340, height: 340,
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 18,
        display: "flex", alignItems: "center", justifyContent: "center",
      }}>
        {qrCodeDataUrl ? (
          <Img src={qrCodeDataUrl} style={{ width: "100%", height: "100%", objectFit: "contain" }} />
        ) : (
          <div style={{ color: brand.primaryColor, fontSize: 18 }}>QR</div>
        )}
      </div>

      {/* Scan-me micro-label under QR */}
      <div style={{
        position: "absolute",
        right: SAFE_INSET, top: 600,
        width: 340,
        textAlign: "center",
        fontSize: 22, fontWeight: 600,
        opacity: 0.85,
      }}>
        Scan with your camera
      </div>

      {/* Footer — license + Fair Housing + website */}
      <div style={{
        position: "absolute",
        bottom: SAFE_INSET, left: SAFE_INSET, right: SAFE_INSET,
        borderTop: `2px solid ${brand.accentColor}`,
        paddingTop: 16,
        display: "flex", justifyContent: "space-between", alignItems: "flex-end",
        fontSize: 18, lineHeight: 1.35, color: "rgba(255,255,255,0.78)",
      }}>
        <div style={{ flex: 1, paddingRight: 20 }}>
          {brand.licenseLine && <div>{brand.licenseLine}</div>}
          <div style={{ marginTop: 6 }}>{brand.shortDisclosure}</div>
        </div>
        <div style={{ textAlign: "right", flexShrink: 0 }}>
          {brand.websiteWordmark && <div style={{ fontSize: 22, fontWeight: 600 }}>{brand.websiteWordmark}</div>}
          {brand.phone && <div style={{ marginTop: 4 }}>{brand.phone}</div>}
        </div>
      </div>
    </AbsoluteFill>
  )
}
