// Route mapping for sidebar navigation
export const ROUTE_MAP: Record<string, string> = {
  "broker-dashboard": "/dashboard",
  "agent-dashboard": "/dashboard",
  crm: "/crm",
  "lead-intelligence": "/leads",
  "lead-insights": "/leads",
  "lead-scraping-config": "/settings",
  "agent-roster": "/contacts",
  "recruiting-hub": "/dashboard/agent/referrals",
  financials: "/analytics",
  "risk-management": "/compliance",
  "listing-approvals": "/approvals",
  "ai-audit": "/analytics",
  "conversation-analytics": "/analytics",
  "vendor-compliance": "/compliance",
  "system-health": "/analytics",
  "lead-distribution": "/leads",
  segmentation: "/analytics",
  "data-health": "/analytics",
  settings: "/settings",
  transactions: "/seed",
  "map-intelligence": "/analytics",
  "knowledge-base": "/academy",
  events: "/seed",
  "listing-intake": "/seed",
  "offer-lab": "/seed",
  calendar: "/seed",
  showings: "/seed",
  "buyer-tours": "/seed",
  "feedback-log": "/seed",
  playbook: "/seed",
  "agent-onboarding": "/academy",
  "voice-call-bridge": "/seed",
  "dashboard-voice": "/dashboard/voice",
  "ai-isa": "/seed",
  "content-studio": "/content-studio",
  "social-planner": "/social-planner",
  sphere: "/referrals",
  documents: "/seed",
  marketplace: "/seed",
  inbox: "/seed",
  approvals: "/approvals",
  "oh-manager": "/seed",
  "closing-dashboard": "/seed",
  cma: "/seed",
  partners: "/seed",
  compliance: "/compliance",
  notifications: "/seed",
  "shareable-assets": "/seed",
  "user-management": "/seed",
  "tc-dashboard": "/seed",
  "listing-distribution": "/seed",
  "buyer-dashboard": "/seed",
  matches: "/seed",
  "home-value": "/seed",
  "seller-dashboard": "/seed",
  "listing-journey": "/seed",
  "ai-chat": "/seed",
  referrals: "/referrals",
  "referral-partners": "/dashboard/agent/referrals",
  "past-clients": "/past-clients",
  academy: "/academy",
  leads: "/leads",
  contacts: "/contacts",
  workflows: "/workflows",
  "video-assistant": "/video-assistant",
}

export function getNavItemUrl(navId: string): string {
  return ROUTE_MAP[navId] || `/${navId}`
}
