/**
 * lib/recruiting/recruiting-pitch-kit.ts
 *
 * THE RECRUITING PITCH KIT — the final gap in the asset audit, and the one
 * NO competitor even attempts: Rave/Lofty/RealScout market listings to
 * consumers; nobody produces the brokerage's OWN growth marketing. This OS
 * recruits agents as a first-class business process (switch propensity,
 * retention radar, ROI ledger, weekly outreach) but produced zero
 * recruit-facing assets — the brokerages table has carried
 * recruiting_pitch / recruiting_value_props / recruiting_split_to_agent /
 * recruiting_monthly_fee since setup with nothing consuming them.
 *
 * The kit: a brand-true, print-ready PITCH ONE-PAGER (client-pdf engine)
 * built ONLY from real data —
 *   · the brokerage's own pitch + value props (settings, AI-polished
 *     through the gated copy rail, deterministic facts fallback)
 *   · THE AI TEAM the recruit actually gets — enumerated from the live
 *     MANAGERS registry, never a marketing list that can drift from the
 *     product
 *   · the deal terms (split %, monthly fee — omitted when unset, never
 *     invented)
 *   · measured recruiting ROI when the ledger has it (recruited-agent
 *     production from recruiting_analytics), omitted when it doesn't
 *
 * Autonomous: produced per brokerage on the weekly recruit-outreach cron,
 * refreshed ONLY when the settings actually change (settings-hash
 * idempotency), recorded in generated_documents, broker notified with the
 * print-ready link. recruiting_manager owns the talent pipeline.
 */
import { createHash } from "crypto"
import { MANAGERS } from "@/lib/kernel/manager-registry"
import type { ClientPdfSection, ClientPdfSpec, ClientPdfBrand } from "@/lib/documents/client-pdf"

export interface RecruitingPitchFacts {
  brokerageName: string
  pitch: string | null
  valueProps: string[]
  splitToAgent: number | null
  monthlyFee: number | null
  /** Measured: gross commission generated by recruited agents (dollars), when the ledger has it. */
  recruitedGciDollars: number | null
  recruitedAgentCount: number | null
  contactLine: string | null
}

/** PURE: stable hash of everything that shapes the kit — the refresh key. */
export function pitchSettingsHash(f: RecruitingPitchFacts): string {
  return createHash("sha256").update(JSON.stringify({
    n: f.brokerageName, p: f.pitch, v: f.valueProps, s: f.splitToAgent, m: f.monthlyFee,
  })).digest("hex").slice(0, 16)
}

/** PURE: the AI-team section — from the LIVE registry, so the pitch can
 *  never advertise a manager the product doesn't ship. Front-office
 *  (lead-working) managers lead; oversight managers close the list. */
export function aiTeamBullets(): string[] {
  return Object.values(MANAGERS).map((m) => `${m.label} — ${m.domain}`)
}

/** PURE: assemble the pitch spec from facts + polished copy. */
export function recruitingPitchSpec(
  f: RecruitingPitchFacts,
  polishedPitch: string,
  brand: ClientPdfBrand,
  dateLabel: string,
): ClientPdfSpec {
  const sections: ClientPdfSection[] = [
    { paragraphs: polishedPitch.split(/\n{2,}/).map((p) => p.trim()).filter(Boolean).slice(0, 3) },
  ]
  if (f.valueProps.length) {
    sections.push({ heading: "Why agents join", bullets: f.valueProps.slice(0, 6) })
  }
  sections.push({
    heading: "The AI team behind every agent",
    paragraphs: [
      "Every agent here works with a full AI operations team — the same staff a mega-team hires, built into the brokerage:",
    ],
    bullets: aiTeamBullets(),
  })
  // THE TRUST STORY — the differentiator no portal CRM can say: autonomy is
  // EARNED from the broker's own approvals, visible, revocable, ledger-backed.
  sections.push({
    heading: "An AI team that earns your trust",
    paragraphs: [
      "Nothing publishes or spends without a human until the team has earned it: every proposal you approve or decline is recorded, and only a spotless approval record lets the broker grant a standing move — visible on one governance panel, revocable in one click, with every autonomous act written to a policy ledger you can audit. Fair Housing and consent gates run on every send regardless.",
    ],
  })
  const terms: string[][] = []
  if (f.splitToAgent != null) terms.push(["Commission split to agent", `${f.splitToAgent}%`])
  if (f.monthlyFee != null) terms.push(["Monthly fee", `$${Number(f.monthlyFee).toLocaleString("en-US")}`])
  if (terms.length) sections.push({ heading: "The terms", table: { rows: terms } })
  if (f.recruitedGciDollars != null && f.recruitedAgentCount != null && f.recruitedAgentCount > 0) {
    sections.push({
      heading: "Measured, not claimed",
      paragraphs: [
        `Agents who joined through this pipeline have generated $${Math.round(f.recruitedGciDollars).toLocaleString("en-US")} in gross commission across ${f.recruitedAgentCount} recruited agent${f.recruitedAgentCount === 1 ? "" : "s"} — measured by the operating ledger, not estimated.`,
      ],
    })
  }
  sections.push({
    heading: "The next step",
    paragraphs: [f.contactLine ?? `A confidential conversation costs nothing. Reach out to ${f.brokerageName} and see the platform live.`],
  })
  return {
    title: `Join ${f.brokerageName}`,
    subtitle: "What your business looks like with an AI team behind it",
    preparedLine: dateLabel,
    brand,
    sections,
    disclaimer:
      "Commission structures and fees are subject to the brokerage's independent-contractor agreement. " +
      "This document is informational and not an offer of employment or engagement.",
  }
}

/** PURE: team rows carry their own real recruiting facts — bio/tagline are
 *  the pitch, split fields are the terms. No new columns invented. */
export function teamPitchFacts(t: {
  name: string | null
  tagline: string | null
  bio_text: string | null
  team_split_percent: number | null
  team_split_value: number | null
  team_split_type: string | null
  team_fees_json: unknown
  phone: string | null
}): RecruitingPitchFacts {
  const fees = t.team_fees_json && typeof t.team_fees_json === "object" ? t.team_fees_json as Record<string, unknown> : null
  const monthly = fees && Number.isFinite(Number(fees.monthly_fee)) ? Number(fees.monthly_fee) : null
  const split = t.team_split_percent != null ? Number(t.team_split_percent)
    : t.team_split_type === "percent" && t.team_split_value != null ? Number(t.team_split_value) : null
  return {
    brokerageName: t.name ?? "This team",
    pitch: [t.tagline, t.bio_text].filter(Boolean).join("\n\n") || null,
    valueProps: [],
    splitToAgent: split,
    monthlyFee: monthly,
    recruitedGciDollars: null,
    recruitedAgentCount: null,
    contactLine: t.phone ? `Reach the team lead directly: ${t.phone}` : null,
  }
}

/**
 * Produce/refresh the kit for every recruiting-configured brokerage AND
 * every team with a real pitch (owner rule: teams recruit too — the team
 * lead gets their own recruit-facing one-pager from the team's own
 * bio/tagline/split, on the brokerage's brand).
 * Settings-hash idempotent: unchanged settings → no new document.
 */
export async function runRecruitingPitchKits(svc: any): Promise<{ pitchKits: number; pitchSkipped: number; pitchErrors: number }> {
  const out = { pitchKits: 0, pitchSkipped: 0, pitchErrors: 0 }
  const { data: brokerages } = await svc.from("brokerages")
    .select("id, name, recruiting_pitch, recruiting_value_props, recruiting_split_to_agent, recruiting_monthly_fee, phone, email")
    .or("recruiting_pitch.not.is.null,recruiting_value_props.not.is.null")
    .is("deleted_at", null)
    .limit(500)

  for (const b of ((brokerages ?? []) as any[])) {
    try {
      const facts: RecruitingPitchFacts = {
        brokerageName: b.name ?? "This brokerage",
        pitch: b.recruiting_pitch ?? null,
        valueProps: Array.isArray(b.recruiting_value_props) ? b.recruiting_value_props.map((v: unknown) => String(v)).filter(Boolean) : [],
        splitToAgent: b.recruiting_split_to_agent != null ? Number(b.recruiting_split_to_agent) : null,
        monthlyFee: b.recruiting_monthly_fee != null ? Number(b.recruiting_monthly_fee) : null,
        recruitedGciDollars: null,
        recruitedAgentCount: null,
        contactLine: [b.phone, b.email].filter(Boolean).length
          ? `Reach us directly: ${[b.phone, b.email].filter(Boolean).join(" · ")}`
          : null,
      }

      // Measured ROI from the ledger — only when it actually exists.
      try {
        const { data: roi } = await svc.from("recruiting_analytics")
          .select("recruited_agent_id, gross_commission_generated")
          .eq("brokerage_id", b.id).not("recruited_agent_id", "is", null).limit(1000)
        const rows = (roi ?? []) as Array<{ recruited_agent_id: string; gross_commission_generated: number | null }>
        if (rows.length > 0) {
          const gci = rows.reduce((s, r) => s + (Number(r.gross_commission_generated) || 0), 0)
          if (gci > 0) {
            facts.recruitedGciDollars = gci
            facts.recruitedAgentCount = new Set(rows.map((r) => r.recruited_agent_id)).size
          }
        }
      } catch { /* ROI section simply omitted */ }

      const hash = pitchSettingsHash(facts)
      const { data: existing } = await svc.from("generated_documents")
        .select("id, metadata").eq("brokerage_id", b.id)
        .eq("document_type", "recruiting_pitch")
        .order("created_at", { ascending: false }).limit(1).maybeSingle()
      if ((existing?.metadata as any)?.settings_hash === hash) { out.pitchSkipped++; continue }

      // AI-polish the pitch through the gated copy rail; the raw settings
      // text (already broker-authored) is the deterministic fallback.
      let polished = facts.pitch ?? `${facts.brokerageName} pairs every agent with a built-in AI operations team so production time goes to clients, not admin.`
      try {
        const { generatePersonaCopy, realCopyGenerator } = await import("@/lib/kernel/ai-copy")
        const draft = await generatePersonaCopy(
          {
            goal: "a two-paragraph recruiting pitch inviting a licensed agent to a confidential conversation",
            facts: [facts.brokerageName, facts.pitch ?? "", ...facts.valueProps],
            channel: "landing_page", persona: { audience: "licensed real-estate agents" }, words: 110,
          },
          { body: polished }, { generator: realCopyGenerator },
        )
        polished = draft.body || polished
      } catch { /* broker-authored text stands */ }

      const { resolvePdfBrand, produceClientDocument } = await import("@/lib/documents/client-document-producer")
      const brand = await resolvePdfBrand(svc, { brokerageId: b.id })
      const dateLabel = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" })
      const spec = recruitingPitchSpec(facts, polished, brand, dateLabel)
      const produced = await produceClientDocument(svc, {
        brokerageId: b.id,
        documentType: "recruiting_pitch",
        spec,
        metadata: { settings_hash: hash, source: "auto_recruiting_pitch" },
      })
      if (!produced.ok || !produced.pdfUrl) { out.pitchErrors++; continue }

      // Notify the broker (oldest admin-ish user — the blog-cadence pattern).
      const { data: broker } = await svc.from("users").select("id")
        .eq("brokerage_id", b.id).order("created_at", { ascending: true }).limit(1).maybeSingle()
      if (broker?.id) {
        await svc.from("notifications").insert({
          user_id: broker.id, brokerage_id: b.id, type: "recruiting_pitch_ready",
          title: "Your recruiting pitch kit is ready",
          body: `The recruit-facing one-pager (your pitch, the AI team, your terms${facts.recruitedGciDollars ? ", measured recruited-agent production" : ""}) is print-ready: ${produced.pdfUrl} [recruit-pitch:${hash}]`,
          priority: "medium", channel: "in_app", is_read: false,
        }).then(undefined, () => {})
      }
      out.pitchKits++
    } catch { out.pitchErrors++ }
  }

  // ── TEAM PASS — teams recruit too. A team qualifies when it has a real
  // pitch of its own (bio or tagline); the kit renders on the brokerage's
  // brand with the team's own terms, and the TEAM LEAD gets the link.
  const { data: teams } = await svc.from("teams")
    .select("id, brokerage_id, name, tagline, bio_text, team_split_percent, team_split_value, team_split_type, team_fees_json, phone, team_lead_id")
    .or("bio_text.not.is.null,tagline.not.is.null")
    .is("deleted_at", null)
    .limit(500)
  for (const t of ((teams ?? []) as any[])) {
    try {
      const facts = teamPitchFacts(t)
      if (!facts.pitch) continue
      const hash = pitchSettingsHash(facts)
      const { data: existing } = await svc.from("generated_documents")
        .select("id, metadata").eq("brokerage_id", t.brokerage_id)
        .eq("document_type", "recruiting_pitch")
        .contains("metadata", { team_id: t.id })
        .order("created_at", { ascending: false }).limit(1).maybeSingle()
      if ((existing?.metadata as any)?.settings_hash === hash) { out.pitchSkipped++; continue }

      let polished = facts.pitch
      try {
        const { generatePersonaCopy, realCopyGenerator } = await import("@/lib/kernel/ai-copy")
        const draft = await generatePersonaCopy(
          {
            goal: "a two-paragraph team recruiting pitch inviting a licensed agent to a confidential conversation",
            facts: [facts.brokerageName, facts.pitch],
            channel: "landing_page", persona: { audience: "licensed real-estate agents" }, words: 110,
          },
          { body: polished }, { generator: realCopyGenerator },
        )
        polished = draft.body || polished
      } catch { /* team-authored text stands */ }

      const { resolvePdfBrand, produceClientDocument } = await import("@/lib/documents/client-document-producer")
      const brand = await resolvePdfBrand(svc, { brokerageId: t.brokerage_id })
      const dateLabel = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long" })
      const spec = recruitingPitchSpec(facts, polished, brand, dateLabel)
      const produced = await produceClientDocument(svc, {
        brokerageId: t.brokerage_id,
        documentType: "recruiting_pitch",
        spec,
        metadata: { settings_hash: hash, team_id: t.id, source: "auto_team_recruiting_pitch" },
      })
      if (!produced.ok || !produced.pdfUrl) { out.pitchErrors++; continue }

      // Notify the TEAM LEAD (fall back to the broker pattern when unset).
      let notifyUserId: string | null = null
      if (t.team_lead_id) {
        const { data: leadAgent } = await svc.from("agents").select("user_id").eq("id", t.team_lead_id).maybeSingle()
        notifyUserId = (leadAgent as any)?.user_id ?? null
      }
      if (!notifyUserId) {
        const { data: broker } = await svc.from("users").select("id")
          .eq("brokerage_id", t.brokerage_id).order("created_at", { ascending: true }).limit(1).maybeSingle()
        notifyUserId = (broker as any)?.id ?? null
      }
      if (notifyUserId) {
        await svc.from("notifications").insert({
          user_id: notifyUserId, brokerage_id: t.brokerage_id, type: "recruiting_pitch_ready",
          title: `${facts.brokerageName} — team recruiting pitch ready`,
          body: `The recruit-facing one-pager for your team (your pitch, the AI team, your terms) is print-ready: ${produced.pdfUrl} [recruit-pitch:${hash}]`,
          priority: "medium", channel: "in_app", is_read: false,
        }).then(undefined, () => {})
      }
      out.pitchKits++
    } catch { out.pitchErrors++ }
  }
  return out
}
