"use server"

import { createClient } from "@/lib/supabase/server"
import { createServiceClient } from "@/lib/supabase/service"
import { scoreAllComps } from "@/lib/cma/ai-cma-engine"
import { generatePricePrediction } from "@/lib/pricing/predictive-pricing"
import { generateNetSheet } from "@/app/actions/cma-presentation/net-sheet-calculator"
import { resolveAgreedCommission } from "@/lib/offers/net-sheet-calc"
import { deriveNetSheetClosingCostSection } from "@/lib/offers/seller-closing-costs"
import { resolveAgentId } from "@/lib/kernel/agent-identity"

// ── Types ─────────────────────────────────────────────────────────────────────

export interface CMAPageData {
  cma: CMAReport | null
  comparables: CMAComparable[]
  compScores: Record<string, AICompScore>   // keyed by comparable_id
  riskFlags: CompRiskFlag[]
  propertyUpgrades: PropertyUpgrade[]
  agreement: ListingAgreement | null
}

export interface PricingPageData {
  latestPrediction: PricePrediction | null
  priceHistory: PricingHistoryPoint[]
  activeAlerts: PriceTrendAlert[]
}

export interface NetSheetPageData {
  latestNetSheet: NetSheetCalc | null
  agreement: ListingAgreement | null
  recommendedPrice: number | null
}

interface CMAReport {
  id: string
  brokerage_id: string | null
  listing_id: string | null
  contact_id: string
  agent_id: string
  property_address: string
  property_type: string | null
  bedrooms: number | null
  bathrooms: number | null
  square_feet: number | null
  lot_size: number | null
  year_built: number | null
  condition: string | null
  features: string[] | null
  comparable_count: number
  recommended_price: number | null
  price_range_low: number | null
  price_range_high: number | null
  market_conditions: string | null
  quality_score: number
  disclaimer_included: boolean
  status: string | null
  presented_at: string | null
  expires_at: string | null
  created_at: string | null
  updated_at: string | null
  // computed
  hasAIScores: boolean
  autoGenerated: boolean
}

interface CMAComparable {
  id: string
  cma_id: string
  address: string
  sale_price: number | null
  list_price: number | null
  price_per_sqft: number | null
  bedrooms: number | null
  bathrooms: number | null
  square_feet: number | null
  days_on_market: number | null
  sale_date: string | null
  distance_miles: number | null
  similarity_score: number | null
  adjustments: Record<string, unknown>
  adjusted_price: number | null
  ai_score: number | null
  ai_rationale: string | null
  risk_flags: string[] | null
  coaching_insight: string | null
}

interface AICompScore {
  id: string
  comparable_id: string
  score: number
  confidence_level: string | null
  score_rationale: string | null
  risk_flags: unknown
  coaching_insight: string | null
}

interface CompRiskFlag {
  id: string
  cma_id: string | null
  listing_id: string | null
  risk_type: string
  severity: string
  description: string
  recommended_action: string | null
  is_resolved: boolean
}

interface PropertyUpgrade {
  id: string
  listing_id: string | null
  upgrade_description: string
  estimated_cost: number | null
  roi_estimate: number | null
  status: string
}

interface ListingAgreement {
  id: string
  listing_commission_rate: number | null
  buyer_commission_rate: number | null
  total_commission_rate: number | null
  commission_is_flat_fee: boolean | null
  commission_flat_amount: number | null
  seller_transaction_fee: number | null
  has_commission_adjustment: boolean | null
  adjustment_type: string | null
  adjustment_value: number | null
  adjustment_notes: string | null
  esign_status: string | null
  fully_executed_at: string | null
}

interface PricePrediction {
  id: string
  predicted_price: number
  prediction_date: string
  confidence_score: number | null
  trend_direction: string | null
  trend_percentage: number | null
  market_factors: Record<string, string>
  days_to_sell_estimate: number | null
  created_at: string | null
}

interface PricingHistoryPoint {
  id: string
  price: number
  price_type: string | null
  recorded_at: string
  notes: string | null
}

interface PriceTrendAlert {
  id: string
  alert_type: string
  severity: string
  message: string
  recommended_action: string | null
  is_resolved: boolean
  created_at: string | null
}

interface NetSheetCalc {
  id: string
  sale_price: number
  listing_commission_rate: number | null
  buyer_commission_rate: number | null
  closing_costs: number | null
  mortgage_balance: number | null
  mortgage_payoff_amount: number | null
  property_taxes: number | null
  hoa_fees: number | null
  repair_credits: number | null
  seller_concessions: number | null
  /** Flat seller transaction fee used on this saved sheet (m287). */
  transaction_fee: number | null
  /** Agreed commission was a flat dollar fee, not a percentage (m289). */
  commission_is_flat_fee: boolean | null
  commission_flat_amount: number | null
  gross_proceeds: number | null
  total_costs: number | null
  net_proceeds: number | null
  scenarios: unknown[]
  expires_at: string | null
  created_at: string | null
}

// ── Data Loaders ──────────────────────────────────────────────────────────────

/**
 * Load all CMA tab data for a listing.
 * Agents see own listings. Admins/brokers see all (RLS enforced).
 */
export async function loadCMAPageData(listingId: string): Promise<CMAPageData> {
  const supabase = await createClient()

  const [cmaRes, upgradesRes, agreementRes] = await Promise.all([
    supabase
      .from("cma_reports")
      .select("*")
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    supabase
      .from("property_upgrades")
      .select("*")
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false }),
    supabase
      .from("listing_agreements")
      .select(
        "id, listing_commission_rate, buyer_commission_rate, total_commission_rate, commission_is_flat_fee, commission_flat_amount, seller_transaction_fee, has_commission_adjustment, adjustment_type, adjustment_value, adjustment_notes, esign_status, fully_executed_at"
      )
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
  ])

  const cmaRow = cmaRes.data
  let comparables: CMAComparable[] = []
  let compScores: Record<string, AICompScore> = {}
  let riskFlags: CompRiskFlag[] = []

  if (cmaRow) {
    const [compsRes, scoresRes, flagsRes] = await Promise.all([
      supabase
        .from("cma_comparables")
        .select("*")
        .eq("cma_id", cmaRow.id)
        .order("similarity_score", { ascending: false }),
      supabase
        .from("ai_comp_scores")
        .select("*")
        .eq("cma_id", cmaRow.id),
      supabase
        .from("comp_risk_flags")
        .select("*")
        .eq("cma_id", cmaRow.id)
        .eq("is_resolved", false),
    ])

    comparables = compsRes.data ?? []
    riskFlags = flagsRes.data ?? []

    if (scoresRes.data) {
      for (const score of scoresRes.data) {
        compScores[score.comparable_id] = score
      }
    }
  }

  // Determine if auto-generated (no human actor — lifecycle triggered)
  const autoGenerated = cmaRow
    ? cmaRow.status === "auto_generated"
    : false

  const cma: CMAReport | null = cmaRow
    ? {
        ...cmaRow,
        hasAIScores: Object.keys(compScores).length > 0,
        autoGenerated,
      }
    : null

  return {
    cma,
    comparables,
    compScores,
    riskFlags,
    propertyUpgrades: upgradesRes.data ?? [],
    agreement: agreementRes.data ?? null,
  }
}

export async function loadNetSheetPageData(listingId: string): Promise<NetSheetPageData> {
  const supabase = await createClient()

  const [netSheetRes, cmaRes, agreementRes] = await Promise.all([
    supabase
      .from("net_sheet_calculations")
      .select("*")
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    supabase
      .from("cma_reports")
      .select("recommended_price")
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    supabase
      .from("listing_agreements")
      .select(
        "id, listing_commission_rate, buyer_commission_rate, total_commission_rate, commission_is_flat_fee, commission_flat_amount, seller_transaction_fee, has_commission_adjustment, adjustment_type, adjustment_value, adjustment_notes, esign_status, fully_executed_at"
      )
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
  ])

  return {
    latestNetSheet: netSheetRes.data ?? null,
    agreement: agreementRes.data ?? null,
    recommendedPrice: cmaRes.data?.recommended_price ?? null,
  }
}

export async function loadPricingPageData(listingId: string): Promise<PricingPageData> {
  const supabase = await createClient()

  const [predictionRes, historyRes, alertsRes] = await Promise.all([
    supabase
      .from("price_predictions")
      .select("*")
      .eq("listing_id", listingId)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    supabase
      .from("pricing_history")
      .select("*")
      .eq("listing_id", listingId)
      .order("recorded_at", { ascending: true }),
    supabase
      .from("price_trend_alerts")
      .select("*")
      .eq("listing_id", listingId)
      .eq("is_resolved", false)
      .order("created_at", { ascending: false }),
  ])

  return {
    latestPrediction: predictionRes.data ?? null,
    priceHistory: historyRes.data ?? [],
    activeAlerts: alertsRes.data ?? [],
  }
}

// ── Mutations ─────────────────────────────────────────────────────────────────

/**
 * Trigger AI comp scoring for the latest CMA on a listing.
 * Delegates to scoreAllComps() which handles all DB writes + kernel events.
 */
export async function triggerAICompScoring(
  cmaId: string,
  listingId: string
): Promise<{ success: boolean; scored?: number; error?: string }> {
  const supabase = await createClient()

  const { data: user } = await supabase.auth.getUser()
  if (!user.user) return { success: false, error: "Unauthenticated" }

  const { data: profile } = await supabase
    .from("users")
    .select("brokerage_id")
    .eq("id", user.user.id)
    .single()

  if (!profile?.brokerage_id) return { success: false, error: "No brokerage found" }

  const result = await scoreAllComps(
    cmaId,
    listingId,
    profile.brokerage_id,
    user.user.id
  )

  return { success: result.success, scored: result.scored, error: result.error }
}

/**
 * Trigger price prediction refresh. Uses service client for write access.
 */
export async function triggerPricePrediction(
  listingId: string
): Promise<{ success: boolean; predictedPrice?: number; error?: string }> {
  const supabase = await createClient()

  const { data: user } = await supabase.auth.getUser()
  if (!user.user) return { success: false, error: "Unauthenticated" }

  const { data: profile } = await supabase
    .from("users")
    .select("brokerage_id")
    .eq("id", user.user.id)
    .single()

  if (!profile?.brokerage_id) return { success: false, error: "No brokerage found" }

  const result = await generatePricePrediction(
    listingId,
    profile.brokerage_id,
    user.user.id
  )

  return {
    success: result.success,
    predictedPrice: result.predictedPrice,
    error: result.error,
  }
}

/**
 * Save net sheet calculation using existing calculator.
 */
export async function saveNetSheet(params: {
  listingId: string
  contactId: string
  salePrice: number
  listingCommissionRate?: number
  buyerCommissionRate?: number
  closingCosts?: number
  mortgageBalance?: number
  mortgagePayoffAmount?: number
  propertyTaxes?: number
  hoaFees?: number
  repairCredits?: number
  sellerConcessions?: number
  /** Flat brokerage transaction fee charged to the SELLER (m286/m287). */
  transactionFee?: number
  /** Agreed commission is a flat dollar fee, not a percentage (m289). */
  commissionIsFlatFee?: boolean
  /** The flat commission in dollars when commissionIsFlatFee (m289). */
  commissionFlatAmount?: number
}): Promise<{ success: boolean; netSheetId?: string; error?: string }> {
  const supabase = await createClient()

  const { data: user } = await supabase.auth.getUser()
  if (!user.user) return { success: false, error: "Unauthenticated" }

  const { data: profile } = await supabase
    .from("users")
    .select("brokerage_id")
    .eq("id", user.user.id)
    .single()

  if (!profile?.brokerage_id) return { success: false, error: "No brokerage found" }

  const svc = createServiceClient()

  // net_sheet_calculations.agent_id FKs agents(id), NOT users(id). This wrote
  // user.user.id straight in, so every insert was rejected by the foreign key and
  // the action returned an error — net_sheet_calculations had ZERO rows on the live
  // database. The Save button on the seller net sheet had never once worked.
  //
  // The FK pass that fixed 60+ of these missed this site. lib/kernel/agent-identity
  // states the rule outright: "NEVER do: agentId = user.id".
  const agentId = await resolveAgentId(svc, user.user.id)
  if (!agentId) {
    return { success: false, error: "No agent profile for this user — complete onboarding before saving a net sheet." }
  }

  // ── Persist the sheet that was SHOWN, not a second guess at it ──────────────
  //
  // This used to re-derive the totals with its own fallbacks — `?? 3` for each
  // commission side and `salePrice * 0.02` for closing costs — none of which the
  // displayed sheet uses. Three ways a SAVED sheet could disagree with the sheet
  // the seller was actually shown:
  //
  //   1. FLAT FEE ERASED. The tab charges a flat agreement fee as-is (buyer side
  //      zero). There was no field to send it, so a $4,995 flat fee reloaded as
  //      3% + 3% of the sale price. m289 adds the columns; the params carry it.
  //   2. REGIONAL CLOSING COSTS DISCARDED. The tab defaults the closing-cost line
  //      to deriveNetSheetClosingCostSection — itemized title fees and doc stamps
  //      for the listing's state. It sends `undefined` when the agent hasn't typed
  //      an override, and the flat 2% silently replaced the county-customary math.
  //      Now derived here with the SAME helper, from the listing's own state.
  //   3. COMMISSION GUESSED AT 3+3. When rates are absent the agreed commission is
  //      resolved from the listing agreement through resolveAgreedCommission —
  //      the same resolver the offers page and the cron runner already use —
  //      instead of a house number that matches no agreement.
  const { data: listingRow } = await svc
    .from("listings")
    .select("id, state, commission_rate")
    .eq("id", params.listingId)
    .eq("brokerage_id", profile.brokerage_id)
    .maybeSingle()

  const { data: agreement } = await svc
    .from("listing_agreements")
    .select("listing_commission_rate, buyer_commission_rate, total_commission_rate, commission_is_flat_fee, commission_flat_amount")
    .eq("listing_id", params.listingId)
    .eq("brokerage_id", profile.brokerage_id)
    .maybeSingle()

  // Commission: explicit caller values win (the agent may have edited them on the
  // sheet); otherwise fall back to the agreement via the canonical resolver.
  const agreed = resolveAgreedCommission({
    agreement: agreement ?? null,
    listingCommissionRatePercent: (listingRow?.commission_rate as number | null) ?? null,
    referencePrice: params.salePrice,
  })

  const isFlatFee = params.commissionIsFlatFee ?? agreed.isFlatFee
  const flatAmount = params.commissionFlatAmount ?? agreed.flatAmount ?? null

  // A flat fee is charged as-is and the buyer side is folded into it — mirrors the
  // tab exactly (listComm = flatAmount, buyerComm = 0).
  const listingRate = isFlatFee ? 0 : params.listingCommissionRate ?? agreed.rate * 100
  const buyerRate = isFlatFee ? 0 : params.buyerCommissionRate ?? 0
  const totalCommission = isFlatFee
    ? Number(flatAmount ?? 0)
    : params.salePrice * (listingRate / 100) + params.salePrice * (buyerRate / 100)

  // Closing costs: an explicit override wins; else the county-customary midpoint
  // for the listing's state; else (state unknown) the legacy 2%.
  const closingSection = deriveNetSheetClosingCostSection(
    params.salePrice,
    (listingRow?.state as string | null) ?? null,
  )
  const closingCosts =
    params.closingCosts ?? closingSection?.midpoint ?? params.salePrice * 0.02

  // Costs that do NOT move with the sale price. A payoff, a tax bill, HOA dues,
  // agreed repair credits and a flat transaction fee are the same dollars at any
  // price — only commission (and the percentage-based closing costs) scale.
  const fixedCosts =
    (params.mortgagePayoffAmount ?? params.mortgageBalance ?? 0) +
    (params.propertyTaxes ?? 0) +
    (params.hoaFees ?? 0) +
    (params.repairCredits ?? 0) +
    (params.sellerConcessions ?? 0) +
    (params.transactionFee ?? 0)

  const totalCosts = totalCommission + closingCosts + fixedCosts
  const netProceeds = params.salePrice - totalCosts

  /**
   * Scenario net at a different price. The old version multiplied the ENTIRE cost
   * stack by the scenario factor, which shrank the mortgage payoff, the tax bill
   * and the flat transaction fee by 5% on a quick sale — flattering the number by
   * whatever those happened to total. Only the price-proportional lines move.
   */
  function scenarioNet(factor: number): { salePrice: number; netProceeds: number } {
    const price = Math.round(params.salePrice * factor)
    const commission = isFlatFee
      ? Number(flatAmount ?? 0)
      : price * (listingRate / 100) + price * (buyerRate / 100)
    const closing =
      params.closingCosts != null
        ? params.closingCosts * factor // an explicit override is a % of price in practice
        : deriveNetSheetClosingCostSection(price, (listingRow?.state as string | null) ?? null)?.midpoint ??
          price * 0.02
    return { salePrice: price, netProceeds: Math.round(price - (commission + closing + fixedCosts)) }
  }

  const scenarios = [
    { name: "Recommended", salePrice: params.salePrice, netProceeds },
    { name: "Quick Sale (-5%)", ...scenarioNet(0.95) },
    { name: "Premium (+5%)", ...scenarioNet(1.05) },
  ]

  const expires = new Date()
  expires.setDate(expires.getDate() + 90)

  const { data: inserted, error } = await svc
    .from("net_sheet_calculations")
    .insert({
      brokerage_id: profile.brokerage_id,
      listing_id: params.listingId,
      contact_id: params.contactId,
      agent_id: agentId,
      sale_price: params.salePrice,
      listing_commission_rate: listingRate,
      buyer_commission_rate: buyerRate,
      commission_is_flat_fee: isFlatFee,
      commission_flat_amount: isFlatFee ? flatAmount : null,
      closing_costs: closingCosts,
      transaction_fee: params.transactionFee ?? 0,
      mortgage_balance: params.mortgageBalance ?? 0,
      mortgage_payoff_amount: params.mortgagePayoffAmount ?? params.mortgageBalance ?? 0,
      property_taxes: params.propertyTaxes ?? 0,
      hoa_fees: params.hoaFees ?? 0,
      repair_credits: params.repairCredits ?? 0,
      seller_concessions: params.sellerConcessions ?? 0,
      gross_proceeds: params.salePrice,
      total_costs: totalCosts,
      net_proceeds: netProceeds,
      scenarios,
      expires_at: expires.toISOString(),
    })
    .select("id")
    .single()

  if (error || !inserted) {
    return { success: false, error: error?.message ?? "Insert failed" }
  }

  return { success: true, netSheetId: inserted.id }
}

/**
 * Resolve a price trend alert.
 */
export async function resolvePriceTrendAlert(
  alertId: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { success: false, error: "Unauthorized" }

  const { data: u } = await supabase
    .from("users")
    .select("brokerage_id")
    .eq("id", user.id)
    .maybeSingle()
  if (!u?.brokerage_id) return { success: false, error: "Unauthorized" }

  // Verify the alert belongs to caller's brokerage before resolving
  const { data: existing } = await supabase
    .from("price_trend_alerts")
    .select("brokerage_id")
    .eq("id", alertId)
    .maybeSingle()
  if (!existing) return { success: false, error: "Alert not found" }
  if (existing.brokerage_id !== u.brokerage_id) return { success: false, error: "Forbidden" }

  const { error } = await supabase
    .from("price_trend_alerts")
    .update({ is_resolved: true, resolved_at: new Date().toISOString() })
    .eq("id", alertId)
    .eq("brokerage_id", u.brokerage_id)

  return { success: !error, error: error?.message }
}
