'use server'

import { createServiceClient } from '@/lib/supabase/service'
import { dispatchDirectMail } from '@/lib/providers/dispatch'

export interface DirectMailContext {
  leadId: string
  brokerageId: string
  agentUserId?: string
  templateId?: string
  firstName: string
  lastName: string
  mailingAddress?: string
  city?: string
  state?: string
  zip?: string
  motivation_type?: string
  property_interest?: string
}

export async function shouldTriggerDirectMail(leadId: string): Promise<boolean> {
  const supabase = createServiceClient()
  
  // Get lead data
  const { data: lead } = await supabase
    .from('leads')
    .select('*')
    .eq('id', leadId)
    .single()
  
  if (!lead) return false
  
  // Check if lead has confirmed mailing address in enrichment data
  const hasAddress = !!(
    lead.enrichment_status === 'completed' &&
    lead.enrichment_confidence >= 0.8
  )
  
  // Check email engagement (low engagement might trigger direct mail)
  const { data: messages } = await supabase
    .from('messages')
    .select('id')
    .eq('contact_id', leadId)
    .eq('type', 'email')
  
  const emailEngagement = messages?.length || 0
  const lowEmailEngagement = emailEngagement === 0
  
  return hasAddress && lowEmailEngagement
}

export async function triggerDirectMailCampaign(context: DirectMailContext) {
  if (!context.mailingAddress || !context.city || !context.state || !context.zip) {
    return { success: false, error: 'Missing address data' }
  }
  
  const supabase = createServiceClient()
  
  try {
    // Create direct mail campaign record
    const { data: campaign } = await supabase
      .from('direct_mail_campaigns')
      .insert({
        contact_id: context.leadId,
        campaign_name: `AI ISA Outreach - ${context.firstName} ${context.lastName}`,
        target_audience: 'individual_lead',
        quantity: 1,
        design_url: null, // Will be generated by Lob/PostcardMania
        status: 'pending',
        created_at: new Date().toISOString()
      })
      .select()
      .single()
    
    // Step 3: Dispatch through provider resolution layer
    const result = await dispatchDirectMail({
      brokerageId:    context.brokerageId,
      userId:         context.agentUserId,
      recipientName:  `${context.firstName} ${context.lastName}`.trim(),
      mailingAddress: context.mailingAddress ?? '',
      city:           context.city ?? '',
      state:          context.state ?? '',
      zip:            context.zip ?? '',
      templateId:     context.templateId ?? process.env.LOB_DEFAULT_TEMPLATE_ID ?? '',
      mergeVars: {
        first_name:        context.firstName,
        motivation_type:   context.motivation_type ?? '',
        property_interest: context.property_interest ?? '',
      },
      systemSource: 'ai_isa',
      leadId:       context.leadId,
    })

    // Step 4: Fire-and-forget provider log
    supabase.from('message_provider_logs').insert({
      brokerage_id:        context.brokerageId,
      provider_key:        'lob',
      channel:             'direct_mail',
      direction:           'outbound',
      provider_message_id: result.messageId ?? null,
      provider_status:     result.success ? 'sent' : 'failed',
      error_message:       result.error ?? null,
    }).then(() => {}).catch(() => {})

    // Log activity
    await supabase.from('activities').insert({
      contact_id:    context.leadId,
      brokerage_id:  context.brokerageId,
      activity_type: 'ai_isa_direct_mail',
      title:         'Direct Mail Triggered',
      description:   `Personalized direct mail sent to ${context.mailingAddress}`,
      status:        'completed',
      created_at:    new Date().toISOString(),
    })

    return {
      success:    result.success,
      campaignId: campaign?.id,
      error:      result.error,
    }
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error)

    await supabase.from('automation_errors').insert({
      workflow_name: 'ai_isa_direct_mail',
      error_message: msg,
      context_json:  JSON.stringify(context),
      severity:      'low',
      status:        'open',
      created_at:    new Date().toISOString(),
    })

    return { success: false, error: msg }
  }
}
