'use server'

import { createServiceClient } from '@/lib/supabase/service'

export interface DirectMailContext {
  leadId: string
  firstName: string
  lastName: string
  mailingAddress?: string
  city?: string
  state?: string
  zip?: string
  motivation_type?: string
  property_interest?: string
}

export async function shouldTriggerDirectMail(leadId: string): Promise<boolean> {
  const supabase = createServiceClient()
  
  // Get lead data
  const { data: lead } = await supabase
    .from('leads')
    .select('*')
    .eq('id', leadId)
    .single()
  
  if (!lead) return false
  
  // Check if lead has confirmed mailing address in enrichment data
  const hasAddress = !!(
    lead.enrichment_status === 'completed' &&
    lead.enrichment_confidence >= 0.8
  )
  
  // Check email engagement (low engagement might trigger direct mail)
  const { data: messages } = await supabase
    .from('messages')
    .select('id')
    .eq('contact_id', leadId)
    .eq('type', 'email')
  
  const emailEngagement = messages?.length || 0
  const lowEmailEngagement = emailEngagement === 0
  
  return hasAddress && lowEmailEngagement
}

export async function triggerDirectMailCampaign(context: DirectMailContext) {
  console.log('[AI ISA] Triggering direct mail for lead:', context.leadId)
  
  if (!context.mailingAddress || !context.city || !context.state || !context.zip) {
    console.log('[AI ISA] Insufficient address data for direct mail')
    return { success: false, error: 'Missing address data' }
  }
  
  const supabase = createServiceClient()
  
  try {
    // Create direct mail campaign record
    const { data: campaign } = await supabase
      .from('direct_mail_campaigns')
      .insert({
        contact_id: context.leadId,
        campaign_name: `AI ISA Outreach - ${context.firstName} ${context.lastName}`,
        target_audience: 'individual_lead',
        quantity: 1,
        design_url: null, // Will be generated by Lob/PostcardMania
        status: 'pending',
        created_at: new Date().toISOString()
      })
      .select()
      .single()
    
    // TODO: Integrate with Lob or PostcardMania API
    // const lobResponse = await fetch('https://api.lob.com/v1/postcards', {
    //   method: 'POST',
    //   headers: {
    //     'Authorization': `Basic ${Buffer.from(process.env.LOB_API_KEY + ':').toString('base64')}`,
    //     'Content-Type': 'application/json'
    //   },
    //   body: JSON.stringify({
    //     to: {
    //       name: `${context.firstName} ${context.lastName}`,
    //       address_line1: context.mailingAddress,
    //       address_city: context.city,
    //       address_state: context.state,
    //       address_zip: context.zip
    //     },
    //     front: 'personalized_front_design_url',
    //     back: 'personalized_back_design_url'
    //   })
    // })
    
    // Log activity — Agent task (correct location, no changes) — activity_type: ai_isa_direct_mail
    const { data: lead } = await supabase
      .from('leads')
      .select('brokerage_id')
      .eq('id', context.leadId)
      .single()
    
    if (lead) {
      await supabase.from('activities').insert({
        contact_id: context.leadId,
        brokerage_id: lead.brokerage_id,
        activity_type: 'ai_isa_direct_mail',
        title: 'Direct Mail Triggered',
        description: `Personalized direct mail sent to ${context.mailingAddress}`,
        status: 'completed',
        created_at: new Date().toISOString()
      })
    }
    
    return {
      success: true,
      campaignId: campaign?.id
    }
  } catch (error: any) {
    console.error('[AI ISA] Direct mail trigger error:', error)
    
    await supabase.from('automation_errors').insert({
      workflow_name: 'ai_isa_direct_mail',
      error_message: error.message,
      context_json: JSON.stringify(context),
      severity: 'low',
      status: 'new',
      created_at: new Date().toISOString()
    })
    
    return {
      success: false,
      error: error.message
    }
  }
}
