'use server'

import { createServiceClient } from '@/lib/supabase/service'
import { dispatchDirectMail } from '@/lib/providers/dispatch'

export interface DirectMailContext {
  leadId: string
  brokerageId: string
  agentUserId?: string
  templateId?: string
  firstName: string
  lastName: string
  mailingAddress?: string
  city?: string
  state?: string
  zip?: string
  motivation_type?: string
  property_interest?: string
}

export async function shouldTriggerDirectMail(leadId: string): Promise<boolean> {
  // Wave 36 — gate on the canonical `mailing_address_verified` column,
  // not the enrichment-confidence proxy (which could be high for a lead
  // whose mailing address still failed Lob US verification, the only
  // signal that actually predicts deliverability).
  //
  // Removed the "low email engagement" filter — direct mail is one of
  // the two channels we're allowed to use for an unconsented lead, so
  // gating it behind "no email reply yet" gave up the channel for any
  // lead who briefly engaged. The de-conflict gate inside dispatch
  // still suppresses over-touches at the 30-day cap.
  const supabase = createServiceClient()
  const { data: lead } = await supabase
    .from('leads')
    .select('mailing_address_verified, mailing_address, mailing_city, mailing_state, mailing_zip')
    .eq('id', leadId)
    .maybeSingle()
  const l = lead as {
    mailing_address_verified: boolean | null
    mailing_address:          string | null
    mailing_city:             string | null
    mailing_state:            string | null
    mailing_zip:              string | null
  } | null
  if (!l) return false
  if (l.mailing_address_verified !== true) return false
  return !!(l.mailing_address && l.mailing_city && l.mailing_state && l.mailing_zip)
}

export async function triggerDirectMailCampaign(context: DirectMailContext) {
  if (!context.mailingAddress || !context.city || !context.state || !context.zip) {
    return { success: false, error: 'Missing address data' }
  }

  const supabase = createServiceClient()

  // Wave 36 — defense in depth. The hard gate inside dispatchDirectMail
  // would also block an unverified send, but failing fast here lets us
  // avoid creating a direct_mail_campaigns row we'll never use.
  const eligible = await shouldTriggerDirectMail(context.leadId)
  if (!eligible) {
    return { success: false, error: 'Lead mailing address not verified — Lob send blocked' }
  }

  try {
    // Create direct mail campaign record. Wave 36 — write the canonical
    // tenant columns (brokerage_id, lead_id) explicitly; the legacy
    // `contact_id` column accepted a lead id historically but the
    // canonical lead_id column is what aggregation queries read.
    const { data: campaign } = await supabase
      .from('direct_mail_campaigns')
      .insert({
        brokerage_id:   context.brokerageId,
        lead_id:        context.leadId,
        campaign_name:  `AI ISA Outreach - ${context.firstName} ${context.lastName}`,
        target_audience: 'individual_lead',
        quantity:       1,
        design_url:     null, // Generated by Lob template referenced via templateId
        status:         'pending',
        is_ai_generated: true,
        created_at:     new Date().toISOString(),
      })
      .select()
      .single()
    
    // Step 3: Dispatch through provider resolution layer
    const result = await dispatchDirectMail({
      brokerageId:    context.brokerageId,
      userId:         context.agentUserId,
      recipientName:  `${context.firstName} ${context.lastName}`.trim(),
      mailingAddress: context.mailingAddress ?? '',
      city:           context.city ?? '',
      state:          context.state ?? '',
      zip:            context.zip ?? '',
      templateId:     context.templateId ?? process.env.LOB_DEFAULT_TEMPLATE_ID ?? '',
      mergeVars: {
        first_name:        context.firstName,
        motivation_type:   context.motivation_type ?? '',
        property_interest: context.property_interest ?? '',
      },
      systemSource: 'ai_isa',
      leadId:       context.leadId,
    })

    // Step 4: Fire-and-forget provider log
    supabase.from('message_provider_logs').insert({
      brokerage_id:        context.brokerageId,
      provider_key:        'lob',
      channel:             'direct_mail',
      direction:           'outbound',
      provider_message_id: result.messageId ?? null,
      provider_status:     result.success ? 'sent' : 'failed',
      error_message:       result.error ?? null,
    })

    // Log activity
    await supabase.from('activities').insert({
      contact_id:    context.leadId,
      brokerage_id:  context.brokerageId,
      activity_type: 'ai_isa_direct_mail',
      title:         'Direct Mail Triggered',
      description:   `Personalized direct mail sent to ${context.mailingAddress}`,
      status:        'completed',
      created_at:    new Date().toISOString(),
    })

    return {
      success:    result.success,
      campaignId: campaign?.id,
      error:      result.error,
    }
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : String(error)

    await supabase.from('automation_errors').insert({
      workflow_name: 'ai_isa_direct_mail',
      error_message: msg,
      context_json:  JSON.stringify(context),
      severity:      'low',
      status:        'open',
      created_at:    new Date().toISOString(),
    })

    return { success: false, error: msg }
  }
}
