'use strict'

import { UserRole } from '@/app/types/roles'
import { NavigationConfig, NavItem } from '@/app/types/navigation'

export const NAVIGATION_BY_ROLE: Record<UserRole, NavigationConfig> = {
  agent: {
    sidebarItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing', icon: 'Sparkles' },
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/agent', icon: 'LayoutGrid' },
      { id: 'operations', label: 'Operations', href: '/dashboard/operations', icon: 'Activity' },
      // NOTE: agents work contacts — "My Leads", "Lead Acquisition", and "Lead Intelligence"
      // are intentionally excluded. Lead intake is admin/system; ISA qualification is system.
      { id: 'contacts', label: 'My Contacts', href: '/crm', icon: 'Users' },
      { id: 'listings', label: 'My Listings', href: '/dashboard/listings', icon: 'Home' },
      { id: 'open-houses', label: 'Open Houses', href: '/dashboard/open-houses', icon: 'CalendarDays' },
      { id: 'transactions', label: 'Transactions', href: '/dashboard/transactions', icon: 'FileText' },
      { id: 'forms-library', label: 'Forms Library', href: '/dashboard/forms', icon: 'ClipboardList' },
      { id: 'divider1', divider: true },
      {
        id: 'video-tools',
        label: 'Video Tools',
        icon: 'Video',
        children: [
          { id: 'video-studio', label: 'Video Studio', href: '/dashboard/videos/create' },
          { id: 'video-assistant', label: 'Video Assistant', href: '/video-assistant' },
          { id: 'video-board', label: 'Video Board', href: '/dashboard/videos/board' },
          { id: 'video-library', label: 'Video Library', href: '/dashboard/videos/library' },
          { id: 'video-analytics', label: 'Video Analytics', href: '/dashboard/videos/analytics' },
          { id: 'video-snippets', label: 'Snippets', href: '/dashboard/videos/snippets' },
        ],
      },
      {
        id: 'content',
        label: 'Marketing & Content',
        icon: 'Palette',
        children: [
          { id: 'marketing-studio', label: 'Marketing Studio', href: '/dashboard/marketing/studio' },
          { id: 'marketing-ops', label: 'Ops Center', href: '/dashboard/marketing/ops' },
          { id: 'social-dashboard', label: 'Social Dashboard', href: '/dashboard/social' },
          { id: 'lead-magnets', label: 'Lead Magnets', href: '/dashboard/admin/lead-magnets' },
          { id: 'blog', label: 'Blog Posts', href: '/dashboard/marketing/blog' },
          { id: 'podcast', label: 'Podcast Studio', href: '/dashboard/marketing/podcast' },
          { id: 'seo', label: 'SEO Dashboard', href: '/dashboard/marketing/seo' },
          { id: 'competitors', label: 'Competitors', href: '/dashboard/marketing/competitors' },
        ],
      },
      {
        id: 'campaigns',
        label: 'Campaigns',
        icon: 'Megaphone',
        children: [
          { id: 'campaigns-hub', label: 'Campaigns Hub', href: '/dashboard/campaigns' },
          { id: 'sequences', label: 'Automation Sequences', href: '/dashboard/campaigns/sequences' },
          { id: 'ads', label: 'Ad Campaigns', href: '/dashboard/campaigns/ads' },
          { id: 'direct-mail', label: 'Direct Mail', href: '/dashboard/campaigns/mail' },
          { id: 'repurpose', label: 'Repurpose Content', href: '/dashboard/campaigns/repurpose' },
          { id: 'competitive', label: 'Competitive Intel', href: '/dashboard/campaigns/competitive' },
          { id: 'roi', label: 'Campaign ROI', href: '/dashboard/campaigns/roi' },
        ],
      },
      {
        id: 'communications',
        label: 'Communications',
        icon: 'MessageCircle',
        children: [
          { id: 'inbox', label: 'Inbox', href: '/dashboard/inbox', badgeKey: 'unread_notifications' },
          { id: 'outreach', label: 'AI Outreach', href: '/dashboard/communications/outreach' },
          { id: 'sequences-comm', label: 'Drip Sequences', href: '/dashboard/communications/sequences' },
          { id: 'intelligence', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence' },
          { id: 'handoff-cockpit', label: 'Handoff Cockpit', href: '/dashboard/communications/handoffs' },
        ],
      },
      { id: 'market-insights', label: 'Market Insights', href: '/dashboard/market-insights', icon: 'TrendingUp' },
      { id: 'patterns', label: 'Behavioral Patterns', href: '/dashboard/patterns', icon: 'Activity' },
      { id: 'financials', label: 'My Financials', href: '/dashboard/financials/agent', icon: 'DollarSign' },
      { id: 'credit-pipeline', label: 'Credit Pipeline', href: '/credit-pipeline', icon: 'CreditCard' },
      {
        id: 'sphere',
        label: 'Sphere of Influence',
        icon: 'Users',
        href: '/past-clients',
        children: [
          { id: 'sphere-all', label: 'All Sphere Contacts', href: '/past-clients' },
          { id: 'sphere-referrals', label: 'Referrals', href: '/past-clients?tab=referrals' },
          { id: 'sphere-reviews', label: 'Reviews & Reputation', href: '/past-clients?tab=reviews' },
          { id: 'sphere-gifting', label: 'Gifting & Milestones', href: '/past-clients?tab=gifting' },
        ],
      },
      { id: 'academy', label: 'Academy', href: '/academy', icon: 'BookOpen' },
      { id: 'approvals', label: 'Approvals', href: '/approvals', icon: 'CheckSquare' },
      { id: 'divider2', divider: true },
      {
        id: 'ai-tools',
        label: 'AI Tools',
        icon: 'Sparkles',
        children: [
          { id: 'ai-tools-hub', label: 'AI Toolkit', href: '/dashboard/ai-tools' },
          { id: 'ai-chat', label: 'AI Chat', href: '/dashboard/chat' },
          { id: 'voice-command', label: 'Voice Assistant', href: '/dashboard/voice' },
          { id: 'ai-briefing', label: 'Daily Briefing', href: '/dashboard/briefing' },
        ],
      },
      { id: 'reporting-center', label: 'Reporting Center', href: '/dashboard/reporting', icon: 'BarChart3' },
      { id: 'coaching', label: 'Training & Coaching', href: '/dashboard/coaching', icon: 'Award' },
      { id: 'motivation', label: 'Motivation', href: '/dashboard/motivation', icon: 'Trophy' },
      { id: 'diagnosis', label: 'Business Diagnosis', href: '/dashboard/diagnosis', icon: 'Stethoscope' },
      { id: 'reports', label: 'Reports', href: '/dashboard/reports', icon: 'BarChart3' },
      {
        id: 'agent-tools',
        label: 'Agent Tools',
        icon: 'Wrench',
        children: [
          { id: 'business-cards', label: 'Business Cards', href: '/dashboard/agent/business-cards' },
          { id: 'qr-codes', label: 'QR Codes', href: '/dashboard/agent/qr-codes' },
          { id: 'home-value', label: 'Home Value Tool', href: '/dashboard/tools/home-value' },
        ],
      },
      { id: 'notifications', label: 'Notifications', href: '/notifications', icon: 'Bell' },
      { id: 'divider3', divider: true },
      {
        id: 'settings',
        label: 'Settings',
        icon: 'Settings',
        children: [
          { id: 'my-profile', label: 'My Profile', href: '/dashboard/profile' },
          { id: 'settings-general', label: 'General', href: '/dashboard/settings/general' },
          { id: 'settings-calendar', label: 'Calendar Sync', href: '/dashboard/settings/calendar' },
          { id: 'settings-branding', label: 'Branding', href: '/dashboard/settings/branding' },
          { id: 'settings-integrations', label: 'Integrations', href: '/dashboard/settings/integrations' },
          { id: 'podcast-channels', label: 'Podcast Channels', href: '/dashboard/settings/podcast-channels' },
          { id: 'knowledge-base', label: 'Knowledge Base', href: '/dashboard/settings/knowledge-base' },
          { id: 'listing-templates', label: 'Listing Templates', href: '/dashboard/settings/listing-task-templates' },
        ],
      },
    ],
    topNavItems: [
      { id: 'search', label: 'Search', icon: 'Search' },
      { id: 'notifications', label: 'Notifications', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/agent', icon: 'LayoutGrid' },
      { id: 'contacts', label: 'Contacts', href: '/crm', icon: 'Users' },
      { id: 'listings', label: 'Listings', href: '/dashboard/listings', icon: 'Home' },
      { id: 'more', label: 'More', href: '/dashboard', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'quick-contact', label: 'Create Contact', href: '/contacts/new' },
      { id: 'video-studio', label: 'Create AI Video', href: '/dashboard/videos/create' },
      { id: 'marketing-studio', label: 'Marketing Studio', href: '/dashboard/marketing/studio' },
      { id: 'lead-intel', label: 'Lead Intelligence', href: '/leads' },
      { id: 'briefing', label: 'AI Daily Briefing', href: '/dashboard/briefing' },
      { id: 'voice', label: 'Voice Command', href: '/dashboard/voice' },
      { id: 'outreach', label: 'AI Outreach', href: '/dashboard/communications/outreach' },
      { id: 'market', label: 'Market Insights', href: '/dashboard/market-insights' },
    ],
  },

  broker: {
    sidebarItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing', icon: 'Sparkles' },
      { id: 'dashboard', label: 'Broker Dashboard', href: '/dashboard/brokerage', icon: 'LayoutGrid' },
      { id: 'operations', label: 'Operations', href: '/dashboard/operations', icon: 'Activity' },
      { id: 'team', label: 'My Team', href: '/dashboard/team', icon: 'Users' },
      { id: 'lead-intel', label: 'Lead Intelligence', href: '/leads', icon: 'Brain' },
      { id: 'acquisition', label: 'Lead Acquisition', href: '/dashboard/acquisition', icon: 'Zap' },
      { id: 'analytics', label: 'Analytics', href: '/analytics', icon: 'BarChart3' },
      { id: 'transactions', label: 'All Transactions', href: '/dashboard/transactions', icon: 'FileText' },
      { id: 'forms-library', label: 'Forms Library', href: '/dashboard/forms', icon: 'ClipboardList' },
      { id: 'approvals', label: 'Approvals', href: '/approvals', icon: 'CheckSquare', badgeKey: 'pending_approvals' },
      { id: 'divider1', divider: true },
      {
        id: 'intel',
        label: 'Intelligence',
        icon: 'Brain',
        children: [
          { id: 'intelligence-center', label: 'Intelligence Center', href: '/dashboard/brokerage/intelligence' },
          { id: 'deal-health', label: 'Deal Health', href: '/dashboard/brokerage/deal-health' },
          { id: 'fatigue', label: 'Agent Fatigue', href: '/dashboard/brokerage/fatigue' },
          { id: 'team-heatmap', label: 'Team Heatmap', href: '/dashboard/team-heatmap' },
          { id: 'patterns', label: 'Behavioral Patterns', href: '/dashboard/patterns' },
          { id: 'market-insights', label: 'Market Insights', href: '/dashboard/market-insights' },
          { id: 'coordination', label: 'AI Coordination', href: '/dashboard/coordination' },
          { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality' },
          { id: 'recruiting-roi', label: 'Recruiting ROI', href: '/dashboard/recruiting-roi' },
        ],
      },
      {
        id: 'video-tools',
        label: 'Video Tools',
        icon: 'Video',
        children: [
          { id: 'video-studio', label: 'Video Studio', href: '/dashboard/videos/create' },
          { id: 'video-library', label: 'Video Library', href: '/dashboard/videos/library' },
          { id: 'video-analytics', label: 'Video Analytics', href: '/dashboard/videos/analytics' },
        ],
      },
      {
        id: 'content',
        label: 'Marketing & Content',
        icon: 'Palette',
        children: [
          { id: 'marketing-studio', label: 'Marketing Studio', href: '/dashboard/marketing/studio' },
          { id: 'marketing-ops', label: 'Ops Center', href: '/dashboard/marketing/ops' },
          { id: 'social-dashboard', label: 'Social Dashboard', href: '/dashboard/social' },
          { id: 'lead-magnets', label: 'Lead Magnets', href: '/dashboard/admin/lead-magnets' },
          { id: 'blog', label: 'Blog Posts', href: '/dashboard/marketing/blog' },
          { id: 'podcast', label: 'Podcast Studio', href: '/dashboard/marketing/podcast' },
          { id: 'seo', label: 'SEO Dashboard', href: '/dashboard/marketing/seo' },
          { id: 'competitors', label: 'Competitors', href: '/dashboard/marketing/competitors' },
        ],
      },
      {
        id: 'communications',
        label: 'Communications',
        icon: 'MessageCircle',
        children: [
          { id: 'broker-inbox', label: 'Inbox', href: '/dashboard/inbox' },
          { id: 'intelligence', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence' },
          { id: 'outreach', label: 'AI Outreach', href: '/dashboard/communications/outreach' },
          { id: 'sequences', label: 'Drip Sequences', href: '/dashboard/communications/sequences' },
          { id: 'handoff-cockpit', label: 'Handoff Cockpit', href: '/dashboard/communications/handoffs' },
        ],
      },
      {
        id: 'financials',
        label: 'Financials',
        icon: 'DollarSign',
        children: [
          { id: 'brokerage-pl', label: 'Brokerage P&L', href: '/dashboard/financials/brokerage' },
          { id: 'team-financials', label: 'Team Financials', href: '/dashboard/financials/team' },
          { id: 'commissions', label: 'Commissions', href: '/dashboard/financials/commissions' },
          { id: 'expenses', label: 'Expenses', href: '/dashboard/financials/expenses' },
          { id: 'payouts', label: 'Agent Payouts', href: '/dashboard/financials/payouts' },
          { id: 'credit-pipeline', label: 'Credit Pipeline', href: '/credit-pipeline' },
        ],
      },
      { id: 'compliance', label: 'Compliance', href: '/dashboard/compliance', icon: 'Shield' },
      { id: 'vendors', label: 'Partner Portal', href: '/dashboard/vendors', icon: 'Users' },
      { id: 'system-intel', label: 'System Intelligence', href: '/dashboard/system', icon: 'Radar' },
      {
        id: 'sphere',
        label: 'Sphere of Influence',
        icon: 'Users',
        href: '/past-clients',
        children: [
          { id: 'sphere-all', label: 'All Sphere Contacts', href: '/past-clients' },
          { id: 'sphere-referrals', label: 'Referrals', href: '/past-clients?tab=referrals' },
          { id: 'sphere-reviews', label: 'Reviews & Reputation', href: '/past-clients?tab=reviews' },
          { id: 'sphere-gifting', label: 'Gifting & Milestones', href: '/past-clients?tab=gifting' },
        ],
      },
      { id: 'leaderboard', label: 'Leaderboard', href: '/dashboard/leaderboard', icon: 'Award' },
      { id: 'workflows', label: 'Workflows', href: '/workflows', icon: 'Workflow' },
      { id: 'usage-metrics', label: 'Usage Metrics', href: '/admin/usage', icon: 'Activity' },
      { id: 'assignment-rules', label: 'Assignment Rules', href: '/dashboard/admin/assignment-rules', icon: 'GitBranch' },
      { id: 'reports', label: 'Reports', href: '/dashboard/reports', icon: 'BarChart3' },
      { id: 'divider2', divider: true },
      {
        id: 'settings',
        label: 'Brokerage Settings',
        icon: 'Settings',
        children: [
          { id: 'general', label: 'General', href: '/dashboard/settings/general' },
          { id: 'branding', label: 'Branding', href: '/dashboard/settings/branding' },
          { id: 'team-mgmt', label: 'Team Management', href: '/dashboard/settings/teams' },
          { id: 'integrations', label: 'Integrations', href: '/dashboard/settings/integrations' },
          { id: 'knowledge-base', label: 'Knowledge Base', href: '/dashboard/settings/knowledge-base' },
        ],
      },
    ],
    topNavItems: [
      { id: 'search', label: 'Search', icon: 'Search' },
      { id: 'alerts', label: 'Alerts', icon: 'AlertCircle', badgeKey: 'pending_approvals' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/brokerage', icon: 'LayoutGrid' },
      { id: 'team', label: 'Team', href: '/dashboard/team', icon: 'Users' },
      { id: 'analytics', label: 'Analytics', href: '/analytics', icon: 'BarChart3' },
      { id: 'financials', label: 'Financials', href: '/dashboard/financials/brokerage', icon: 'DollarSign' },
      { id: 'more', label: 'More', href: '/dashboard', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing' },
      { id: 'deal-health', label: 'Deal Health Dashboard', href: '/dashboard/brokerage/deal-health' },
      { id: 'team-heatmap', label: 'Team Heatmap', href: '/dashboard/team-heatmap' },
      { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality' },
      { id: 'compliance', label: 'Compliance Dashboard', href: '/dashboard/compliance' },
      { id: 'marketing', label: 'Marketing Studio', href: '/dashboard/marketing/studio' },
    ],
  },

  isa: {
    sidebarItems: [
      { id: 'dashboard', label: 'AI-ISA Console', href: '/dashboard/isa', icon: 'LayoutGrid' },
      { id: 'calling', label: 'Calling Queue', href: '/dashboard/isa/calling', icon: 'Phone', badgeKey: 'isa_queue_count' },
      { id: 'leads', label: 'Lead Intelligence', href: '/leads', icon: 'Zap' },
      { id: 'outreach', label: 'AI Outreach', href: '/dashboard/communications/outreach', icon: 'Send' },
      { id: 'sequences', label: 'Drip Sequences', href: '/dashboard/communications/sequences', icon: 'Repeat' },
      { id: 'campaigns', label: 'Campaigns', href: '/dashboard/isa/campaigns', icon: 'Megaphone' },
      { id: 'scripts', label: 'Scripts', href: '/dashboard/isa/scripts', icon: 'FileText' },
      { id: 'analytics', label: 'My Stats', href: '/dashboard/isa/analytics', icon: 'BarChart3' },
      { id: 'intelligence', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence', icon: 'Brain' },
      { id: 'divider1', divider: true },
      {
        id: 'video-tools',
        label: 'Video Tools',
        icon: 'Video',
        children: [
          { id: 'video-studio', label: 'Video Studio', href: '/dashboard/videos/create' },
          { id: 'video-library', label: 'Video Library', href: '/dashboard/videos/library' },
        ],
      },
      { id: 'settings', label: 'Settings', href: '/dashboard/settings/general', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'notifications', label: 'Notifications', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'calling', label: 'Calling', href: '/dashboard/isa/calling', icon: 'Phone' },
      { id: 'leads', label: 'Leads', href: '/leads', icon: 'Zap' },
      { id: 'outreach', label: 'Outreach', href: '/dashboard/communications/outreach', icon: 'Send' },
      { id: 'analytics', label: 'Stats', href: '/dashboard/isa/analytics', icon: 'BarChart3' },
      { id: 'more', label: 'More', href: '/dashboard', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'dial-number', label: 'Open Calling Queue', href: '/dashboard/isa/calling' },
      { id: 'outreach', label: 'AI Outreach Center', href: '/dashboard/communications/outreach' },
      { id: 'new-campaign', label: 'ISA Campaigns', href: '/dashboard/isa/campaigns' },
      { id: 'voice-isa', label: 'Voice ISA Dashboard', href: '/dashboard/voice/isa' },
    ],
  },

  admin: {
    sidebarItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing', icon: 'Sparkles' },
      { id: 'dashboard', label: 'Admin Dashboard', href: '/dashboard/admin', icon: 'LayoutGrid' },
      { id: 'leads', label: 'Lead Intelligence', href: '/leads', icon: 'Brain' },
      { id: 'onboarding', label: 'Agent Onboarding', href: '/dashboard/admin/onboarding', icon: 'UserPlus' },
      { id: 'assignment-rules', label: 'Assignment Rules', href: '/dashboard/admin/assignment-rules', icon: 'GitBranch' },
      { id: 'forms', label: 'Forms Manager', href: '/dashboard/admin/forms', icon: 'FileText' },
      { id: 'knowledge', label: 'Knowledge Base', href: '/dashboard/admin/knowledge', icon: 'BookOpen' },
      { id: 'approvals', label: 'Approvals', href: '/approvals', icon: 'CheckSquare', badgeKey: 'pending_approvals' },
      { id: 'divider1', divider: true },
      {
        id: 'intelligence',
        label: 'Intelligence Suite',
        icon: 'Brain',
        children: [
          { id: 'intelligence-center', label: 'Intelligence Center', href: '/dashboard/brokerage/intelligence' },
          { id: 'deal-health', label: 'Deal Health', href: '/dashboard/brokerage/deal-health' },
          { id: 'team-heatmap', label: 'Team Heatmap', href: '/dashboard/team-heatmap' },
          { id: 'patterns', label: 'Behavioral Patterns', href: '/dashboard/patterns' },
          { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality' },
          { id: 'coordination', label: 'AI Coordination', href: '/dashboard/coordination' },
          { id: 'comm-intel', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence' },
          { id: 'farm-intel', label: 'Farm Intelligence', href: '/dashboard/admin/farm-intelligence' },
          { id: 'provider-intel', label: 'Provider Intelligence', href: '/dashboard/admin/provider-intelligence' },
        ],
      },
      { id: 'analytics', label: 'Analytics', href: '/analytics', icon: 'BarChart3' },
      { id: 'reports', label: 'Reports', href: '/dashboard/reports', icon: 'FileText' },
      { id: 'team-financials', label: 'Team Financials', href: '/dashboard/financials/team', icon: 'DollarSign' },
      { id: 'compliance', label: 'Compliance', href: '/dashboard/compliance', icon: 'Shield' },
      { id: 'brand-compliance', label: 'Brand & Compliance', href: '/dashboard/admin/brand', icon: 'Shield' },
      { id: 'feature-governance', label: 'Feature Governance', href: '/dashboard/admin/feature-governance', icon: 'Shield' },
      { id: 'workflows', label: 'Workflows', href: '/workflows', icon: 'Workflow' },
      { id: 'video-analytics', label: 'Video Analytics', href: '/dashboard/videos/analytics', icon: 'Video' },
      { id: 'sla-monitor', label: 'SLA Monitor', href: '/dashboard/admin/sla-monitor', icon: 'Clock' },
      { id: 'visitor-tracking', label: 'Visitor Tracking', href: '/dashboard/admin/visitor-tracking', icon: 'Eye' },
      { id: 'divider2', divider: true },
      { id: 'billing', label: 'Billing', href: '/admin/billing', icon: 'CreditCard' },
      { id: 'usage-metrics', label: 'Usage Metrics', href: '/admin/usage', icon: 'Activity' },
      { id: 'system-intel', label: 'System Intelligence', href: '/dashboard/system', icon: 'Radar' },
      { id: 'system', label: 'System Health', href: '/admin/system-health', icon: 'HeartPulse' },
      { id: 'logs', label: 'Audit Trail', href: '/admin/audit-trail', icon: 'Eye' },
      { id: 'ai-audit', label: 'AI Audit', href: '/admin/ai-audit', icon: 'Sparkles' },
      { id: 'error-handler', label: 'Error Handler', href: '/admin/error-handler', icon: 'AlertTriangle' },
      { id: 'settings', label: 'Settings', href: '/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'AlertTriangle', badgeKey: 'pending_approvals' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/admin', icon: 'LayoutGrid' },
      { id: 'onboarding', label: 'Onboarding', href: '/dashboard/admin/onboarding', icon: 'UserPlus' },
      { id: 'system', label: 'System', href: '/admin/system-health', icon: 'Activity' },
      { id: 'settings', label: 'Settings', href: '/settings', icon: 'Settings' },
    ],
    commandPaletteItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing' },
      { id: 'view-logs', label: 'View Audit Trail', href: '/admin/audit-trail' },
      { id: 'system-status', label: 'System Health', href: '/admin/system-health' },
      { id: 'deal-health', label: 'Deal Health', href: '/dashboard/brokerage/deal-health' },
      { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality' },
      { id: 'workflows', label: 'Workflows', href: '/workflows' },
      { id: 'onboarding', label: 'Agent Onboarding', href: '/dashboard/admin/onboarding' },
    ],
  },

  vendor: {
    sidebarItems: [
      { id: 'dashboard', label: 'Dashboard', href: '/vendor/dashboard', icon: 'LayoutGrid' },
      { id: 'jobs', label: 'Jobs', href: '/vendor/jobs', icon: 'Briefcase', badgeKey: 'vendor_pending_jobs' },
      { id: 'portfolio', label: 'Portfolio', href: '/vendor/portfolio', icon: 'Image' },
      { id: 'earnings', label: 'Earnings', href: '/vendor/earnings', icon: 'DollarSign' },
      { id: 'settings', label: 'Settings', href: '/vendor/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'notifications', label: 'Notifications', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'jobs', label: 'Jobs', href: '/vendor/jobs', icon: 'Briefcase' },
      { id: 'earnings', label: 'Earnings', href: '/vendor/earnings', icon: 'DollarSign' },
      { id: 'portfolio', label: 'Portfolio', href: '/vendor/portfolio', icon: 'Image' },
      { id: 'profile', label: 'Profile', href: '/vendor/settings', icon: 'User' },
    ],
    commandPaletteItems: [
      { id: 'accept-job', label: 'Accept Job', href: '/vendor/jobs' },
      { id: 'upload-photos', label: 'Upload Photos', href: '/vendor/portfolio/upload' },
    ],
  },

  contact: {
    // Contact users should be redirected to /portal/[contactId] - these are fallback links
    sidebarItems: [
      { id: 'overview', label: 'Overview', href: '/portal', icon: 'Home' },
      { id: 'transaction', label: 'My Transaction', href: '/portal', icon: 'FileText' },
      { id: 'documents', label: 'Documents', href: '/portal', icon: 'Folder' },
      { id: 'messages', label: 'Messages', href: '/portal', icon: 'Mail' },
    ],
    topNavItems: [
      { id: 'notifications', label: 'Notifications', icon: 'Bell' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'overview', label: 'Overview', href: '/portal', icon: 'Home' },
      { id: 'transaction', label: 'Transaction', href: '/portal', icon: 'FileText' },
      { id: 'documents', label: 'Documents', href: '/portal', icon: 'Folder' },
      { id: 'messages', label: 'Messages', href: '/portal', icon: 'Mail' },
    ],
    commandPaletteItems: [
      { id: 'contact-agent', label: 'Contact Agent', href: '/portal' },
      { id: 'view-docs', label: 'View Documents', href: '/portal' },
    ],
  },

  compliance_officer: {
    sidebarItems: [
      { id: 'dashboard', label: 'Compliance Command', href: '/dashboard/compliance', icon: 'LayoutGrid' },
      { id: 'violations', label: 'Violations', href: '/compliance/violations', icon: 'AlertTriangle', badgeKey: 'compliance_violations' },
      { id: 'audits', label: 'Audit Logs', href: '/compliance/audits', icon: 'Eye' },
      { id: 'policies', label: 'Policies', href: '/compliance/policies', icon: 'FileText' },
      { id: 'reports', label: 'Reports', href: '/compliance/reports', icon: 'BarChart3' },
      { id: 'full-compliance', label: 'Full Compliance Center', href: '/dashboard/compliance', icon: 'Shield' },
      { id: 'comm-intel', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence', icon: 'Brain' },
      { id: 'approvals', label: 'Approvals Queue', href: '/approvals', icon: 'CheckSquare' },
      { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality', icon: 'Sparkles' },
      { id: 'audit-trail', label: 'Platform Audit Trail', href: '/admin/audit-trail', icon: 'Database' },
      { id: 'settings', label: 'Settings', href: '/compliance/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'AlertTriangle', badgeKey: 'compliance_violations' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/compliance', icon: 'LayoutGrid' },
      { id: 'violations', label: 'Violations', href: '/compliance/violations', icon: 'AlertTriangle' },
      { id: 'audits', label: 'Audits', href: '/compliance/audits', icon: 'Eye' },
      { id: 'reports', label: 'Reports', href: '/compliance/reports', icon: 'BarChart3' },
      { id: 'more', label: 'More', href: '/dashboard/compliance', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'flag-violation', label: 'Flag Violation', href: '/compliance/violations/new' },
      { id: 'generate-report', label: 'Generate Report', href: '/compliance/reports/new' },
      { id: 'comm-intel', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence' },
    ],
  },

  tc: {
    sidebarItems: [
      { id: 'dashboard', label: 'Coordinator Command', href: '/dashboard/coordinator', icon: 'LayoutGrid' },
      { id: 'deals', label: 'Active Deals', href: '/transaction/deals', icon: 'Handshake', badgeKey: 'active_deals' },
      { id: 'checklists', label: 'Checklists', href: '/transaction/checklists', icon: 'CheckSquare' },
      { id: 'documents', label: 'Documents', href: '/transaction/documents', icon: 'Folder' },
      { id: 'vendors', label: 'Vendor Coordination', href: '/transaction/vendors', icon: 'Users' },
      { id: 'settings', label: 'Settings', href: '/transaction/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/coordinator', icon: 'LayoutGrid' },
      { id: 'deals', label: 'Deals', href: '/transaction/deals', icon: 'Handshake' },
      { id: 'checklists', label: 'Checklists', href: '/transaction/checklists', icon: 'CheckSquare' },
      { id: 'vendors', label: 'Vendors', href: '/transaction/vendors', icon: 'Users' },
      { id: 'more', label: 'More', href: '/dashboard/coordinator', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'new-deal', label: 'New Deal', href: '/transaction/deals/new' },
      { id: 'contact-vendor', label: 'Contact Vendor', href: '/transaction/vendors/contact' },
    ],
  },

  lender: {
    sidebarItems: [
      { id: 'dashboard', label: 'Lender Dashboard', href: '/lender/dashboard', icon: 'LayoutGrid' },
      { id: 'pipeline', label: 'Loan Pipeline', href: '/lender/pipeline', icon: 'TrendingUp', badgeKey: 'lender_pipeline_count' },
      { id: 'approvals', label: 'Approvals', href: '/lender/approvals', icon: 'CheckCircle' },
      { id: 'underwriting', label: 'Underwriting', href: '/lender/underwriting', icon: 'FileCheck' },
      { id: 'documents', label: 'Documents', href: '/lender/documents', icon: 'Folder' },
      { id: 'settings', label: 'Settings', href: '/lender/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/lender/dashboard', icon: 'LayoutGrid' },
      { id: 'pipeline', label: 'Pipeline', href: '/lender/pipeline', icon: 'TrendingUp' },
      { id: 'approvals', label: 'Approvals', href: '/lender/approvals', icon: 'CheckCircle' },
      { id: 'underwriting', label: 'UW', href: '/lender/underwriting', icon: 'FileCheck' },
      { id: 'more', label: 'More', href: '/lender/menu', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'approve-loan', label: 'Approve Loan', href: '/lender/approvals' },
      { id: 'send-to-uw', label: 'Send to UW', href: '/lender/underwriting' },
    ],
  },

  title_agent: {
    sidebarItems: [
      { id: 'dashboard', label: 'Title Dashboard', href: '/title/dashboard', icon: 'LayoutGrid' },
      { id: 'orders', label: 'Title Orders', href: '/title/orders', icon: 'Package', badgeKey: 'title_open_orders' },
      { id: 'status', label: 'Order Status', href: '/title/status', icon: 'Clock' },
      { id: 'documents', label: 'Title Documents', href: '/title/documents', icon: 'FileText' },
      { id: 'closing', label: 'Closing Schedule', href: '/title/closing', icon: 'Calendar' },
      { id: 'settings', label: 'Settings', href: '/title/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/title/dashboard', icon: 'LayoutGrid' },
      { id: 'orders', label: 'Orders', href: '/title/orders', icon: 'Package' },
      { id: 'status', label: 'Status', href: '/title/status', icon: 'Clock' },
      { id: 'closing', label: 'Closing', href: '/title/closing', icon: 'Calendar' },
      { id: 'more', label: 'More', href: '/title/menu', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'new-order', label: 'New Title Order', href: '/title/orders/new' },
      { id: 'schedule-closing', label: 'Schedule Closing', href: '/title/closing/new' },
    ],
  },

  // superadmin — same full access as admin + platform management
  superadmin: {
    sidebarItems: [
      { id: 'platform', label: 'Platform Admin', href: '/admin/platform', icon: 'ShieldAlert' },
      { id: 'brokerages', label: 'Brokerages', href: '/admin/brokerages', icon: 'Building2' },
      { id: 'users', label: 'All Users', href: '/admin/users', icon: 'Users' },
      { id: 'divider1', divider: true },
      { id: 'observability', label: 'Observability', href: '/dashboard/superadmin/observability', icon: 'Radar' },
      { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality', icon: 'Sparkles' },
      { id: 'patterns', label: 'Behavioral Patterns', href: '/dashboard/patterns', icon: 'Activity' },
      { id: 'coordination', label: 'AI Coordination', href: '/dashboard/coordination', icon: 'Network' },
      { id: 'divider2', divider: true },
      { id: 'billing', label: 'Billing Administration', href: '/admin/billing', icon: 'CreditCard' },
      { id: 'usage-metrics', label: 'Usage Metrics', href: '/admin/usage', icon: 'Activity' },
      { id: 'assignment-rules', label: 'Assignment Rules', href: '/dashboard/admin/assignment-rules', icon: 'GitBranch' },
      { id: 'feature-governance', label: 'Feature Governance', href: '/dashboard/admin/feature-governance', icon: 'Shield' },
      { id: 'workflows', label: 'Workflows', href: '/workflows', icon: 'Workflow' },
      { id: 'divider3', divider: true },
      { id: 'system-health', label: 'System Health', href: '/admin/system-health', icon: 'Activity' },
      { id: 'ai-audit', label: 'AI Audit', href: '/admin/ai-audit', icon: 'Eye' },
      { id: 'integrations', label: 'Integrations', href: '/admin/integrations', icon: 'Plug' },
      { id: 'settings', label: 'Settings', href: '/admin/settings', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'Bell' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'platform', label: 'Platform', href: '/admin/platform', icon: 'ShieldAlert' },
      { id: 'brokerages', label: 'Brokerages', href: '/admin/brokerages', icon: 'Building2' },
      { id: 'system-health', label: 'System', href: '/admin/system-health', icon: 'Activity' },
      { id: 'settings', label: 'Settings', href: '/admin/settings', icon: 'Settings' },
      { id: 'more', label: 'More', href: '/admin/menu', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'observability', label: 'Observability Dashboard', href: '/dashboard/superadmin/observability' },
      { id: 'manage-brokerages', label: 'Manage Brokerages', href: '/admin/brokerages' },
      { id: 'system-health', label: 'View System Health', href: '/admin/system-health' },
      { id: 'ai-quality', label: 'AI Quality', href: '/dashboard/ai-quality' },
      { id: 'patterns', label: 'Behavioral Patterns', href: '/dashboard/patterns' },
    ],
  },

  // team_lead — agent capabilities + team management overlay
  team_lead: {
    sidebarItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing', icon: 'Sparkles' },
      { id: 'dashboard', label: 'Team Dashboard', href: '/dashboard/agent', icon: 'LayoutGrid' },
      { id: 'crm', label: 'CRM', href: '/crm', icon: 'Users' },
      { id: 'leads', label: 'Lead Intelligence', href: '/leads', icon: 'Brain' },
      { id: 'transactions', label: 'Transactions', href: '/dashboard/transactions', icon: 'FileText' },
      { id: 'agent-roster', label: 'My Team', href: '/dashboard/team', icon: 'UserCheck' },
      { id: 'team-heatmap', label: 'Team Heatmap', href: '/dashboard/team-heatmap', icon: 'Map' },
      { id: 'leaderboard', label: 'Leaderboard', href: '/dashboard/leaderboard', icon: 'Award' },
      { id: 'approvals', label: 'Approvals', href: '/approvals', icon: 'CheckSquare' },
      { id: 'market-insights', label: 'Market Insights', href: '/dashboard/market-insights', icon: 'TrendingUp' },
      { id: 'divider1', divider: true },
      {
        id: 'video-tools',
        label: 'Video Tools',
        icon: 'Video',
        children: [
          { id: 'video-studio', label: 'Video Studio', href: '/dashboard/videos/create' },
          { id: 'video-library', label: 'Video Library', href: '/dashboard/videos/library' },
          { id: 'video-analytics', label: 'Video Analytics', href: '/dashboard/videos/analytics' },
        ],
      },
      {
        id: 'content',
        label: 'Content Studio',
        icon: 'Palette',
        children: [
          { id: 'marketing-studio', label: 'Marketing Studio', href: '/dashboard/marketing/studio' },
          { id: 'social-dashboard', label: 'Social Dashboard', href: '/dashboard/social' },
          { id: 'newsletters', label: 'Newsletters', href: '/newsletters/templates' },
          { id: 'repurpose', label: 'Repurpose Content', href: '/dashboard/campaigns/repurpose' },
        ],
      },
      {
        id: 'communications',
        label: 'Communications',
        icon: 'MessageCircle',
        children: [
          { id: 'outreach', label: 'AI Outreach', href: '/dashboard/communications/outreach' },
          { id: 'sequences', label: 'Drip Sequences', href: '/dashboard/communications/sequences' },
          { id: 'intelligence', label: 'Comm Intelligence', href: '/dashboard/communications/intelligence' },
        ],
      },
      {
        id: 'financials',
        label: 'Financials',
        icon: 'DollarSign',
        children: [
          { id: 'my-financials', label: 'My Financials', href: '/dashboard/financials/agent' },
          { id: 'team-financials', label: 'Team Financials', href: '/dashboard/financials/team' },
        ],
      },
      { id: 'compliance', label: 'Compliance', href: '/dashboard/compliance', icon: 'Shield' },
      { id: 'reports', label: 'Reports', href: '/dashboard/reports', icon: 'BarChart3' },
      {
        id: 'sphere',
        label: 'Sphere of Influence',
        icon: 'Users',
        href: '/past-clients',
        children: [
          { id: 'sphere-all', label: 'All Sphere Contacts', href: '/past-clients' },
          { id: 'sphere-referrals', label: 'Referrals', href: '/past-clients?tab=referrals' },
          { id: 'sphere-reviews', label: 'Reviews & Reputation', href: '/past-clients?tab=reviews' },
          { id: 'sphere-gifting', label: 'Gifting & Milestones', href: '/past-clients?tab=gifting' },
        ],
      },
      { id: 'settings', label: 'Settings', href: '/dashboard/settings/general', icon: 'Settings' },
    ],
    topNavItems: [
      { id: 'alerts', label: 'Alerts', icon: 'Bell', badgeKey: 'unread_notifications' },
      { id: 'profile', label: 'Profile', icon: 'User' },
    ],
    mobileBottomNav: [
      { id: 'dashboard', label: 'Dashboard', href: '/dashboard/agent', icon: 'LayoutGrid' },
      { id: 'crm', label: 'CRM', href: '/crm', icon: 'Users' },
      { id: 'transactions', label: 'Deals', href: '/dashboard/transactions', icon: 'FileText' },
      { id: 'team', label: 'Team', href: '/dashboard/team', icon: 'UserCheck' },
      { id: 'more', label: 'More', href: '/dashboard', icon: 'Menu' },
    ],
    commandPaletteItems: [
      { id: 'briefing', label: 'AI Briefing', href: '/dashboard/briefing' },
      { id: 'view-team', label: 'View Team', href: '/dashboard/team' },
      { id: 'team-heatmap', label: 'Team Heatmap', href: '/dashboard/team-heatmap' },
      { id: 'new-contact', label: 'New Contact', href: '/contacts/new' },
      { id: 'video-studio', label: 'Create AI Video', href: '/dashboard/videos/create' },
    ],
  },
}

export function getNavigationForRole(role: string | string[]): NavigationConfig {
  const roles = Array.isArray(role) ? role : [role]
  const primaryRole = roles[0]
  return NAVIGATION_BY_ROLE[primaryRole as UserRole] || NAVIGATION_BY_ROLE.contact
}

export function filterNavItemsByPermissions(items: NavItem[], userPermissions: string[]): NavItem[] {
  return items.filter((item) => {
    if (!item.requiredPermissions) return true
    return item.requiredPermissions.some((perm) => userPermissions.includes(perm))
  })
}
