// lib/offers/offer-strategy-advisor.ts
// ─────────────────────────────────────────────────────────────────────────────
// THE BUYER OFFER-STRATEGY BRAIN — the shared, context-free core that turns a target
// listing + the buyer's situation into a CONCRETE, grounded offer plan: a recommended
// offer price, a price range, win probability, escalation, contingencies, earnest money.
//
// This used to live ONLY inside the auth-gated UI action (app/actions/ai-offer-creation.ts),
// so the AUTONOMOUS "offer-strategy moment" (the buyer reaching the offer_strategy stage)
// could never reach it — the AI managers handed the agent a generic "go pull comps yourself"
// note while the real engine sat unused. Extracting it here lets BOTH the UI action AND the
// offer-strategy producer share ONE brain (no drift, no duplicate prompt), so when a buyer is
// ready to write, the team hands the agent a real, comps/market-grounded number to act on.
//
// Numbers are GENERATED by the gateway from the real listing + buyer facts (never fabricated
// by us); the caller supplies real list price / DOM / pre-approval. No I/O here beyond the
// gateway call — the callers resolve the inputs.

import { generateObjectRouted } from "@/lib/ai/models"
import { BuyerOfferStrategySchema, type BuyerOfferStrategy, type BuyerOfferStrategyInput } from "./offer-strategy-types"

// Re-export the pure surface so existing importers of the advisor keep working.
export { BuyerOfferStrategySchema, summarizeOfferStrategy } from "./offer-strategy-types"
export type { BuyerOfferStrategy, BuyerOfferStrategyInput } from "./offer-strategy-types"

/**
 * generateBuyerOfferStrategy — the shared brain. Returns the validated strategy, or null on
 * any gateway/validation failure (callers degrade gracefully — the UI surfaces an error, the
 * autonomous producer falls back to the generic brief). The gateway grounds every number in
 * the supplied real listing + buyer facts.
 */
export async function generateBuyerOfferStrategy(
  params: BuyerOfferStrategyInput,
): Promise<BuyerOfferStrategy | null> {
  try {
    const { object } = await generateObjectRouted({
      feature: "offer_analysis",
      schema: BuyerOfferStrategySchema,
      prompt: `You are a buyer's agent strategist. Help craft a winning offer strategy.

Listing Details:
- List Price: $${params.listPrice.toLocaleString()}
- Days on Market: ${params.daysOnMarket}
- Competing Offers: ${params.competingOffers ?? "Unknown"}
- Market: ${params.marketConditions}

Buyer Situation:
- Motivation: ${params.buyerMotivation}
- Max Budget: $${params.buyerMaxBudget.toLocaleString()}

Consider:
1. Market conditions and competition
2. Buyer's budget and motivation
3. What will make this offer stand out
4. Risk vs reward tradeoffs

Provide a comprehensive offer strategy. Never recommend an offer above the buyer's max budget.`,
    })
    return object as BuyerOfferStrategy
  } catch (error) {
    console.error("[offer-strategy-advisor] strategy generation failed:", error)
    return null
  }
}
