/**
 * /dashboard/cma/[cmaId] — ONE cma_reports row, by its own id.
 *
 * Until this page existed no route could render a CMA by id:
 * /dashboard/listings/[id]/cma is listing-scoped (latest row by listing_id,
 * app/actions/seller-cma.ts loadCMAPageData) and a CMA with listing_id = null —
 * every listing-appointment prep CMA — was unreachable. The copilot panel's
 * "Open CMA" link was tombstoned for exactly that reason; this route is the
 * survivor it was waiting for. Sibling /dashboard/cma/page.tsx is a redirect
 * stub and the '/dashboard/cma' ROUTE_ALIASES entry stays as it is.
 *
 * Reader: loadCMAReportById (seller-cma.ts) — requireAuth, brokerage pin from
 * the session, children gated by the parent's id. Body: CMAReportTab, the same
 * component the listing-scoped page renders, which brings the deterministic
 * appraisal-defense packet (window.print) with it — §5: nothing model-authored
 * is added on this path. CMAClient is NOT reused: three of its four tabs are
 * listing-scoped and would have nothing to show here.
 *
 * Status vocabulary — two live disagreements this page does NOT fix (§6 job):
 *   · app/actions/seller-cma.ts loadCMAPageData tests
 *     `status === "auto_generated"`, a value cma_reports_status_check does not
 *     admit (archived | draft | presented | ready), so `autoGenerated` there is
 *     permanently false.
 *   · app/components/dashboard/listings/cma-history-sheet.tsx STATUS_CONFIG maps
 *     draft / shared_with_seller / expired / active — only `draft` overlaps the
 *     CHECK, and its "Mark Shared with Seller" writes `shared_with_seller`.
 * This header renders the raw status string and does not join either spelling.
 */

import Link from "next/link"
import { notFound, redirect } from "next/navigation"
import { Badge } from "@/components/ui/badge"
import { CMA_DISCLAIMER } from "@/lib/cma/disclaimer"
import { loadCMAReportById } from "@/app/actions/seller-cma"
import { CMAReportTab } from "@/app/dashboard/listings/[id]/cma/tabs/cma-report-tab"

interface Props {
  params: Promise<{ cmaId: string }>
}

export default async function CMAReportByIdPage({ params }: Props) {
  const { cmaId } = await params
  const res = await loadCMAReportById(cmaId)

  if (!res.success) {
    if (res.error === "unauthenticated") redirect("/login")
    // invalid_id and cma_not_found (missing OR another tenant's) are the same
    // 404 — the page must not distinguish "not yours" from "not there".
    notFound()
  }

  const { cma, listingId } = res.data
  if (!cma) notFound()

  // CMAReportTab takes a listing prop. A prep CMA has no listing, so the prop is
  // synthesised from the report's own columns — the address is the folded
  // "street, city, state zip" string ai-cma.ts writes; there is no city/state
  // column to split it back out of.
  const listing = {
    id: listingId ?? "",
    list_price: null,
    address: cma.property_address,
    property_type: cma.property_type,
    bedrooms: cma.bedrooms,
    bathrooms: cma.bathrooms,
    square_footage: cma.square_feet,
  }

  const created = cma.created_at
    ? new Date(cma.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })
    : null

  return (
    <div className="flex flex-col min-h-screen bg-background">
      {/* Page header */}
      <div className="border-b border-border bg-card px-6 py-4">
        <p className="text-xs text-muted-foreground font-medium uppercase tracking-wide">
          CMA Report
        </p>
        <div className="flex flex-wrap items-center gap-3 mt-0.5">
          <h1 className="text-xl font-semibold text-foreground">{cma.property_address}</h1>
          {cma.status && (
            <Badge variant="outline" className="text-muted-foreground capitalize">
              {cma.status}
            </Badge>
          )}
        </div>
        <p className="text-xs text-muted-foreground mt-1">
          {created ? `Prepared ${created}` : "Preparation date not recorded"}
          {cma.comparable_count != null
            ? ` · ${cma.comparable_count} comparable${cma.comparable_count === 1 ? "" : "s"}`
            : ""}
          {listingId ? (
            <>
              {" · "}
              <Link href={`/dashboard/listings/${listingId}/cma`} className="underline hover:text-foreground">
                Open the listing&apos;s CMA workspace
              </Link>
            </>
          ) : (
            " · Not attached to a listing"
          )}
        </p>
      </div>

      <div className="flex-1 overflow-auto">
        <CMAReportTab listing={listing} data={res.data} />
      </div>

      {/* MANDATORY disclaimer — sticky footer, non-dismissable
          (same block as app/dashboard/listings/[id]/cma/cma-client.tsx). */}
      <div className="sticky bottom-0 z-40 bg-amber-50 border-t border-amber-300 px-6 py-2.5">
        <p className="text-xs text-amber-800 font-medium leading-snug max-w-4xl">
          <span className="font-bold">IMPORTANT: </span>
          {CMA_DISCLAIMER}
        </p>
      </div>
    </div>
  )
}
