/**
 * lib/kernel/manager-registry.ts
 *
 * THE canonical map of "which Claude manager owns this activity". The One Command
 * Center aggregates every governed action across many surfaces; this registry makes
 * the multi-manager model explicit and accountable — EVERY activity on the egress is
 * owned by a named manager, with ZERO orphans. Adding a new Command Center queue
 * without assigning it here fails the manager-ownership regression test.
 *
 * Pure module (no imports, no server-only) so both the kernel loader (server) and the
 * Command Center UI (client) share ONE source of truth for manager identity + labels —
 * no drift between a server map and a hand-kept client KIND_LABEL.
 *
 * All 11 managers mirror managed_agents.agent_kind (lib/agents/spawn-helper.ts AgentKind):
 * the 7 core managers + Ads Manager (m193) + AI ISA (m197, lead qualification/nurture) +
 * Recruiting Manager (m215, agent recruiting / talent pipeline — brokerage growth) +
 * Data Steward (m203, data integrity / identity / field stewardship across the lead spine).
 *
 * ── PRESERVED MANAGER BOUNDARIES (the product's governance contract) ──────────
 * Sides of the business map to managers precisely — no blurring:
 *   · AI ISA            — leads (unconsented, ISA + brokerage owned) and ISA
 *                         engagement ACTIVITIES: every outreach/call/message the
 *                         ISA logs while qualifying, until handoff converts the
 *                         lead to a contact.
 *   · Listing Concierge — the SELLER side: listings and in-house SHOWINGS of our
 *                         listings (external buyer agents coming through our door,
 *                         ShowingTime sync, access codes, seller feedback loops).
 *   · Shopping Agent    — the BUYER side: TOURS (taking our buyer out, routes,
 *                         stops) and OFFERS the buyer writes, plus preferences,
 *                         matches and saved properties.
 *   · Deal Coordinator  — post-acceptance: transactions, transaction tasks and
 *                         the deal calendar through closing.
 *   · Sphere Manager    — LIFETIME relationships: closed & past clients, repeat
 *                         and referral cultivation after the deal is done.
 * No additional manager is needed for these splits — each boundary lands cleanly
 * on an existing manager's charter; introducing one would dilute accountability.
 */

export type ManagerKey =
  | "deal_coordinator"
  | "shopping_agent"
  | "listing_concierge"
  | "sphere_of_influence"
  | "campaign_orchestrator"
  | "marketing_agent"
  | "asset_manager"
  | "ads_manager"
  | "ai_isa"
  | "data_steward"
  | "recruiting_manager"

export interface ManagerInfo {
  key:    ManagerKey
  label:  string
  /** One-line domain the manager is accountable for (UI tooltip / grouping). */
  domain: string
}

export const MANAGERS: Record<ManagerKey, ManagerInfo> = {
  deal_coordinator:      { key: "deal_coordinator",      label: "Deal Coordinator",      domain: "Transactions & closings" },
  shopping_agent:        { key: "shopping_agent",        label: "Shopping Agent",        domain: "Buyer journey" },
  listing_concierge:     { key: "listing_concierge",     label: "Listing Concierge",     domain: "Sellers & listings" },
  sphere_of_influence:   { key: "sphere_of_influence",   label: "Sphere Manager",        domain: "Lifetime closed & past clients — repeat & referral" },
  campaign_orchestrator: { key: "campaign_orchestrator", label: "Campaign Orchestrator", domain: "Multi-touch campaigns & content" },
  marketing_agent:       { key: "marketing_agent",       label: "Marketing Manager",     domain: "Brand & promotion" },
  asset_manager:         { key: "asset_manager",         label: "Asset Manager",         domain: "Media & brand library" },
  ads_manager:           { key: "ads_manager",           label: "Ads Manager",           domain: "Paid advertising" },
  ai_isa:                { key: "ai_isa",                label: "AI ISA",                domain: "Lead qualification, nurture & re-engagement" },
  data_steward:          { key: "data_steward",          label: "Data Steward",          domain: "Data integrity, identity & field stewardship" },
  recruiting_manager:    { key: "recruiting_manager",    label: "Recruiting Manager",    domain: "Agent recruiting & talent pipeline (brokerage growth)" },
}

/**
 * Every Command Center queue → its owning manager. `client_message` is resolved
 * per-row from the message's agent_kind (any of the deal-critical managers can
 * propose a client message), so it is intentionally absent here and handled by
 * resolveActionManager.
 */
export const QUEUE_MANAGER: Record<string, ManagerKey> = {
  // Agent-action queues
  marketing:              "marketing_agent",
  asset:                  "asset_manager",
  ads:                    "ads_manager",
  // Content-approval queues
  social:                 "marketing_agent",
  newsletter:             "campaign_orchestrator",
  direct_mail:            "marketing_agent",
  ad_creative:            "ads_manager",
  predictive_listing:     "sphere_of_influence",
  transaction_task:       "deal_coordinator",
  transaction_smart_task: "deal_coordinator",
  agent_followup:         "sphere_of_influence",
  blog:                   "campaign_orchestrator",
  podcast:                "campaign_orchestrator",
}

/**
 * MAINTENANCE / BURN-DOMAIN OWNERSHIP — every audit/cleanup workstream on the egress
 * is owned by a named Claude manager, so as code is cleaned and fixed there is always
 * a manager accountable for keeping that domain on the ONE egress. The ownership
 * simulator asserts every domain maps to a real manager (zero orphan burn types),
 * and each domain lists its runnable proof so the owner is tied to a regression,
 * not just a label.
 */
export const MAINTENANCE_DOMAINS: Record<string, { manager: ManagerKey; proof: string; what: string }> = {
  // ── Data Steward — data integrity across the raw → leads → contacts spine ──
  schema_drift_guard:         { manager: "data_steward", proof: "test:schema-drift",       what: "No code references a column the live table lacks; baseline burn-down ratchet" },
  conversation_memory:        { manager: "data_steward", proof: "test:conversation-memory", what: "THE CONTEXT SPINE — one durable, shared running summary per contact (last touch, stated preferences, open commitment, mood) persisted to contacts.metadata->'context_spine' (REUSED jsonb, no new table) so every manager (AI ISA, agent, concierges, Director) acts on the SAME memory and nobody forgets what was discussed. composeContextSummary reads ONLY real interaction rows (honest empty when none, never invents a fact); it SUMMARIZES, it is NOT a second state machine (buyer_stage/contact_type stay canonical). Injectable AI summarizer seam; team-query's bullpen now surfaces the persisted spine instead of only recomputing live" },
  regulatory_change_watcher:  { manager: "data_steward", proof: "test:regulatory-watcher", what: "REGULATORY-CHANGE WATCHER — keeps the compliance GATES current automatically: scans the gated external-search rail (Tavily/Exa) for recent real-estate reg changes (TCPA/CAN-SPAM/FTC/Fair-Housing-HUD/NAR/state RE commissions), PURE matchAffectedSurfaces maps each REAL sourced change to the OS surfaces it touches (the 5-gate cascade, FAIR_HOUSING_PATTERNS, state_protected_classes, the BBA/authority gate), classifyChangeSeverity reads a binding/advisory tier + an effective date parsed LITERALLY (never invented), records an idempotent observation (m224 reg_change_observations, per change-signature x ISO week) and ESCALATES a GATED brief to the compliance/broker owner (manager_signals bus + notifications). NEVER fabricates a regulation or an effective date; search unavailable -> no changes, nothing escalated; weekly cron" },
  lossless_promotion:         { manager: "data_steward", proof: "test:data-steward",       what: "raw → leads → contacts moves identity/address/enrichment without loss" },
  import_field_mapping:       { manager: "data_steward", proof: "test:data-steward",       what: "CSV/CRM imports: known fields map, unmapped columns preserved in notes" },
  import_value_normalization: { manager: "data_steward", proof: "test:data-steward",       what: "Imported values reconciled to canonical vocabulary (synonyms + gated AI match)" },
  dedup_merge:                { manager: "data_steward", proof: "test:data-steward",       what: "Dedup merges fill empties and preserve conflicts in notes — never drop" },
  enrichment_conservation:    { manager: "data_steward", proof: "test:data-steward",       what: "PeopleData enrichment lands in first-class columns AND jsonb" },
  consent_suppression:        { manager: "data_steward", proof: "test:lead-pipeline",      what: "TCPA consent/opt-out provenance carries faithfully — no fabricated consent" },
  manager_boundaries:         { manager: "data_steward", proof: "test:manager-ownership",  what: "Buyer/seller/lead/lifetime boundaries preserved: tours+offers=buyer (Shopping), in-house showings=listing side, ISA activities=AI ISA, sphere=lifetime past clients" },
  dual_portal:                { manager: "asset_manager",  proof: "test:dual-portal", what: "DUAL-JOURNEY PORTAL — a contact who is BOTH buyer AND seller (contact_type='both', 'must sell to buy') sees BOTH journeys in a tabbed Buy|Sell portal instead of collapsing to one; resolveDualPortalView is additive on top of determinePortalView (single buyer/seller/lifetime resolution unchanged for everyone), surfaces the linker's stamped sale→buy dependency banner when gated (dualBannerPredicate); reuses journey_states + the existing buyer/seller home components + transparency_updates, no new tables" },
  dual_intent_linker:         { manager: "data_steward", proof: "test:dual-intent",        what: "ONE contact who is BOTH seller AND buyer (the 'must sell to buy' case): closes a real spine gap — motivationToContactType maps 'both'→'buyer' so the lead→contact spine NEVER writes contact_type='both' even though event-reactor spawns BOTH managers + both agents accept it. linkDualJourneys sets contact_type='both' and writes TWO journey_states rows for the one contact (composite user_id ${contact}:buyer / :seller to satisfy UNIQUE(user_id), per JOURNEY_PROGRESS_CONTRACT §70) so Shopping Agent (buy) AND Listing Concierge (sell) both work the person; pure detectDualIntent + sellMustPrecedeBuy surface the dependency (purchase contingent on the sale closing → gated, reason sale_funds_purchase) via the existing transparency_updates; idempotent, honest no-op when only one side has signal — no new tables" },
  // ── AI ISA — the qualify → assign → convert chain ──
  qualification_chain:        { manager: "ai_isa",       proof: "test:isa-qualification",  what: "Conversation scoring persists; readiness gates handoff" },
  assignment_routing:         { manager: "ai_isa",       proof: "test:isa-qualification",  what: "Tier-aware routing (solo/team/brokerage/multi-location); preview = engine" },
  lead_conversion:            { manager: "ai_isa",       proof: "test:isa-qualification",  what: "Qualification converts to a lossless contact via the canonical converter" },
  buyer_intent_conversion:    { manager: "shopping_agent", proof: "test:buyer-intent-conversion", what: "BUYER-side conversion-on-intent ROUTER (no one-size-fits-all): a buyer LEAD converts to a CONTACT on POSITIVE INTENT via the CANONICAL handoff (acceptAIISAHandoff → consented → assigned → lossless buyer contact, leads.ai_isa_owner=false so the ISA goes DORMANT, agent notified) and EACH intent routes to its own milestone — positive_reply: convert only; criteria_request: capture property_preferences (saved search) + advance buyer_stage→BUYER_SEARCH_CONFIGURED; preapproval_request: start pre-approval (buyer_financial_profiles, verified=false — requested not completed); showing_request: schedule a showing (showing_requests) respecting the NAR-2024 BBA gate + buyer_stage→BUYER_TOURING. Shopping Agent owns it; idempotent per (lead,reason), no double-convert, honest-guarded (under representation → refuse; missing criteria/property → skip routing but still convert)" },
  inbound_intent_classifier:  { manager: "ai_isa", proof: "test:inbound-intent", what: "INBOUND INTENT CLASSIFIER — the autonomy capstone: when a lead REPLIES (email/SMS/web) the AI ISA reads the message, classifies the intent, and self-routes to the right conversion+milestone (no human picks the reason). Maps an inbound message → {side:'buyer'|'seller', reason} via an injectable classifier (AI generateText+strict enum through the gateway by default, PURE keywordIntentFallback as the deterministic floor) and calls the matching converter: seller→convertSellerLeadOnIntent (positive_reply|cma_request|appointment_request), buyer→convertBuyerLeadOnIntent (positive_reply|criteria_request|preapproval_request|showing_request). HONEST CONSERVATISM: clear POSITIVE → convert+route; clear NEGATIVE → HALT (reuse detectNegativeIntent/haltEngagementForNegativeReply — never convert); AMBIGUOUS → NO conversion, keep nurturing. Wired into handle-inbound-email behind the negative-intent halt; idempotent, gated, additive" },
  seller_appt_conversion:     { manager: "ai_isa",       proof: "test:seller-appt-conversion", what: "CONVERSION-ON-INTENT, decoupled from the appointment: a seller LEAD converts to a CONTACT on POSITIVE ENGAGEMENT / INTENT (positive ISA conversation, or a CMA/info request) via the CANONICAL handoff (acceptAIISAHandoff → consented → assigned → lossless contact, ai_isa_owner=false so the ISA goes DORMANT, agent notified of a new contact to reach out to, CMA proposed when asked) — NOT on booking an appointment; a converted-no-appointment contact stays alive via the existing stale/ghost re-engage loop (detectStaleContacts catches last_contacted_at NULL). The listing APPOINTMENT is a SEPARATE, LATER milestone (bookSellerListingAppointment) that fires listing.appointment_set → the flagship listing-appt-prep chain and converts ONLY as an idempotent safety if no contact exists yet (no double convert/welcome/chain); honest-guarded (lead under representation → refuse)" },
  lead_nurture:               { manager: "ai_isa",       proof: "test:lead-nurture",       what: "Hot-seller-LEAD nurture (the conversion push lead→contact): VERIFICATION-GATED, channel-appropriate outreach — a Director 'thinking of selling?' reel EMAILED when leads.email_verified (gated proposal via proposeClientMessage audience='lead'/channel='email', CAN-SPAM honored: email_verified && !email_opt_out), a POSTCARD when leads.mailing_address_verified (direct_mail_campaigns approval_status='pending'/status='planning', carrying its QR → conversion landing); each channel independent + idempotent per (lead, channel), nothing auto-sends, NO portal card (it's a lead, no portal until conversion)" },
  isa_reengagement_loop:      { manager: "ai_isa",       proof: "test:isa-reengagement",   what: "THE RE-ENGAGEMENT LOOP — 'dormant until they ghost, then follow up on cadence': the decisions behind the ghost-detection (lead-side, lifecycle_state='isa_qualifying') + stale-contact-monitor (contact-side, post-conversion) crons now live in ONE pure policy (lib/ai-isa/reengagement-policy.ts) shared by both runners so production + proof can't drift. CADENCE shouldSendGhostOutreach: Phase 1 (≤14d from first outreach) Mon/Wed/Fri only, Phase 2 (>14d) first-send then every 30d — weekday-independent. STOP ghostReengagementStopReason (representation / inactive / contact reengage-disallowed / opted-out / reply-received, in precedence) so the ISA goes dormant the instant a human takes over or the lead opts out. STALE staleContactEligibility encodes every exclusion (dnc / paused / reengage-disallowed / do-not-contact / deleted / active-transaction / not-yet-stale) — the single authority the contact detector's post-fetch loop honors; never-contacted = maximally stale (999d). Contact-side dispatch stays consent + evaluateOutbound gated; nothing fabricated" },
  self_tuning_cadence:        { manager: "campaign_orchestrator", proof: "test:cadence-learning", what: "SELF-TUNING CADENCE — the over-touch frequency cap LEARNS each brokerage's rhythm from real engagement instead of being a static config (the 'agentic, it learns' differentiator). getEngagementSignals reads the shared touch ledger (marketing_campaign_touchpoints opened/clicked/converted vs sent over 30d); pure computeLearnedCadence adjusts the cap WITHIN HARD BOUNDS — engaged audience (≥50% engagement, sample≥20) loosens by up to +2 (capped at 2× base), cooling audience (≤10%) tightens by 1 (floored at 1), thin sample or normal band leaves base untouched, windowDays never changes. evaluateDeconflict opt-in via learn:true (best-effort, fails open to base). The legal gates — consent/opt-out/DNC/quiet-hours/suppression — are SEPARATE and ALWAYS apply; learning can never loosen a legal floor, only the UX/deliverability guardrail" },
  seller_time_to_list:        { manager: "ai_isa",       proof: "test:seller-timeline",   what: "SELLER TIME-TO-LIST — the missing TIME dimension on top of scoreSellerIntent: the radar scores HOW motivated a homeowner is, this predicts WHEN they'll list so the AI ISA works the right seller at the RIGHT MOMENT, not just the most motivated. Pure computeSellerListingTimeline uses ONLY present signals (no fabrication): pre-foreclosure/notice-of-sale = a FORCED 14–90 day auction clock; tax lien forced 60–120; FSBO ACTIVE now (0–45); fresh expired an imminent re-list (7–60, widening as it ages); divorce 60–180; probate court-paced 120–365; long-tenure+high-equity / absentee = EVENTUAL (90–365); unknown when nothing time-bound. Forced clocks outrank discretionary windows outrank eventual; timelineRank sorts imminent sellers first. ANNOTATION ONLY — a scraped record never skips the canonical gate (raw_scraped_leads → processRawRecord decides promotion); leads stay brokerage+AI-ISA owned until conversion" },
  lead_overtouch_governance:  { manager: "ai_isa",       proof: "test:lead-deconflict",   what: "LEADS ARE GOVERNED TOO — the de-confliction over-touch frequency cap now protects an unconverted LEAD the same way it protects a promoted contact (the customer relationship is protected from the first touch, not just post-conversion). Lead outbound logs to isa_outreach_log by lead_id; evaluateDeconflict counts that ledger when a leadId is supplied (contactId takes precedence when both exist), and dispatch.ts passes leadId through the email/sms/phone/mail deconflictGate (mail gate extended to leads — lead postcards are a real nurture channel). leadLogChannel maps the cap's 'mail' to the log's 'direct_mail'. A lead at the cap is deferred (defer-don't-drop) instead of over-messaged" },
  speed_to_lead:              { manager: "ai_isa",       proof: "test:speed-to-lead",     what: "SPEED-TO-LEAD ENGINE — every AI-ISA-owned lead gets a MICRO-PERSONALIZED first touch within minutes of promotion (email when email_verified, direct_mail fallback when mailing_address_verified, NEVER phone/SMS for unconsented leads); every newly-assigned contact gets an ISA jump-in after the agent grace window (default 5m) if the agent hasn't reached out — best CONSENTED channel (phone only when tcpa_consent && !dnc && !phone_opt_out); first_touched_at + first_touch_channel stamped on both tables; idempotent per-2-min cron is the safety net (m228 columns + partial needs-first-touch indexes)" },
  micro_personalization:      { manager: "ai_isa",       proof: "test:speed-to-lead",     what: "MICRO-PERSONALIZATION ENGINE — all ISA outreach copy (email/SMS/voicemail/call-opener) is assembled from the genuinely-present enrichment facts (occupation, life_events, household_income band, home_owner_status, marital_status, city, motivation, budget, timeline) for THAT record via the gateway; ZERO hardcoded message strings (replaced the ghost-subject, contact-SMS, lead-SMS templates); deterministic fallback varies with the facts so two different enriched records provably produce different copy; channel rules enforced (SMS ≤320 chars + STOP; voicemail ≤25s; Fair Housing in every prompt)" },
  credit_pipeline:            { manager: "ai_isa",       proof: "test:schema-drift",       what: "Credit-readiness nurture (kanban mirrors on contacts; credit_accounts canonical)" },
  briefing_isa_overnight:     { manager: "ai_isa",       proof: "test:isa-qualification",  what: "Overnight handoffs/escalations lead the agent + team-lead morning briefs" },
  voice_isa:                  { manager: "ai_isa",       proof: "test:isa-qualification",  what: "Voice calls feed the SAME rolling qualification + canonical handoff chain as email" },
  transaction_propensity:     { manager: "ai_isa",       proof: "test:propensity",         what: "Signal fusion — intent/engagement/equity/life-event/referral/recency fused into one transparent 'likely to transact in 90 days' score + top reasons (who to re-engage first)" },
  voice_dial_batch:           { manager: "ai_isa",       proof: "test:voice-dial-batch",   what: "AI ISA proposes a batch of CONSENTED high-propensity contacts to call; human approves; consent is RE-CHECKED at approval before any dial (voice is contacts-only, TCPA + ISA-reengage gated)" },
  client_as_actor:            { manager: "campaign_orchestrator", proof: "test:client-actor", what: "THE CLIENT BECOMES AN ACTOR — the missing arrow: a buyer/seller portal request flows INTO the same manager bench + approval gate the agent uses, instead of the client being a passive recipient of a read-only Q&A bot. classifyClientIntent + routeClientIntent (pure) encode the compliance contract: browse/search/save/ask is OPEN (NAR 2024 gates the tour, not the search); a showing routes to requestShowing (BBA enforced internally — if unsigned, a signing-link is PROPOSED to the agent, never dropped); a seller's price/listing change is PROPOSED to the Listing Concierge through the approval gate, never auto-executed; questions stay advisory. dispatchClientAction reuses the real primitives (requestShowing, proposeClientMessage); app/api/portal/client-action is the auth-gated surface. Nothing reaches anyone without a human in the loop — the client participates in the AI team, on the same page as the agent" },
  manager_signal_bus:         { manager: "campaign_orchestrator", proof: "test:manager-signals", what: "Inter-manager bus — managers publish outcomes, addressed managers consume by proposing governed deliverables; every conversation auditable + on the Command Center" },
  deconflict_defer_retry:     { manager: "campaign_orchestrator", proof: "test:deferral-retry", what: "DEFER, DON'T DROP — when the de-confliction frequency cap blocks a sequence send (one more touch would over-message the contact), the step-executor RESCHEDULES the same step instead of treating the deferral as a failed send and advancing past it (which silently dropped the touch). dispatch.ts returns providerKey 'deconflict_gate' on an over-touch block; isDeconflictDeferral distinguishes it from a real failure; decideDeferral reschedules current_step (unchanged) with a 24h backoff up to MAX_DEFERS, then gives up and advances so a perpetually-capped contact never stalls the cadence. The touch is preserved and retried once the over-touch window clears — the over-messaging cap protects the contact WITHOUT losing the message" },
  touch_ledger_unification:   { manager: "campaign_orchestrator", proof: "test:touchpoint-bridge", what: "THE SHARED TOUCH LEDGER — System A (the canonical sequence engine) records every send into marketing_campaign_touchpoints, the SAME ledger de-confliction / attribution / team-query read. Until now ONLY System B (marketing triggers) wrote touchpoints, so the canonical drip engine's sends were INVISIBLE to the over-messaging frequency cap (deconflict counts that table per contact+channel) — a contact could be over-messaged because the cap never saw the sequence's own sends. m1098 made campaign_id nullable + added sequence_id + source='sequence' (additive, empty table, zero data risk); step-executor records a touchpoint on every successful send (channel-mapped: email/sms/video feed the cap; best-effort, never fails a send). This ALSO de-risks retiring System B's enrollment path — A now feeds the shared ledger so de-confliction/attribution/team-query keep working" },
  first_touch_coordination:   { manager: "campaign_orchestrator", proof: "test:first-touch-coord", what: "THE BATON HAND-OFF — the welcome drip's first hello and the AI ISA speed-to-lead engine no longer collide: both share ONE ledger (contacts.first_touched_at / first_touch_channel) so a brand-new contact never gets two same-channel hellos within minutes. Scoped to the welcome arc only (CONTACT_CAPTURED-triggered FIRST outreach step) — an OFFER_ACCEPTED/LISTING_PUBLISHED day-0 step is NOT a first hello and always sends. decideFirstTouch (pure): skip_duplicate when the recorded first touch already used this channel (defer to AI ISA, published on the bus → Command Center 'managers talking'); send_and_claim when no first touch is on record (the drip stamps the ledger so speed-to-lead's `first_touched_at IS NULL` guard stands down); send for a genuine second channel (ISA called, drip emails). Idempotent `.is(null)` claim, race-safe — never clobbers the ISA's channel" },
  team_plays:                 { manager: "campaign_orchestrator", proof: "test:team-plays", what: "The huddle — ≥2 managers with open business on one client convene into ONE co-authored play; fragments superseded (no proposal spam), every play human-approved" },
  appointment_whisper:        { manager: "campaign_orchestrator", proof: "test:whisper",    what: "The Whisper — T-30 hallway briefing: the managers' combined knowledge on the next client whispered to the agent in the user's CONFIGURED assistant voice (audio on EVERY tier; text only when no voice is configured)" },
  fire_drills:                { manager: "deal_coordinator", proof: "test:fire-drill",  what: "The 9pm save — UNCOVERED deadline (contingency live + prerequisite missing) convenes the team: CRITICAL save-plan briefing (assistant voice on every tier), client-calming draft into the gate, audit line on the bus" },
  consent_recovery_chain:     { manager: "data_steward", proof: "test:consent-recovery", what: "Revoked consent is a CHAIN not a flag: fallback to the channel the client still allows (gated) → enrichment re-run for updated contact info → only then a respectful withdraw via the Sphere (history kept, never a delete)" },
  manager_dissent:            { manager: "campaign_orchestrator", proof: "test:manager-dissent", what: "Peer review before the human sees a proposal: a DIFFERENT manager checks Fair Housing (shared pattern list), consent, fire-drill timing + spacing — visible dissent notes; vetoes only for withdrawn/revoked (auditable, no forged approver)" },
  partners_meeting:           { manager: "campaign_orchestrator", proof: "test:partners-meeting", what: "Sunday Night Partners' Meeting — the week presented by the AI team (plays, drills, whispers, recoveries, dissents, deals + the one ask) as D-ID avatar video / assistant-voice audio / memo, every tier" },
  cron_dispatch:              { manager: "data_steward", proof: "test:cron-dispatch", what: "One heartbeat, every schedule — vercel.json keeps ONE per-minute cron; the registry preserves all 100+ loop schedules verbatim (Vercel's 40-cron cap was failing every deployment at config validation); drift closed both directions (route ⇄ registry ⇄ vercel.json)" },
  voice_bullpen_wiring:       { manager: "campaign_orchestrator", proof: "test:voice-team", what: "THE SPOKEN BULLPEN — the AI-team coordination commands (team_query/area_query/morning_standup) are now reachable from the ElevenLabs Conv AI SPOKEN voice admin, not just the internal voice route: registered in lib/voice/tool-registry.ts (read-only, gates:[], correct authority — team/area allow agent_or_isa, standup is agent-only) and dispatched through ONE shared lib/voice/team-commands.ts that calls the SAME kernel backends (runTeamQuery/runAreaQuery/runMorningStandup) the internal route uses — both front-ends share the dispatch, no drift, no duplicated logic. 'Hey team, what do you know about the Hendersons / what's near 44 Birch / what should I do today' (read-only) PLUS the acting verbs — standup_action ('knock out number two'), voice_followup ('send the Hendersons a follow-up' — proposal→approval gate, consent re-checked, gates:['evaluate_outbound']), start_marketing (gated sequence enrollment), cut_promo ('cut a reel for 44 Birch' — Remotion+D-ID rail, Fair Housing pre-flight) — all now work by voice. Acting verbs delegate to backends that enforce their OWN gate; nothing sends autonomously. Registry authority enforced (followup agent_or_isa; standup/cut_promo agent-only)." },
  team_query:                 { manager: "campaign_orchestrator", proof: "test:team-query", what: "'Hey team—' — the bullpen question: ask the voice admin about a person and the FULL bench reports what its OWN tables know (propensity, saves, deals+deadlines, gate, marketing touches+sequences, data hygiene, recruit overlap, bus talk, withdrawn state) in ONE manager-attributed spoken answer; read-only, honest when empty" },
  voice_delegation:           { manager: "campaign_orchestrator", proof: "test:voice-delegation", what: "The handoff after the bullpen: 'send a follow-up' = propose→approve AS the speaking agent through the SAME gate (consent re-checked; dictation verbatim); 'start marketing' = governed sequence enrollment (steps clear the compliance gate); 'cut a promo reel for 44 Birch' = manual trigger on the CANONICAL Remotion+D-ID rail (Fair Housing pre-flight, cooldown debounce, social drafts human-approved); WITHDRAWN refuses outreach" },
  morning_standup:            { manager: "campaign_orchestrator", proof: "test:morning-standup", what: "'Hey team, what should I do today?' — the managers rank the day's top 3 moves: fire drills first (most expensive to ignore), then aging client-message approvals (overdue past the 4h SLA outrank fresh), then the single warmest cooling lead (14d+ quiet, propensity-ranked); one spoken ranked answer, read-only, honest when the day is clear" },
  standup_action:             { manager: "campaign_orchestrator", proof: "test:standup-action", what: "'Knock out number two' — one-breath delegation on a ranked stand-up item: re-derived live (never stale), routed to its rail (approval→approve AS the agent through the gate; reengage→follow-up; fire is NEVER auto-resolved — a save plan is human judgment)" },
  area_query:                 { manager: "campaign_orchestrator", proof: "test:area-query", what: "'Anything happening near 44 Birch?' — the bullpen for a PLACE: the marketing bench reports active listings (Listing Concierge), reusable promo reels ready/rendering (Asset Manager), and live ads targeting the area (Ads Manager); read-only, honest when nothing's running" },
  idle_hands_initiative:      { manager: "campaign_orchestrator", proof: "test:idle-hands", what: "Managers fill silence with governed work: stale listings get social drafts (pending approval), recent closings get just_sold reels (lifecycle policy ON — automatic work never bypasses it), anniversaries get gated notes, missing email/phone self-heals via enrichment, the warmest cooling lead gets a PRE-DRAFTED re-engage (auto-draft ≠ auto-send); the IDLE RULE blocks initiative when a manager's own proposals already pend" },
  manager_office_hours:       { manager: "campaign_orchestrator", proof: "test:office-hours", what: "Drops, not sprays: morning + afternoon drops sweep unread per-proposal approval pings into ONE digest per agent grouped by manager (oldest wait surfaced); swept pings marked read (audit kept), CRITICAL never swept, gate/SLA untouched" },
  outcome_learning:           { manager: "campaign_orchestrator", proof: "test:outcome-learning", what: "The human's approve/reject decisions tune the team: HUMAN decisions only (peer-review vetoes + team-play supersedes excluded), trusted until a real sample (10+) falls below 40% approval — then that manager's INITIATIVE pauses (commands + scheduled duties continue); consulted live by idle-hands. Rejections carry the spoken WHY ('reject number two — too pushy' → agent feedback stored), and the TRUST METER on the Command Center shows rates + reasons per manager" },
  initiative_ledger:          { manager: "campaign_orchestrator", proof: "test:idle-hands", what: "'While you were away' — one leadership card per idle-hands pass that produced work (social drafts, reels, notes, data fixes, pre-drafts, seasonal plays), 12h dedupe; the morning proof the team worked overnight" },
  seasonal_plays:             { manager: "campaign_orchestrator", proof: "test:idle-hands", what: "Quarter-aware campaigns staged INACTIVE once per season (Spring Sellers / Summer Movers / Fall Market Reset / Year-End Gratitude) — the human activates; nothing runs until then; idempotent by season name" },
  persona_copy:               { manager: "campaign_orchestrator", proof: "test:ai-copy", what: "Copy is NEVER hardcoded — every play generates its wording per the contact's persona (name, audience, situation, brand tone) + the real facts through the AI gateway, with a deterministic fallback so a play always produces safe real copy; Fair Housing enforced in the system prompt" },
  commission_forecaster:      { manager: "deal_coordinator", proof: "test:commission-forecaster", what: "Live commission/GCI forecast per agent from the real pipeline (closed YTD + probability-weighted in-progress) → cap distance + pace-to-goal + the 1-2 deals to push; gated agent summary (optional assistant-voice audio); cap read if configured, honestly says so when not" },
  offer_net_sheet:            { manager: "listing_concierge", proof: "test:offer-net-sheet", what: "In-house listing with open offer(s) → side-by-side seller NET PROCEEDS comparison (price − payoff/taxes/HOA/commission/credit) ranked by NET (surfaces the offer that nets the seller most, not the highest price); ONE gated agent summary + a read-only seller-portal VALUE card + an interactive net sheet in the offer view & portal; idempotent per offer-set/24h" },
  closing_watchtower:         { manager: "deal_coordinator", proof: "test:closing-watchtower", what: "The EARLY layer on the date chain — a chain date MOVES (milestone audit trail: lifecycle.milestone.date_changed) → critical path to closing recomputed (binding constraint + slack + ok/tight/at_risk) → ONE gated Deal Coordinator alert with the concrete impact + a plain-language portal value card to BOTH represented sides; idempotent per move-set + per contact/day; no closing date on file → skipped honestly" },
  closing_war_room:           { manager: "deal_coordinator", proof: "test:closing-war-room", what: "The FINAL-MILE cockpit — one read-only surface per deal in the closing window: every clear-to-close CONDITION with an HONEST status (done/open/unknown — a signal we can't read is unknown, never a fabricated done) mapped to a real column (milestone chain, transaction_lenders.clear_to_close_date, title_escrow earnest_money + closing_scheduled wire proxy, contract_signatures fully_signed, the document-audit checklist), the REUSED watchtower critical-path timeline, wire/EMD confirmation, and the OPEN ITEMS the Deal Coordinator drives to done (transaction_tasks + transaction_pending_actions, severity-ordered, each with an owner). closingReadiness is ready ONLY when every required condition is genuinely met; an unknown required condition is itself a blocker. No new tables, no writes; no closing date -> honest skip" },
  anniversary_equity:         { manager: "sphere_of_influence", proof: "test:anniversary-equity", what: "Yearly closing-anniversary equity report for past clients: REAL AVM value vs purchase price; equity only when the original loan is on file (else appreciation-only and the copy says so); portal value card (equity_report) + ONE gated agent proposal carrying the ready-to-send anniversary note + optional D-ID+ElevenLabs avatar video when the agent's voice/avatar is configured; one report per contact per YEAR; no valuation → honest skip" },
  listing_appt_prep:          { manager: "listing_concierge", proof: "test:listing-appt-prep", what: "the flagship pre-listing-appointment chain — CMA → presentation → D-ID chapter videos → pre-appointment drip, run-dedupe idempotent per (chain,entity,trigger); pushes a seller-portal value card up front (the flywheel)" },
  financing_pit_stop:         { manager: "deal_coordinator", proof: "test:financing-pit-stop", what: "Deal enters the FINANCING window (financing milestone approaching, or buyer's pre-approval going stale — real stored dates only, else skipped) → parallel rate-refresh RACE across the preferred lender bench (one GATED rate-request draft per preferred lender, nothing auto-sends), known/returned quotes ranked by lowest EFFECTIVE COST (rate + points + amortized fees) → ONE gated Deal Coordinator agent summary + a read-only buyer-portal value card; rates labeled estimates; idempotent one-race-per (deal, financing-window). Complements the Title & Closing Watchtower (date side)" },
  bidding_war_concierge:      { manager: "shopping_agent", proof: "test:bidding-war", what: "Buyer-side bidding-war prep on an OUTSIDE listing — escalation-strategy brief (ceiling+cap+term levers, agent-gated), a buyer-voice 'highest-and-best' cover letter DRAFT (Fair-Housing constrained) for the buyer to approve, and a rapport note to the outside listing agent; one bundle per offer, nothing auto-sends" },
  reverse_prospecting:        { manager: "shopping_agent", proof: "test:reverse-prospecting", what: "A new/coming-soon listing matches the brokerage's OWN buyers by saved criteria (property_preferences) → Shopping Agent proposes a persona-aware buyer note per match (gated) + AI ISA queued as call candidates (bus); one note per (listing, buyer) ever — inventory becomes instant buyer demand" },
  tour_optimizer:             { manager: "shopping_agent", proof: "test:tour-optimizer", what: "Buyer Tour Day Optimizer — a planned tour's stops are geocoded (FREE OSM Nominatim) and ordered nearest-neighbor by drive time (haversine @ 30mph ESTIMATE, labeled 'est.'; un-geocodable stops kept in place with null drive — no fabrication), written back to tour_stops.order_index + drive_time_from_prev_minutes + tours.total_drive_time_minutes + a showing_routes audit row; after completion ONE buyer-portal value card recaps the day (loved/liked counts + per-home feedback + warm next step) and stamps the tour reported; idempotent per tour" },
  vendor_orchestration:       { manager: "deal_coordinator", proof: "test:vendor-orchestration", what: "As a deal crosses each stage the right bench vendor (inspector/lender/title; stager ONLY when staging is enabled in brokerage settings) is proposed PREFERENCE-FIRST (preferred over rating) with a persona-aware quote draft — gated to the agent, one per (txn, service_type), nothing auto-books" },
  objection_library:          { manager: "ai_isa", proof: "test:objection-library", what: "Every ISA-call objection is categorized; the rebuttal that books the most appointments is crowned (min-sample gated) and fed to the next call script — sales intelligence compounding off real conversations; no new table (derived from ai_isa_calls)" },
  equity_trigger:             { manager: "sphere_of_influence", proof: "test:equity-trigger", what: "PAST-CLIENT EQUITY TRIGGER — the Sphere watches every past client's home value + the rate environment and fires on a MATH crossing (not a calendar date): meaningful equity GAINED (cash-out, real equity >= $150k AND >= 35% of value) or current rates >= 75bps below the client's ORIGINAL locked rate with >= $150/mo modeled saving (refi). Reuses anniversary-equity computeEquityLine; proposes ONE gated agent note + a Director EquityReportReel + a portal value card. Rate fabrication forbidden (no authoritative market_rate_snapshots row or source seed_default -> equity-only, refi null); no valuation -> honest skip. Idempotent per (contact, trigger-type, quarter); withdrawn excluded" },
  referral_radar:             { manager: "sphere_of_influence", proof: "test:referral-radar", what: "Data Steward derives a life-event on a past client (job change, equity milestone, etc.) and the Sphere surfaces BOTH a nudge (internal notification — who to reach + why) AND a persona-aware touchpoint drafted into the gate; one per (contact, event) per 90d; withdrawn excluded" },
  campaign_command_center:    { manager: "campaign_orchestrator", proof: "test:campaign-center", what: "ONE surface for every marketing draft the bench staged across all channels (social/email/newsletter/blog/direct-mail/ads/neighbor-farm/open-house), grouped by play — the agent approves the whole campaign in one place instead of piecemeal" },
  marketing_bench:            { manager: "campaign_orchestrator", proof: "test:marketing-bench", what: "ONE primitive stages a coordinated draft across EVERY channel (social, email, newsletter, blog, direct mail) — each gated to its pending/draft state, idempotent, ID-space + CHECK-constraint correct; the plays just say 'stage these' and the bench handles every table" },
  intent_campaign:            { manager: "data_steward", proof: "test:intent-campaign", what: "The Data Steward leads outbound: SCRAPES motivated sellers (BatchData high-equity/absentee/pre-foreclosure) in active markets + the brokerage's own high-intent buyers, then the bench drafts SITUATION-SPECIFIC email + direct mail to each — gated, scrape is an injectable seam (no test spend)" },
  launch_war_room:            { manager: "campaign_orchestrator", proof: "test:launch-war-room", what: "The new-listing bookend to the Farm Play: a coming-soon/just-listed listing convenes the bench — reel + social/email/newsletter/blog + the FIRST open house scheduled + a coming-soon neighbor farm + a geo ad + one agent summary; all gated, one war room per listing" },
  lookalike_audience:         { manager: "ads_manager", proof: "test:lookalike", what: "First-party lookalike from the CLOSING TABLE: the Ads Manager seeds a lookalike audience from the brokerage's actual closed buyers (who really bought, where) — paid spend chases proven converters, not generic interest segments; staged as a draft ad (min seed guard)" },
  farm_play:                  { manager: "campaign_orchestrator", proof: "test:farm-play", what: "A Team Play for a PLACE — geographic farming, the listing agent's #1 growth engine, run as ONE coordinated multi-manager play on each closed deal: Data Steward stages the neighbor farm (seller-permission-gated), Marketing drafts the 'just sold near you' postcard, Ads stages a geo campaign (draft), Recruiting logs standout wins as talent-pipeline proof, Campaign Orchestrator proposes one agent summary — six managers, nothing sends until seller OK + human approval" },
  client_pulse:               { manager: "listing_concierge", proof: "test:client-pulse", what: "The CLIENT's weekly 'what your team did for you': sellers get showings+feedback, social, reel status, live ads, next deadline with HONEST coverage ('already covered' vs 'on it'); buyers get saves, tours, deal stage; gated (proposed→approved→portal card), one per client per week, empty weeks stay SILENT — answers 'my agent went dark'" },
  voice_results_loop:         { manager: "ai_isa",       proof: "test:manager-signals",    what: "Call outcomes shape the next dial list (cooldowns: recent call 14d, cold outcome 30d, appointment → hand off to the concierge via the bus)" },
  // ── Surface sections owned by their domain managers ──
  briefing_deal_risk:         { manager: "deal_coordinator",  proof: "test:manager-ownership", what: "Deals-at-risk briefing sections" },
  deadline_watcher:           { manager: "deal_coordinator",  proof: "test:deadline-watcher", what: "Inspection/appraisal/financing/walkthrough/closing deadlines within 24h notify the deal parties (was built but never scheduled — found by the domain audit)" },
  appointment_noshow_autopilot: { manager: "deal_coordinator", proof: "test:appointment-noshow", what: "Protect every auto-booked appointment: a MISSED appointment (start past a grace window, still 'scheduled') → mark the calendar_event 'no_show' (free-text status, no fabricated enum) + audit lifecycle_event + a GATED warm re-book ('sorry we missed you — here are new times') + fed to the EXISTING AI-ISA re-engage entry point (no parallel re-engage); an UPCOMING appointment within the reminder window → ONE gated client reminder. Idempotent per (appt, stage); nothing auto-sends" },
  document_compliance_audit:  { manager: "deal_coordinator", proof: "test:document-audit", what: "DOCUMENT COMPLIANCE AUDIT (retires audit-document + broker-audit workflows) — a HYBRID pass: an OCR/content TEXT pass (the existing lib/documents/ocr-pdf text layer + deterministic + optional gateway-TEXT checklist) MERGED with a gateway VISION pass (openai/gpt-4o or anthropic/claude-3-5-sonnet via the Vercel AI Gateway — Gemini vision is BANNED, guarded) over the document image (client_documents.document_url) that sees what OCR cannot: signature inked per signer, initials, checkboxes, stamp, date filled. classifyFindings merges both streams; records on client_documents.ai_metadata (REUSED jsonb, no new table) with an honest method (vision+text | text_only | vision_only | not_audited), and on findings ESCALATES to the broker via the existing notifications rail + a manager-signals bus line. Both passes are injectable seams; honest degradation — vision unavailable -> text-only partial_audit (NEVER a fabricated signature finding), neither -> not_audited; idempotent per (document, extracted-text + vision content); hourly sweep cron" },
  document_autofile:          { manager: "deal_coordinator", proof: "test:document-autofile", what: "THE AI AUTO-FILING CLERK (retires document-storage-logic workflow) — kills the #1 transaction-admin chore: a recently-uploaded UNFILED client_documents row is classified (injectable gateway classifier → PURE keyword/extension floor) into the canonical doc_category enum and routed to the right DEAL (stamped transaction, else the uploader's single open transaction) — sets doc_category + document_type folder key + transaction_id + ai_metadata audit, recorded on lifecycle_events. HONEST: low confidence → left UNFILED + flagged for human (never misfiled); idempotent (an already-categorized doc is a no-op). Files the storage OBJECT too: MOVES it within the client-documents Supabase Storage bucket into the deal-folder path {brokerage}/{transaction_id}/{doc_category}/ (idempotent; honest when document_url has no parsable bucket path; a failed move still files the row); 15-min sweep cron" },
  document_custody:           { manager: "deal_coordinator", proof: "test:document-custody", what: "DOCUMENT STORAGE CUSTODY — compliance-grade custody for the PRIVATE client-documents bucket: issueGovernedDocumentUrl mints a TIME-LIMITED createSignedUrl (TTL by purpose: view 5m/download 15m/share 1h/compliance_export 24h) instead of a bare ungoverned getPublicUrl, and RECORDS who/when/why/doc on the EXISTING document_access_log (no new table); retentionPolicyFor(doc_category) is a DATA map of keep-years (legal record 7yr / diligence 5yr) honest about being a DEFAULT not law; runRetentionScan FLAGS docs past their window for human review (gated report, NEVER auto-deletes). HONEST: a document_url with no parsable bucket object (data: fallback / external) cannot be signed — returns a reason, never a fabricated URL or audit row; reuses the autofile bucket+path rails; weekly cron" },
  deal_autopsy_learning:      { manager: "deal_coordinator", proof: "test:deal-autopsy", what: "DEAL-AUTOPSY LEARNING — post-mortem for fallen-through deals: when a transaction reaches status='lost', classifyFailureReason derives the failure reason (financing/inspection/appraisal/cold_feet/title/low_appraisal/competing_offer/other) from REAL contingency columns + lender/inspection/title evidence (never fabricated); runDealAutopsy persists the observation (deal_autopsy_observations m226, idempotent per transaction), feeds the coaching loop via proposeClientMessage (audience='agent', the same inbox runAgentCoaching uses — agent-coaching.ts unchanged), and publishes a deal_coordinator → recruiting_manager:deal_autopsy_completed bus signal. Trigger: runLostTransactionAutopsies (closing-orchestration, additive). HONEST: reason only from the 8-value enum; no contingency evidence → 'other' at low confidence, never a fabricated cause" },
  briefing_listing_risk:      { manager: "listing_concierge", proof: "test:manager-ownership", what: "Listings-at-risk briefing sections" },
  client_message_gate:        { manager: "campaign_orchestrator", proof: "test:client-extract", what: "Every client-facing AI output proposes → human approves → sends" },
  portal_final_hop:           { manager: "campaign_orchestrator", proof: "test:portal-e2e", what: "End-to-end: approved portal messages render a visible client card; regulated channels (sms/email) hard-block at the consent gate before any send" },
  manager_daily_standup:      { manager: "campaign_orchestrator", proof: "test:manager-ownership", what: "Broker's daily per-manager accountability report (manager-standup.ts); every line manager-attributed" },
  manager_weekly_pnl:         { manager: "campaign_orchestrator", proof: "test:command-center", what: "Broker's weekly per-manager production scorecard (manager-weekly-pnl.ts); WoW outcomes incl. GCI" },
  brokerage_owner_report:     { manager: "campaign_orchestrator", proof: "test:brokerage-pnl", what: "Owner's Report — YTD GCI + company dollar, production by agent, recruiting ROI, referral value (brokerage-pnl.ts)" },
  governed_deliverables_rail: { manager: "campaign_orchestrator", proof: "test:deliverables", what: "Unified rail — every loop's gate proposals rolled up (count, human-approved, by manager + loop); the proof-of-system view" },
  agent_scorecard:            { manager: "deal_coordinator", proof: "test:agent-scorecard", what: "Per-agent production + deal health + education completion + recruiting ROI (agent-scorecard.ts) — agent-management view" },
  mobile_approval_push:       { manager: "campaign_orchestrator", proof: "test:mobile-approval", what: "Two-tier approval push: agent (front line) on every pending approval, manager escalation at 4h (approval latency is the egress's critical path)" },
  nothing_dropped_sweep:      { manager: "campaign_orchestrator", proof: "test:nothing-dropped", what: "THE NOTHING-DROPPED SWEEP — the LIVE-DATA proof of the core promise (nothing falls through the cracks), and the antidote to the agent/team/broker anxiety 'what am I forgetting / about to lose?'. The per-entity safety nets (stale-contact monitor, lead ghost detection, deadline watcher, approval office-hours) each work ONE lane; NOTHING unifies them. This composes the awaiting states across entities — pending showings, proposed approvals, open inter-manager signals, never-first-touched leads (leads stay AI-ISA owned) — into ONE ranked card: everything past its SLA with no next action, worst-first. Pure findDroppingBalls (past-SLA AND no-next-action) + severity = overdue × criticality (an untouched OFFER outranks a stale lead); summarizeSweep caps the card. runNothingDroppedSweep is READ-ONLY (a sweep never writes; opt-in to escalate a gated digest). Contacts + transactions excluded — their dedicated monitors own them. The live-data complement to the governance egress_coverage_audit" },
  egress_coverage_audit:      { manager: "data_steward", proof: "test:egress-coverage", what: "Meta-audit: every burn domain's proof is runnable, every manager owns something, no dangling/orphan ownership — the governance graph stays whole" },
  seller_update_video:        { manager: "listing_concierge", proof: "test:seller-update-video", what: "Weekly seller-update D-ID avatar video proposed into the client-message gate (no HeyGen)" },
  strategy_learning_loop:     { manager: "shopping_agent",    proof: "test:strategy-learning",  what: "Offer/counter outcomes close the loop back to the recommendation that produced them (strategy_outcomes)" },
  strategy_learning_insights: { manager: "shopping_agent",    proof: "test:strategy-insights",  what: "Accumulated outcomes → market intelligence (win rate, deviation, by strategy type) fed back into the next recommendation" },
  referral_closing_loop:      { manager: "sphere_of_influence", proof: "test:referral-closer", what: "Deal close → matching referral closed, partner lifetime value credited, partner thank-you proposed into the gate" },
  recruiting_outreach_loop:   { manager: "recruiting_manager", proof: "test:recruit-outreach", what: "Recruit stage advance / stale recruit → next recruiting outreach proposed into the gate (talent pipeline kept warm)" },
  capacity_guardian:          { manager: "recruiting_manager", proof: "test:capacity-guardian", what: "THE CAPACITY GUARDIAN — protects the HUMAN so the ball is NEVER dropped (the core promise to agents/teams/brokerages). Every other tool scores OUTPUT (GCI/closings) or frames a cold book as a performance leak; this is the inverse — it detects when an agent is OVERLOADED and proposes the team REBALANCE work BEFORE any lead/contact/follow-up goes stale. LEADS COUNT as real load (a lead with no portal still needs the AI ISA to qualify it). Pure computeAgentWorkloadIndex (active contacts + leads + deals vs the TIER ceiling — solo 40 / team 75 / brokerage 150 / multi 250 — plus follow-up DEBT = stale contacts + overdue tasks); burnoutRisk is HIGH when at/over the ceiling OR debt ≥ DEBT_ALARM (the ball is already dropping, regardless of headcount). detectOverload proposes the MINIMUM rebalance to get back under the ceiling / clear the worst debt. runCapacityGuardian publishes a GATED, persona-generated (never hardcoded) recommendation on the inter-manager bus (recruiting_manager → ai_isa to pause assignment), tier-aware, dedup per agent; nothing moves a client autonomously — the broker/team-lead approves" },
  recruiter_agent_mgmt:       { manager: "recruiting_manager", proof: "test:recruiter-agent-mgmt", what: "Commission & Cap Forecaster loops the Recruiting Manager into agent-management via the bus: an agent who HITS/crosses cap → agent_crushed_cap (recruiting PROOF surfaced to broker/admins); a STALLING agent (real pipeline + big projected miss, or zero production + thin pipeline) → agent_stalling (coaching prompt to the responsible manager, never autonomous to the agent); deal_coordinator → recruiting_manager, dedupe per (recruiting_manager, type, agent)" },
  agent_coaching_loop:        { manager: "recruiting_manager", proof: "test:agent-coaching", what: "THE AGENT COACHING LOOP — the brokerage develops its PEOPLE: a weekly per-agent coaching brief (composeCoachingBrief -> strengths / leaks / one focus) from REAL stats only — REUSES generateAgentScorecards (production+deal-health+education) + the no-show (calendar_events no_show) / stale-book (last_contacted_at past DEFAULT_STALE_DAYS) / tour->offer aggregates; documented sample-gated thresholds, honest not-enough-data for thin agents (never invented criticism). Owner recruiting_manager (already owns agent development via recruiter_agent_mgmt). ONE GATED manager-facing brief per (agent, ISO week) to broker/team-lead (proposeClientMessage, audience agent) — never autonomous to the agent; no new tables. (consolidated: the old coaching-engine weekly report is retired; the coaching dashboard reads this brief)" },
  portal_value_card:          { manager: "campaign_orchestrator", proof: "test:portal-value", what: "The shared portal-value primitive: every contact-touch play (Client Pulse, Referral Radar, Reverse Prospecting) leaves ONE fresh REAL card on the contact's portal each run (transparency_updates, is_visible_to_client=true) drawn from values it already computed — idempotent per (contact, update_type, day), no fabrication, skips when a play has nothing real to say; the portal is always worth returning to" },
  vendor_marketplace_loop:    { manager: "deal_coordinator", proof: "test:vendor-loop", what: "Vendor booked → client intro proposed (Deal Coordinator); service completed → client review request proposed (Sphere) — both gated" },
  education_delivery_loop:    { manager: "shopping_agent", proof: "test:education-delivery", what: "Client at a lifecycle stage → side-appropriate concierge proposes the best-matched lesson into the gate + records the assignment" },
  video_outro_qr:             { manager: "asset_manager", proof: "test:video-qr", what: "AI-made reels carry a SCANNABLE, TRACKED outro QR reusing the existing qr_codes/qr_scan_events backend (no new tables): kind→destination_type map (just_listed/just_sold→listing_detail, open_house→book_meeting, presentation_chapter→video_avatar_tour, anniversary→anniversary_video, newsletter→landing_page); the /api/qr/scan?slug= resolver stays the dynamic indirection (target_url editable, slug never stale); idempotent per (entity,kind) so re-renders reuse one tracked code; default-off + mlsClean-clean (no QR on MLS cuts); a mint failure never blocks the render" },
  video_coordination:         { manager: "campaign_orchestrator", proof: "test:video-coordination", what: "A finished render becomes ONE coordinated team deliverable on the bus: Asset Manager → Campaign Orchestrator (gated multi-channel distribution draft, approval pending) ALWAYS + Ads Manager (proposed paid promotion) for promotable kinds (just_listed/just_sold/open_house) + on render failure → campaign_orchestrator:video_compliance_failed escalation; deduped per ai_video_project, nothing auto-publishes or auto-spends, the polling crons stay as idempotent safety nets" },
  video_director:             { manager: "asset_manager", proof: "test:video-director", what: "The Asset Manager DIRECTS video creation: selectVideoFormat picks the best of the 24 Remotion compositions per situation×target-channel (new_listing×TikTok→JustListedReelSquare+B-roll; ×YouTube→Horizontal 16:9; market/cma→chart reels; explainer→avatar; presentation→narrated slides; anniversary→EquityReportReel), then commissionVideo assembles intro (brand+agent photo+hook) → main (the chosen format) → outro (brand+contact+tracked QR), staging a compliance-gated ai_video_projects row the existing render crons + concatIntroOutro bookends carry; idempotent per (entity,kind), MLS-clean respected, never auto-publishes" },
  director_eval:              { manager: "data_steward", proof: "test:director-eval", what: "Compliance EVAL/REGRESSION harness over the autonomous Video Director (auditor distinct from the audited asset_manager): PROVES the autonomy stays governed by the EXISTING runtime gate (evaluateOutbound) — detectUngroundedClaims flags hook/caption/script facts not in commissionVideo's bounded factStrings (net-new grounding/hallucination coverage); detectFairHousingRisk reuses the ENCODED FAIR_HOUSING_PATTERNS (+ state_protected_classes) and is asserted to AGREE with the real Gate-4 evaluator (no invented rules); evalScopeCreep asserts approval_status stays 'pending_review' (never auto-publishes); evalLearningCannotRewardBlocked asserts a blocked variant never stages → never scored. Pure (CI) + guarded read-only live; exercises the gate, never a new gate" },
  ai_sentinel:                { manager: "data_steward", proof: "test:ai-sentinel", what: "THE AI SENTINEL — license-risk sentiment escalation (kernel equivalent of the retired negative-feedback-escalation workflow): classifyLicenseRisk tiers an inbound comm none|elevated|critical from deterministic patterns (explicit board/HUD complaint, lawyer/sue/breach, discrimination/steering grievance reusing the ENCODED FAIR_HOUSING_PATTERNS = critical; 'speak to your manager'/severe dissatisfaction = elevated; normal/positive/plain-opt-out = none, honest no-op). The tier ABOVE the opt-out seed (detectNegativeIntent): on tier!=='none' HALTS automation (reuses the seed's halt — isa_reengage_allowed=false +dnc on critical, leads.call_stop_flag), ESCALATES to the human broker via the EXISTING notifications rail (priority by tier) with the matched signals, records the incident on activities + a manager_signals audit — NEVER auto-replies to a license-risk message. Wired into handle-inbound-email BEFORE the reply/intent classifier; idempotent per (entity, incident); no new tables" },
  video_broll:                { manager: "asset_manager", proof: "test:video-broll", what: "B-roll picker sources real lifestyle clips from the video_assets scope cascade (agent→team→brokerage, Mediabunny-probed durations) so the Director composites them under needsBroll formats (ComingSoon/Neighborhood/vertical Just-Listed); selectBrollPlan fills/loops/truncates the timeline; honest empty → no B-roll, never a fabricated clip or broken render" },
  explainer_anim:             { manager: "asset_manager", proof: "test:explainer-anim", what: "Animated explainer reel — a real-estate concept as a deterministic moving diagram (equity-over-time draw-on curve / rate-buydown payment bars / closing-timeline stepped path / what-$X/mo-buys price bars) with optional avatar PIP narration; the in-stack answer to Manim (NO Python runtime). Diagram CONTENT is the pure explainerDiagramSpec(topic, facts) output; topic rides situation.facts; geometry reuses lib/charts/geometry; honest hasData=false 'share your numbers' fallback when facts are thin — never fabricates a chart" },
  format_learning:            { manager: "asset_manager", proof: "test:format-learning", what: "The Video Director SELF-IMPROVES: scoreFormatOutcomes turns REAL signals (qr_scan_events on each video's minted QR + social_posts engagement) into per (kind×channel×composition×mood) performance; recommendFormatAdjustment keeps the deterministic default UNLESS a competitor has ≥ a real sample AND beats it by a clear margin (reusing outcome-learning's gating), then returns the learned pick + a human-readable why stamped to video_metadata.format_source; selectVideoFormatLearned with empty data === selectVideoFormat (backward-compatible) — never fabricates, never overrides on thin data" },
  promo_composition:          { manager: "asset_manager", proof: "test:promo-composition", what: "render-just-listed routes the composition per listing_promo event_type through the Director's SituationKind taxonomy instead of hardcoding JustListedReel: just_sold→JustSoldReelSquare (soldPrice/daysOnMarket/above-asking), open_house_*→OpenHouseAnnounceReel (date/time headline), coming_soon→ComingSoonReel (whenString/teaser/broll); just_listed/price_reduction/under_contract keep the legacy vertical 25s organic reel (hybrid D-ID bookends + 9:16 social). Missing required facts → honest fallback to JustListedReel, flagged, never a broken render" },
  hook_ab:                    { manager: "asset_manager", proof: "test:hook-ab", what: "Hook A/B 'first-3-seconds' engine — the Director drafts 2-3 distinct OPENING hook angles (curiosity/social-proof/urgency/value), each independently compliance-gated, and stages them as ai_video_projects rows sharing an experiment_id (+ variant_index + hook_variant) each minting its own tracked QR; format-learning's scoreHookOutcomes + recommendHookWinner crown the winning opener ONLY past the same sample+margin gate (real qr_scan_events + social engagement), stamping hook_source default|learned so future commissions prefer it. Nothing auto-publishes; honest 'still testing' on thin data; single-hook path unchanged" },
  photo_walkthrough:          { manager: "asset_manager", proof: "test:photo-walkthrough", what: "Cinematic photo→walkthrough reel — turns any MLS photo set (listing_media file_url, sort_order asc) into a MOVING property tour so a listing with NO video still gets a scroll-stopping reel: each photo gets a Ken Burns pan/zoom over its own frame window with a cross-fade + narrated tour-beat captions. Motion is the PURE kenBurnsPlan(photos, bodyFrames, opts) output (windows tile the timeline, alternating pans, oversized set capped, sane scale/pan bounds); honest empty → [] so the Director skips it; reuses the JustListedReel brand/QR/voiceover contract" },
  caption_burn_in:            { manager: "asset_manager", proof: "test:captions", what: "Sound-off captions: buildCaptionPlan chunks a script into ≤4-word cues that tile the VO timeline (no overlap, sane dwell), word-accurate from REAL ElevenLabs with-timestamps alignment when present else honest even-distribution ESTIMATE (timingSource flag, never claims sync it lacks); empty script → []; CaptionLayer cue-selection is bounds-safe; additive + default-off across the VO-bearing compositions so existing renders never regress" },
  content_studio:             { manager: "asset_manager", proof: "test:content-studio", what: "The Content Studio — the Asset Manager's command surface that makes the AI creative team VISIBLE and approvable: loadContentStudio aggregates every Director-staged ai_video_projects reel into pending_review + recently-approved groups, each surfacing composition/aspect/channels, music mood, format_source + the learned WHY, the hook A/B (variants + crowned winner via recommendHookWinner's sample+margin gate), caption state, QR/B-roll flags; approveContentItem flips ONE reel through the REAL existing ai_video_projects gate (pending_review→approved, brokerage-scoped, idempotent) — read-only aggregation, gated approve, no new tables" },
  geo_reel_autopublish:       { manager: "asset_manager", proof: "test:geo-reel-pages", what: "Every broker-APPROVED + compliance-PASSED + completed reel auto-publishes to a public, AI-search-citable /v/[slug] page (complete schema.org VideoObject + RealEstateListing JSON-LD, thumbnailUrl=the VideoCoverThumb OG cover, llms.txt + sitemap inclusion, AI-crawler robots) so ChatGPT/Perplexity/Gemini/Google AI Overviews can CITE the agent's listings — gated ONLY to approved+compliant reels (a public page is broadcast advertising carrying Fair-Housing/EHO/license disclosures), idempotent per reel (public_slug minted once, never double-publishes)" },
  ai_search_citation_monitor: { manager: "campaign_orchestrator", proof: "test:citation-monitor", what: "The GEO INGRESS loop (pairs with geo_reel_autopublish's egress) — tracks whether AI search engines (ChatGPT/Perplexity/Gemini/Google AI Overviews/Bing Copilot) actually CITE our published /v/[slug] reel pages + brand via a gated web/Exa/Tavily query; scores AI-search visibility 0..1 from REAL recorded observations (cited / not_cited / honest not_checked when the search rail is down — not_checked excluded from the denominator, never a fabricated citation); idempotent per (page, platform, day); observations in m223 ai_search_citation_observations" },
  lead_intake_cockpit:        { manager: "data_steward", proof: "test:lead-intake", what: "The Lead Intake Cockpit — read-only command surface over the FRONT of the lifecycle: the live raw_scraped_leads → THE GATE (processRawRecord: enrich/dedup/territory+identity guards) → leads (ai_isa_owner) → contact funnel, folded into stage counts (pending/promoted/rejected/error + converted), per-SOURCE conversion (raw→lead, lead→contact), the GATE-REJECTION breakdown with WHY (unassigned_no_market; territory_mismatch; insufficient identity; duplicate; error), and the top hot seller-intent leads the AI ISA is holding (ai_isa_owner, contact_id NULL, Listing Inventory Radar note + lead_score). Pure helpers unit-testable, honest zeros when empty; NO writes, no new tables — reuses the existing pipeline truth" },
  listing_inventory_radar:    { manager: "data_steward", proof: "test:inventory-radar", what: "Continuously surfaces SELLER-INTENT candidates the scraper bench already scraped (expired/withdrawn, FSBO, absentee, high-equity/pre-foreclosure) from raw_scraped_leads, scores intent 0..1 (documented weights — pre-foreclosure+high-equity outranks a fresh low-equity FSBO) + ranks, then feeds the hottest INTO THE CANONICAL FLOW: PROMOTE through THE GATE (processRawRecord — enrich/dedup/territory+identity guards) into a `leads` row (ai_isa_owner=true, NO portal, NOT a contact), carry the intent score+reasons onto the lead (notes + lead_score floor) so AI ISA prioritizes it, and route data_steward → ai_isa for qualification. The client-facing seller path (data_steward → listing_concierge: gated 'thinking of selling?' brief + Director reel + gated CMA) applies ONLY post-conversion, when the candidate is already a CRM contact (leads.contact_id). Idempotent per (candidate, window); never scrapes, never fabricates contact info, never messages a non-contact, nothing auto-sends" },
  voice_studio_session:       { manager: "asset_manager", proof: "test:studio-session", what: "VOICE STUDIO SESSION BATCH — one spoken command ('book me a week of content') plans a GATED content calendar: planStudioSession (PURE) derives N reels from REAL inputs (active listings + evergreen topics, spread across upcoming weekdays); commissionStudioSession fans out to the existing Video Director commissionVideo for each item so every reel goes through the full Director pipeline (format selection → compliance gate → QR mint → pending_review). The session is persisted in studio_sessions (m225) + ai_video_projects.studio_session_id links each reel back. Idempotent per session_key. Nothing auto-publishes — the agent approves each reel in the Content Studio. Wired into voice-command route as the studio_session intent + the book_studio_session voice tool. D-ID + ElevenLabs ONLY." },
  multilingual_reels:         { manager: "asset_manager", proof: "test:multilingual-reel", what: "MULTILINGUAL REEL VARIANTS — the Asset Manager produces reels in multiple languages: (1) script translated via the existing AI gateway (NOT Gemini); (2) ElevenLabs TTS rendered with the eleven_multilingual_v2 model + target language; (3) translated captions burned into the Remotion composition via the existing CaptionLayer. commissionMultilingualReel (lib/video/multilingual-reel.ts) fans out one reel per locale, idempotent per (entity, kind, locale), compliance-gated via the EXISTING Director (commissionVideo), NEVER auto-publishes. D-ID + ElevenLabs ONLY (no HeyGen, no Gemini). localeToElevenLabsLanguage maps BCP-47 tags to ElevenLabs language_code; eleven_multilingual_v2 auto-detects from translated text as fallback" },
}

/**
 * GUARDED-TABLE OWNERSHIP — every table under the schema-drift guard has an owning
 * manager, so every remaining baseline entry (and any future drift) lands on a named
 * manager's burn-down list. The ownership simulator derives the table list from the
 * live snapshot: adding a guarded table without an owner FAILS the regression.
 */
export const TABLE_MANAGER: Record<string, ManagerKey> = {
  contacts:                     "data_steward",
  leads:                        "ai_isa",
  raw_scraped_leads:            "data_steward",
  property_preferences:         "shopping_agent",
  listings:                     "listing_concierge",
  property_matches:             "shopping_agent",
  saved_properties:             "shopping_agent",
  agent_client_messages:        "campaign_orchestrator",
  remotion_composition_renders: "asset_manager",
  notifications:                "campaign_orchestrator",
  assignment_log:               "ai_isa",
  ai_daily_briefings:           "ai_isa",
  ai_isa_call_batches:          "ai_isa",
  manager_signals:              "campaign_orchestrator",
  transactions:                 "deal_coordinator",
  // Buyer side: the buyer WRITES offers (pre-acceptance) and goes on tours.
  offers:                       "shopping_agent",
  tours:                        "shopping_agent",
  tour_stops:                   "shopping_agent",
  // Seller side: in-house showings OF our listings (external buyer agents,
  // ShowingTime sync, access codes) belong to the listing's manager.
  showings:                     "listing_concierge",
  tasks:                        "deal_coordinator",
  // The activity ledger is dominated by ISA engagement records (outreach, calls,
  // messages while qualifying) — the AI ISA is accountable for it.
  activities:                   "ai_isa",
  calendar_events:              "deal_coordinator",
}

/** Resolve the manager accountable for a maintenance/burn domain (never undefined). */
export function resolveMaintenanceManager(domain: string): ManagerInfo {
  const entry = MAINTENANCE_DOMAINS[domain]
  return entry ? MANAGERS[entry.manager] : FALLBACK_MANAGER
}

/** Resolve the manager accountable for a guarded table's data integrity (never undefined). */
export function resolveTableManager(table: string): ManagerInfo {
  const key = TABLE_MANAGER[table]
  return key ? MANAGERS[key] : FALLBACK_MANAGER
}

/** Fallback owner for any activity not yet mapped — surfaced so nothing is ever truly orphaned. */
export const FALLBACK_MANAGER: ManagerInfo = {
  key: "marketing_agent", label: "Operations", domain: "Unassigned — needs an owner",
}

/**
 * Resolve the owning manager for a Command Center action. For `client_message` the
 * owner is the proposing manager (its agent_kind); for every other queue it's the
 * static QUEUE_MANAGER owner. Never returns undefined (zero-orphan guarantee).
 */
export function resolveActionManager(queue: string, agentKind?: string | null): ManagerInfo {
  if (queue === "client_message") {
    if (agentKind && agentKind in MANAGERS) return MANAGERS[agentKind as ManagerKey]
    return FALLBACK_MANAGER
  }
  const key = QUEUE_MANAGER[queue]
  return key ? MANAGERS[key] : FALLBACK_MANAGER
}
