// lib/kernel/signal-registry.ts
//
// THE SIGNAL REGISTRY — the declared catalog of every inter-manager signal_type on the bus, exactly
// as manager-registry catalogs every egress burn-domain. The Command Center's whole differentiator is
// that managers COORDINATE; this makes that coordination GOVERNED: every signal a manager publishes is
// declared here with its disposition (does a manager CONSUME it, or is it surfaced for a HUMAN on the
// feed?) and the coordination KIND the feed renders it as. test:signal-integrity then proves zero
// orphans — every published signal_type is catalogued, every "handled" type has a real handler, every
// handler is catalogued, and the declared kind matches the live classifier. Pure data (no I/O).

import type { CoordinationKind } from "./coordination-kind"

export type SignalDisposition = "handled" | "feed_only"

export interface SignalSpec {
  /** the manager(s) whose inbox CONSUMES this signal via SIGNAL_HANDLERS (empty = feed-only). */
  consumers: string[]
  /** "handled" = an automated consumer acts on it; "feed_only" = surfaced for a human on the feed. */
  disposition: SignalDisposition
  /** the coordination kind the feed should render it as (must match classifyCoordination). */
  kind: CoordinationKind
  /** one-line purpose, for the catalog. */
  what: string
}

/**
 * Every inter-manager signal_type, declared. Add a row here when you publish a new signal_type —
 * test:signal-integrity fails on any published type that isn't catalogued (the orphan guard).
 */
export const SIGNAL_REGISTRY: Record<string, SignalSpec> = {
  // ── Handled — an automated manager inbox consumes and acts (gated) ──
  isa_call_appointment:    { consumers: ["shopping_agent", "listing_concierge"], disposition: "handled", kind: "handoff",    what: "AI ISA booked an appointment on a dial-batch call — concierge proposes the prep follow-up" },
  deal_closed:             { consumers: ["sphere_of_influence"],                 disposition: "handled", kind: "update",     what: "a deal closed — the client crosses into lifetime territory; Sphere proposes the welcome" },
  long_horizon_nurture_handoff: { consumers: ["sphere_of_influence"],            disposition: "handled", kind: "handoff",    what: "a lead went a year+ without replying to the ISA — instead of abandoning it the ISA HANDS the long-tail to the Sphere of Influence manager (no reply ≠ no future); Sphere proposes ONE gated light value-touch to keep the relationship warm for whenever they're ready" },
  price_reduced:           { consumers: ["shopping_agent"],                      disposition: "handled", kind: "update",     what: "price drop on an in-house listing — Shopping Agent re-matches buyers who saved it" },
  listing_back_on_market:  { consumers: ["shopping_agent"],                      disposition: "handled", kind: "update",     what: "a deal fell through and the listing is BACK ON MARKET (a contract stage → active transition) — the Listing Concierge tells the Shopping Agent (inventory→demand) to re-engage the buyers who SAVED it with a personal 'back on market, still want it?' nudge (avatar-worthy → Asset Manager reel → Campaign sends). The highest-intent re-marketing moment, which the normal just_listed idempotency silently skipped" },
  listing_stall_reprospect:{ consumers: ["shopping_agent"],                      disposition: "handled", kind: "update",     what: "a listing is STALLING (the early predictor, before any price cut) — the Listing Concierge tells the Shopping Agent (inventory→demand) to re-prospect the buyers who SAVED it with a gated alert (a stall often precedes a price move); the two sides of the team work the stall together instead of a solo seller nudge" },
  seller_intent_hot:       { consumers: ["ai_isa", "listing_concierge"],         disposition: "handled", kind: "update",     what: "a seller's intent went hot — routed for an ISA call + listing concierge prep" },
  content_winner:          { consumers: ["ads_manager"],                         disposition: "handled", kind: "update",     what: "a winning organic post — Ads Manager proposes promoting it (gated paid spend)" },
  video_ready:             { consumers: ["campaign_orchestrator", "ads_manager"],disposition: "handled", kind: "handoff",    what: "a Director video finished — distribute (orchestrator) + promote promotable kinds (ads)" },
  lead_creative_handoff:   { consumers: ["asset_manager"],                       disposition: "handled", kind: "handoff",    what: "the AI ISA qualified a lead and DELEGATES the persona-matched 1:1 intro reel to the Asset Manager (video director) — commissionVideo stages a gated reel from the lead's real facts (book-a-consult QR, compliance gate); nothing auto-publishes" },
  contact_reel_handoff:    { consumers: ["asset_manager"],                       disposition: "handled", kind: "handoff",    what: "the AI ISA re-engages a CONTACT and DELEGATES a TRULY SITUATIONAL reel to the Asset Manager — the reel KIND fits the persona (buyer→explainer / seller→cma / both→market_update / lifetime→anniversary), fronted by the ASSIGNED AGENT's avatar/voice; commissionVideo stages it gated, idempotent per (contact, kind), nothing auto-publishes. Managers delegating, not the ISA making videos itself" },
  buyer_welcome_reel_handoff:{ consumers: ["asset_manager"],                     disposition: "handled", kind: "handoff",    what: "a buyer LEAD just became a CONTACT — the Shopping Agent DELEGATES the very first touch, a personal WELCOME avatar reel (Director 'lead_intro' — a calm 'A Quick Hello' fronted by the ASSIGNED agent), to the Asset Manager; commissionVideo stages it gated, and on completion the existing video-coordination routes contact_outreach_ready → the Campaign Orchestrator's gated 1:1 invite email embedding the reel + the portal CTA, so a newly converted buyer is never dropped between conversion and first contact" },
  seller_conversion_reel_handoff:{ consumers: ["asset_manager"],                 disposition: "handled", kind: "handoff",    what: "an un-converted SELLER (a homeowner who asked 'what's my home worth?' and has a seller-mode portal but hasn't booked a listing consult) — the seller mirror of the buyer welcome reel: the Listing Concierge DELEGATES a personal, value-forward avatar reel (Director 'lead_intro', customer-facing, fronted by the ASSIGNED agent — 'here's what your home could really sell for, let's map your move') to the Asset Manager; staged gated, and on completion the existing video-coordination routes contact_outreach_ready → the Campaign Orchestrator's gated 1:1 email embedding the reel + the seller-mode portal CTA. So a homeowner who showed selling intent is never dropped before they convert. Idempotent per contact" },
  offer_confidence_reel_handoff:{ consumers: ["asset_manager"],                  disposition: "handled", kind: "handoff",    what: "a buyer reached the OFFER-STRATEGY moment (found the one) — alongside the agent's concrete comps-grounded offer plan, the Shopping Agent DELEGATES a personal, number-free 'offer confidence' avatar reel (fronted by the assigned agent — 'you found it, you're ready, here's how we write a strong offer') to the Asset Manager; staged gated, and on completion routes contact_outreach_ready → the Campaign Orchestrator's gated 1:1 email + portal CTA. The analytical plan + the human push, working together to get the buyer to write" },
  lead_outreach_ready:     { consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "a lead's persona intro reel finished — the Campaign Orchestrator proposes ONE gated, 1:1 follow-up EMAIL embedding it (email only: an unconsented lead is never SMS/phone/social and a personalized reel is never broadcast); a human approves before it sends" },
  contact_outreach_ready:  { consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "a CONTACT's situational reel finished — the Asset Manager hands the finished reel to the Campaign Orchestrator (the manager that SENDS it), which proposes ONE gated, 1:1 email embedding the reel + its thumbnail to that client (personal, never a social broadcast — it's their CMA/equity/buyer-match reel); a human approves before send" },
  saved_home_reel_handoff: { consumers: ["asset_manager"],                        disposition: "handled", kind: "handoff",    what: "a home the buyer SAVED changed in a HIGH-EMOTION way (price_drop / back_on_market / coming_soon first-look) — the Shopping Agent DELEGATES to the Asset Manager (video director) to commission a PERSONAL avatar reel from the assigned agent; on completion the existing video-coordination routes contact_outreach_ready → the Campaign Orchestrator SENDS it. Shopping decides → Asset creates → Campaign sends; the ISA never makes the video. No-spam (fires on a REAL change to a home they already engaged), idempotent per (contact,kind)" },
  saved_home_message:      { consumers: ["campaign_orchestrator"],                 disposition: "handled", kind: "update",     what: "a lower-emotion saved-home change (under_contract / new_match / open_house) — the Shopping Agent routes it to the Campaign Orchestrator (the manager that SENDS), which proposes a warm, persona-aware, gated text nudge that drives back to the portal. RealScout sends a generic alert; we send a personal note from the buyer's own agent. No-spam, idempotent per (contact,kind)" },
  testimonial_reel_handoff: { consumers: ["asset_manager"],                        disposition: "handled", kind: "handoff",    what: "a newly-closed / lifetime client left a VIDEO testimonial in their portal — the Sphere of Influence manager DELEGATES to the Asset Manager (video director) to commission a 'testimonial' social-proof reel (Director TestimonialReel) that features the client's clip with brand framing, fronted by the assigned agent; staged GATED (nothing auto-publishes — the agent approves before it goes out), idempotent per contact. Sphere decides → Asset creates → on completion the existing video-coordination hands it to the Campaign Orchestrator to distribute. The social proof no agent has time to produce, made automatically from a real client's words" },
  relocation_referral_request:{ consumers: ["sphere_of_influence"],               disposition: "handled", kind: "handoff",    what: "a RELOCATED lifetime client (left our market — moved away, downsized out of area, entered senior living, etc.) tapped 'help me find a great agent in my new area'. We don't serve that market, but the Sphere Manager (referral-out owner) escalates a HIGH-priority follow-up to place an OUTBOUND agent referral — goodwill that keeps the relationship warm plus a referral fee at close. Fair housing: only the neutral relocation fact is used, never the reason. Idempotent per open request" },
  next_move_intent:        { consumers: ["sphere_of_influence"],                  disposition: "handled", kind: "handoff",    what: "a LIFETIME customer TAPPED a self-directed 'Your Next Move' option in their portal (move up / right-size / invest / refinance / improve / explore) — a client-INITIATED re-transaction intent, the cleanest and most compliant lead signal there is (equity/tenure only, never protected-class targeting). The AI ISA (who hears the client) HANDS it to the Sphere Manager (lifetime relationship owner), who escalates a HIGH-priority follow-up to the responsible agent with the concrete delegated next step (buyer consult + CMA for move-up / finance review for refinance / vendor intro for improve). Turns a passive past-client portal into a re-transaction funnel — idempotent per (contact, intent) within the open window" },
  newsletter_touch_handoff:{ consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "the AI ISA decided a lead/contact's NEXT-BEST touch is the passive newsletter (the nurture downshift — stop pestering with 1:1s, keep value flowing) and HANDS the relationship to the Campaign Orchestrator (the content-channel owner) to ensure enrollment (idempotent; honors unsubscribe + opt-out). Works for both leads and contacts (audience in payload) — managers working together on the newsletter channel" },
  video_compliance_failed: { consumers: ["campaign_orchestrator"],              disposition: "handled", kind: "alert",      what: "a video failed compliance — escalate to the approval queue, never auto-publish" },
  recruit_activated:       { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a recruited agent was provisioned — Deal Coordinator wires them into production tracking" },
  agent_book_reassigned:   { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a departing agent's IN-FLIGHT deals moved to a successor (admin deactivation) — Deal Coordinator alerts the deal-coordination owners to confirm the transaction team so a live deal is never dropped mid-transaction" },
  agent_first_close:       { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "update",     what: "a recruited agent closed their first deal — recruiting ROI's first datapoint + celebrate" },
  agent_crushed_cap:       { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "escalation", what: "a current agent blew past cap — surface as recruiting proof to the broker" },
  agent_stalling:          { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "escalation", what: "a recruited agent is stalling on production — flag for a check-in" },
  deal_autopsy_completed:  { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "alert",      what: "a won/lost-deal autopsy finished — feed the coaching/recruiting learning" },
  license_lapsing:         { consumers: ["compliance_officer"],                  disposition: "handled", kind: "escalation", what: "the Recruiting Manager's license/CE/ethics readiness sweep found an agent with a BLOCKER (expired license, CE short past cycle, or ethics overdue) — a real regulatory exposure if that agent transacts. It HANDS the finding to the Compliance Officer (regulatory owner), who records it in the compliance ledger (compliance_flags) so the exposure is tracked/auditable, not just a transient reminder. Recruiting detects (owns the agents table) → Compliance records — managers working together on a legal-risk item; deduped per open (agent, exposure)" },
  certification_issued:    { consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "the positive mirror of license_lapsing — an agent EARNED a certification (onboarding / specialty credential). The Recruiting Manager (owns certifications) HANDS it to the Campaign Orchestrator (content/social owner), who proposes a GATED 'congrats on your certification' social-proof post fronted by the agent (nothing auto-publishes — the human approves). Turns a compliance/education milestone into a marketing asset no competitor produces; idempotent per cert award (entityId = certId), the agent name sanitized" },
  contact_withdrawn:       { consumers: ["sphere_of_influence"],                 disposition: "handled", kind: "alert",      what: "every channel revoked + no new contact info — mark withdrawn, inform the agent, preserve history" },
  loan_milestone:          { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a financing milestone landed (application → approval → clear-to-close → funded, or denial/delay) — Deal Coordinator keeps the buyer + agent on the same page through the loan: a gated buyer update + an agent prompt; a denial NEVER auto-messages the buyer (the agent calls personally)" },
  transaction_action_pending: { consumers: ["finance_manager", "compliance_officer"], disposition: "handled", kind: "escalation", what: "an URGENT/HIGH closing-orchestration pending action owned by the lender (→ Finance opens a gated task) or a deadline-bearing vendor — title/escrow/inspection (→ Compliance flags the TC + agent). Routed by suggested_recipient; the TC's own buyer/seller items stay in the closing-concierge UI" },
  deal_save_huddle:        { consumers: ["finance_manager", "compliance_officer"], disposition: "handled", kind: "escalation", what: "a deal worsened into at_risk/critical — the Deal Coordinator convenes a huddle routed by the FAILING health component: Finance works the loan side (opens a TC-assigned task), Compliance flags the deadline/contingency exposure; EVERY play keeps the TC + the deal's agent aware (NOT the broker — operational), and earnest money also proposes an URGENT gated buyer warning. The coordinator drives its own docs/title/earnest bucket directly" },
  showing_feedback_routed: { consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "the week's buyer-showing feedback routed a play (price pressure / strong interest / presentation) — concierge proposes a gated seller recommendation (manager-orchestrated, not a passive task)" },
  listing_stall_predicted: { consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "a listing is heading for a stall (DOM past the area's pace, showings drying up, no offers) BEFORE expiry — concierge proposes an early gated marketing-refresh/price-strategy recommendation" },
  home_value_seller_intent:{ consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "a homeowner requested a home value (home-value tool / valuation magnet) — the strongest INBOUND seller signal; concierge proposes a gated precise-CMA follow-up so the team responds like a listing lead, not a lead left in the inbox" },
  buyer_stall_predicted:   { consumers: ["shopping_agent"],                       disposition: "handled", kind: "update",     what: "a buyer has toured a lot with no offer written (fatigue / expectations / drifting away) — the buyer-side counterpart to listing-stall; Shopping Agent proposes a gated reset (recalibrate expectations or re-energize with fresh matches)" },

  // ── Feed-only — surfaced on the Command Center for a HUMAN (no automated consumer by design) ──
  voice_command_dispatched:       { consumers: [], disposition: "feed_only", kind: "handoff",    what: "A HUMAN SPOKE AND THE WORK REACHED THE RIGHT MANAGER. The voice admin's kernel lane decomposes an utterance into capabilities, attributes each to the manager whose charter owns it (CAPABILITY_MANAGER), and dispatches one signal per step — carried onto the bus by the Cron Manager, the operations seat, so the receiving manager is never the sender and who asked is never lost. Dispatched ONLY after the speaker confirmed a mutating step: buildVoicePlan marks those needs_confirmation and a plan is a proposal until a second turn says yes. Feed-only: the manager's own inbox and approval rails already govern what happens next, and a spoken sentence must not bypass them. This is the differentiator a single-assistant product cannot copy — not a missing feature, a missing bus" },
  outcome_contradicted:           { consumers: [], disposition: "feed_only", kind: "alert",      what: "WE SAID IT HAPPENED AND THE PROVIDER SAYS IT DID NOT. Published by the Data Steward (which owns provider truth) to the manager that MADE the claim, when outcome reconciliation flips a touch to 'contradicted' — a Twilio undelivered/failed status on an SMS the OS recorded as sent, a Lob returned_to_sender on a postcard a campaign counted as mailed. Raised ONCE per touch (escalated_at guards it) so a provider re-sending a failure event does not re-raise. Feed-only ON PURPOSE: what to do about a client who never got the message is a relationship judgement — re-send on another channel, call them, or let it go — and automating that behind a broker's back is exactly the over-reach this OS refuses. What IS automatic is that the claim stops reading as true. See lib/outcomes/reconciliation.ts" },
  dsar_filed:                     { consumers: [], disposition: "feed_only", kind: "alert",      what: "A CLIENT EXERCISED A DATA RIGHT FROM THEIR OWN PORTAL AND A STATUTORY CLOCK STARTED. Published by the Data Steward (which owns the contact record the request is about) to the Compliance Officer (the regulatory owner) when a portal user files an access/export or deletion request against THEIR OWN contact record — identity_verified is true at the source because the request came from an authenticated session whose user_id matches the contact, which is a stronger proof than the email round-trip a manual request needs. Feed-only, and the reason matters: a deletion request is NOT self-executing. Records under a brokerage's transaction-retention obligation cannot be erased on request, the scope of an export is a judgement about what belongs to the requester versus the other side of a deal, and an OS that quietly deleted a client's file because a button was pressed would destroy the evidence a regulator later asks for. So the portal FILES the request onto the existing data_subject_requests queue with its due date, the human working that queue decides and acts, and the signal exists so the clock is visible on the feed the day it starts rather than the week it expires" },
  capability_dark:                { consumers: [], disposition: "feed_only", kind: "alert",      what: "an APP CAPABILITY cannot run for this tenant and somebody has to decide what to do about it. Published by the Data Steward (which owns connection integrity, so it is the manager that OBSERVES readiness) to the manager accountable for the capability's domain — CAPABILITY_MANAGER in lib/agentic-os/capability-ownership.ts. Routing is deliberate: a capability the SELF-HEALER already has an open proposal for raises NOTHING (a decision made mid-repair is wrong by the time it lands), a missing PLATFORM credential goes to the Steward because no other manager can light an env key, and only a tenant-connectable gap reaches the owning manager — which is the only one that can choose the workaround (route the touch to another channel, hold the play, tell the human plainly). Feed-only by design: the WORKAROUND is a judgement about a client relationship, not something to automate behind a broker's back. Deduped to one open signal per capability" },
  living_video_stale:             { consumers: [], disposition: "feed_only", kind: "alert",      what: "A DELIVERED VIDEO HAS STARTED SAYING SOMETHING UNTRUE. A living video is one whose content is a claim about facts that move — 'three showings this week', 'listed at $545,000'. Every other CRM ships those as static files that rot from the moment they render, and this OS was no different: requestSellerUpdateReel is gated by a SEVEN-DAY idempotency window, so a price drop on Tuesday reached the seller the following Monday in a video that opens with the old price. m312 stamps a facts_key (deliberately NARROWER than the render cache's frame_key, which covers cosmetics like the QR data url and the photo array and would churn renders for changes nobody cares about) and the sweep re-derives the declared facts each tick — a few indexed reads, no Chromium — and diffs them. Materiality is per-fact and is the judgment that makes this useful rather than annoying: a price or a showing count or the agent's re-recorded AVATAR is always material, days-on-market never is (it ticks daily and would re-send a video about nothing), video scans only past a jump of 25. On a material change the producer stages a replacement with force (the weekly window is a spam guard against the cadence cron, not a rule that a seller lives with a wrong number) and the Asset Manager, which owns the render ledger, hears WHICH fact moved. It never SENDS: the existing gated delivery path and a human approval is what reaches the client, because a system that both judged a video stale and mailed the replacement is one bad fact provider away from spamming a seller" },
  render_determinism_leak:        { consumers: [], disposition: "feed_only", kind: "alert",      what: "A COMPOSITION CAN NEVER REUSE A RENDER. Every Remotion composition in this repo is a pure function of its props (zero Math.random / Date.now / new Date across remotion/**), so identical content should render once and be reused — that is what m310's frame_key/artifact_key cache does. A producer that stamps a per-call value into input_props (an epoch-suffixed URL, a fresh uuid, a full ISO timestamp) poisons the key, so every render is a fresh Chromium bundle + encode while the cache reports a healthy 0% hit rate: the expensive kind of silent failure, because nothing is broken and nothing is saved either. The Cron Manager's sweep (sweepDeterminismLeaks) names the offending prop PATHS and raises them to the Asset Manager, which owns remotion_composition_renders + remotion_compositions. Feed-only on purpose: the fix is a code change in the producer, not something an inbox can apply — and the brief says exactly which path to move. Deduped per (brokerage, composition) on a 7-day window so a standing leak does not re-raise every cron tick. Deliberately conservative about dates: a plain 'week of 2026-07-27' is CONTENT and is never flagged, because a detector that cries wolf gets ignored" },
  creative_fatigue:               { consumers: [], disposition: "feed_only", kind: "alert",      what: "an ad creative's performance is fatiguing — refresh advised" },
  budget_rebalance:               { consumers: [], disposition: "feed_only", kind: "update",      what: "the ad outcome loop found a >=2x CPL gap between live campaigns — a GATED budget-shift proposal (a human approves before money moves; deduped 14d per campaign pair)" },
  deadline_conflict_finding:      { consumers: [], disposition: "feed_only", kind: "alert",       what: "the document kernel's deadline derivation hit AMBER: a scanned document's date conflicts with a tracked transaction deadline (or supports one the scan wasn't confident enough to auto-track) — a GATED review proposal with the policy_decisions evidence, resolved ONE-CLICK on the Command Center feed (adopt the document's date / keep the tracked one — resolveDeadlineConflictAction records the human decision back into policy_decisions + consumed_action); the kernel never silently moves a date a human or another rail recorded (deduped 14d per transaction+deadline pair)" },
  stage_advance_candidate:        { consumers: [], disposition: "feed_only", kind: "handoff",     what: "document kernel Phase B: a scanned document's arrival asserts the deal has MOVED (inspection report during INSPECTION, appraisal report during APPRAISAL, closing disclosure during FINANCING_PENDING, EM receipt during UNDER_CONTRACT) — the kernel consulted the REAL canAdvanceStage gate first (blocked candidates record a red policy decision instead of signaling) and proposes the advance for one-click human approval on the feed; approveStageAdvanceAction drives the SAME advanceStage engine as the manual click (state machine + critical milestones + compliance gates hold — no kernel bypass), deduped 14d per transaction+stage pair" },
  autonomy_ratchet_proposal:      { consumers: [], disposition: "feed_only", kind: "update",      what: "THE POLICY AUTONOMY RATCHET — autonomy is EARNED per brokerage from its OWN approval history: when one amber deadline shape (e.g. 'correct the closing date from a scanned CD') has been human-approved >=10 times with ZERO declines in policy_decisions, the Deal Coordinator proposes — TO THE BROKER (broker/admin-only resolution, refused by voice) — raising that ONE shape to green for their tenancy. Grant lands in managed_agents.config.doc_kernel_grants (the SAME policy surface the autonomy-gate/Trust Scorecard govern); the deriver then acts autonomously on that shape, recording green auto_adopted_granted/auto_tracked_granted rows — the ledger trail never thins. A single decline resets trust; declined proposals dedupe 30d; stage advances NEVER ratchet (business-visible state stays human forever); legal gates (consent/FH/TCPA) are untouchable by design. Swept on the deadline-watcher cron. GENERALIZED to the marketing lanes: social_post:<post_type> shapes (>=20 straight human approvals on AI-staged posts, zero rejections — higher bar, outward-facing brand) propose the same way, granted into campaign_orchestrator's marketing_grants; the cadence then stages that shape approved+scheduled while the manager's autonomy POSTURE and every dispatch gate still override. The Earned Autonomy panel (Command Center) lists all grants with evidence + revoke" },
  partner_agreement_lapsing:      { consumers: [], disposition: "feed_only", kind: "escalation",  what: "a referral partner's agreement_end_date lapsed or ends within the 30d renewal window — a silently-expired referral fee agreement is a commission-dispute exposure when the next referral arrives. The Sphere (partner-relationship owner) escalates ONE gated renewal per partner (open-signal dedupe) + notifies the owning agent; nothing auto-renews or auto-contacts the partner. Rides the referral-asks cron beside the reciprocity tracker" },
  first_touch_deferred:           { consumers: [], disposition: "feed_only", kind: "deferral",   what: "a manager yielded the first touch to another (soft dissent — 'you've got this')" },
  deferral_stall_nudge:           { consumers: [], disposition: "feed_only", kind: "deferral",   what: "a deferred touch has stalled past its window — nudge to pick it back up" },
  relist_recovery:                { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a listing expired/withdrawn — the Listing Concierge routes the ACUTE re-list call to the AI ISA, which picks it up via the canonical consent-gated contact engagement (the seller re-launch message already went out separately)" },
  offer_rejection_recovery:       { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a buyer's offer was rejected — the Shopping Agent routes the ACUTE same-day regroup call to the AI ISA, which picks it up via the canonical consent-gated contact engagement" },
  rate_lock_watch:                { consumers: ["finance_manager"],            disposition: "handled",   kind: "handoff",    what: "a financing client's rate lock is expiring vs the closing date — Finance opens a gated drive-to-done task to confirm an extension/relock before the rate (or the deal) is lost" },
  reverse_prospecting_call_candidate:{ consumers: ["ai_isa"], disposition: "handled", kind: "handoff", what: "an MLS reverse-prospecting match (a new listing fits a saved buyer) — the Shopping Agent routes the call candidate to the AI ISA, which picks it up via the canonical consent-gated contact engagement (strike while the listing is fresh)" },
  open_house_lead_handoff:        { consumers: ["ai_isa"], disposition: "handled", kind: "handoff", what: "the hot, unrepresented buyer leads from a Listing Concierge open house — handed to the AI ISA, which now PICKS THEM UP and qualifies each (consent-gated contact engagement) instead of the leads dying as a dashboard count; the seller-event → buyer-pipeline bridge" },
  stale_preapproval_reengage:     { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a pre-approval went stale (no active deal) — the Shopping Agent routes the EXPIRED case to the AI ISA for a re-qualification call, picked up via the canonical consent-gated contact engagement" },
  client_welcome_co_owned:        { consumers: [], disposition: "feed_only", kind: "update",     what: "ONE WELCOME EMAIL, TWO MANAGERS ON THE FILE. Owner ruling, verbatim: \"the welcome email is picked up by the listing concierge if it is a seller, shopping agent for a buyer, both listing concierge and shopping agent for both seller and buyer, sphere if lifetime.\" A contact_type of 'both' is the only case that names TWO managers, and `agent_client_messages.agent_kind` is a single text column (verified live — no array, no join table), so the ledger row and the governed send carry the FIRST manager (listing_concierge: a dual-sided move starts with the home they already own) and this signal is how the SECOND one picks the same welcome up. Published by lib/kernel/client-welcome.ts the moment the ledger row exists — NOT after a successful send, because a co-owner who only hears about the welcomes that went out cannot notice the ones the autonomy gate held. The route listing_concierge → shopping_agent is already a DECLARED collaboration edge (MANAGER_COLLABORATIONS.listing_demand_bridge), so nothing about the governance model is new here; what was missing was a second welcome-owner, not a second rail. FEED-ONLY ON PURPOSE, and this is the honest disposition rather than the convenient one: the welcome itself has already been authored, gated and sent under the owning manager, so there is no automated act left for the co-owner to perform — what they need is to KNOW, on the day, that this client is on their desk too. The move-up coordination that follows once there is a listing and a search to line up is `dual_transaction_timing`, which is a different question asked later" },
  referral_reciprocity:           { consumers: [], disposition: "feed_only", kind: "update",     what: "a referral partner is owed reciprocity — surface the give-back" },
  channel_order_recommendation:   { consumers: [], disposition: "feed_only", kind: "update",     what: "the learned best lead channel for this brokerage (advisory)" },
  copy_variant_promoted:          { consumers: [], disposition: "feed_only", kind: "update",     what: "an A/B copy variant won on reply rate and was promoted" },
  health_lifecycle_play:          { consumers: [], disposition: "feed_only", kind: "update",     what: "a decaying relationship routed to the right manager for a re-engagement play" },
  second_opinion_requested:       { consumers: [], disposition: "feed_only", kind: "update",     what: "a strategic play asked a second manager for a complementary read (the huddle)" },
  source_allocation_advice:       { consumers: [], disposition: "feed_only", kind: "update",     what: "lead-source enable/disable advice from real conversion + ROI" },
  source_lifetime_health_advice:  { consumers: [], disposition: "feed_only", kind: "update",     what: "lead-source lifetime-quality advice (relationships that LAST, not just first close)" },
  voice_action:                   { consumers: [], disposition: "feed_only", kind: "update",     what: "the VOICE ADMIN executed a spoken action (task / activity / client message) — the owning manager records it on the bus so every voice command is visible + accountable in the Command Center, exactly like the text command bar" },
  repurpose_shorts_handoff:       { consumers: ["asset_manager"], disposition: "handled", kind: "handoff", what: "Campaign Orchestrator → Asset Manager: a broadcast marketing reel is done and being distributed — AUTONOMOUSLY cut platform SHORTS from it. The Asset Manager re-commissions the same content as vertical reels (tiktok/instagram) for the social channels the primary didn't cover, through the Director/commissionVideo pipeline (real render + bookends + QR + gating). Replaces the old manual snippets/repurpose UI process with a managed, on-the-bus decision" },
  campaign_recovered:             { consumers: [], disposition: "feed_only", kind: "update",     what: "the Campaign Orchestrator AUTONOMOUSLY caught a stalled campaign (an already-approved 'scheduled' launch that never fired) and RE-LAUNCHED it through the compliance-gated publisher — the agent never had to redo the work. Surfaced in the Command Center's managers-talking feed so the team sees marketing never falls through the cracks" },
  win_story:                      { consumers: [], disposition: "feed_only", kind: "update",     what: "a farm-area win worth telling the neighborhood (social proof)" },
  trid_disclosure_clock:          { consumers: [], disposition: "feed_only", kind: "update",     what: "a TRID disclosure clock is ticking on a deal — keep the timeline honest" },
  journey_conformance_violation:  { consumers: [], disposition: "feed_only", kind: "alert",      what: "a contact's journey drifted off its required path — flag for review" },
  net_sheet_surprise:             { consumers: [], disposition: "feed_only", kind: "alert",      what: "a net-sheet figure shifted enough to surprise the seller — get ahead of it" },
  wire_fraud_risk:                { consumers: [], disposition: "feed_only", kind: "update",     what: "a wire-fraud risk signal on a closing — verify before any funds move" },
  document_compliance_finding:    { consumers: [], disposition: "feed_only", kind: "alert",      what: "a document-compliance audit finding needs a human's eyes" },
  regulatory_change_detected:     { consumers: [], disposition: "feed_only", kind: "alert",      what: "a real-estate regulatory change was detected that touches the gates" },
  license_risk_escalated:         { consumers: [], disposition: "feed_only", kind: "escalation", what: "an AI-sentinel license/authority risk escalated for review" },
  launch_war_room_convened:       { consumers: [], disposition: "feed_only", kind: "escalation", what: "a listing launch war-room convened the team" },
  deal_play_prep_ready:           { consumers: [], disposition: "feed_only", kind: "handoff",    what: "Deal Play hop 1: Listing Concierge staged the launch -> Asset Manager cuts the reel (narration; artifacts gated)" },
  deal_play_reel_ready:           { consumers: [], disposition: "feed_only", kind: "handoff",    what: "Deal Play hop 2: Asset Manager staged the promo reel -> Campaign Orchestrator takes the campaign" },
  deal_play_campaign_ready:       { consumers: [], disposition: "feed_only", kind: "handoff",    what: "Deal Play hop 3: Campaign Orchestrator staged the channel drafts -> Ads Manager proposes the paid push" },
  deal_play_ads_ready:            { consumers: [], disposition: "feed_only", kind: "handoff",    what: "Deal Play hop 4: Ads Manager staged the ad drafts -- the play is staged end to end, one review to launch" },
  fire_drill_opened:              { consumers: [], disposition: "feed_only", kind: "escalation", what: "a fire-drill opened — the team converges on an urgent situation" },
  farm_play_convened:             { consumers: [], disposition: "feed_only", kind: "escalation", what: "a farm play convened the managers around a neighborhood opportunity" },
  bidding_war_convened:           { consumers: [], disposition: "feed_only", kind: "escalation", what: "a bidding-war concierge convened the team around multiple offers" },
  first_touch_claimed:            { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a manager claimed the first touch on a new lead (the bullpen race resolved)" },
  dual_transaction_timing:        { consumers: [], disposition: "feed_only", kind: "update",     what: "MOVE-UP coordination — a 'both' contact selling their current home AND buying the next; the Listing Concierge ↔ Shopping Agent timing play (ramp the buyer search as the sale closes, prep a sale-contingent offer, or align close dates) made visible on the bus so the two sides never drift out of sync" },
  stage_stalled:                  { consumers: [], disposition: "feed_only", kind: "update",     what: "a contact has sat in a legal lifecycle stage TOO LONG with nothing in motion (the quiet failure journey-conformance's illegal-transition check misses) — surfaced to the manager who owns that stage (AI ISA / Shopping Agent / Listing Concierge / Deal Coordinator) by dwell-vs-ceiling" },
  listing_marketing_ready:        { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a listing reached coming-soon or went live — the Listing Concierge → Campaign Orchestrator marketing handoff, made visible on the bus (the kernel-event fanout still enrolls the sequences; this makes the team coordination legible)" },
  offer_docs_ready:               { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a signed offer packet passed the completeness scan (all required forms present + signed) — the Deal Coordinator handoff that the docs are verified and ready to send to the listing agent (the agent is also notified)" },
  seller_update_reel_handoff:     { consumers: ["asset_manager"], disposition: "handled", kind: "handoff", what: "Listing Concierge → Asset Manager: commission an active listing's WEEKLY seller-update avatar reel (the agent's D-ID + ElevenLabs talking-head summarizing showings, buyer interest, days-on-market, price position). The Asset Manager CREATES the reel; on completion the Campaign Orchestrator DELIVERS it — the seller video now rides the manager bus (decide → create → send) instead of a monolithic cron" },
  seller_update_ready:            { consumers: ["campaign_orchestrator"], disposition: "handled", kind: "handoff", what: "Asset Manager → Campaign Orchestrator: a brokerage's finished seller-update reels are ready — propose each to its seller through the gate (audience='seller', listing_concierge voice), and on approval materialize the rich listing-dashboard video card. The SEND half of the Listing Concierge → Asset Manager → Campaign Orchestrator chain" },
  offers_compare_handoff:              { consumers: ["listing_concierge"], disposition: "handled", kind: "handoff", what: "Data Steward → Listing Concierge: an offer received on an IN-HOUSE listing (uploaded or emailed in, then AI-read) finished EXTRACTION — the now-comparison-ready offer (real price + terms) is handed to the Listing Concierge to run the net-sheet comparison NOW (single or multi) and propose the gated seller summary + portal card ranked by what the seller KEEPS, not sticker price. Event-driven on extraction completion; the */15 offer-net-sheet cron stays as the brokerage-wide safety net. (NOT the Deal Coordinator — that manager only owns transactions, post-compliance-gate)" },
  agent_overloaded:               { consumers: [], disposition: "feed_only", kind: "escalation", what: "capacity guardian flagged an agent's load — surfaced for the broker (advisory)" },
  nothing_dropped_digest:         { consumers: [], disposition: "feed_only", kind: "update", what: "the NOTHING-DROPPED sweep found balls in the air. Declared UPDATE, matching classifyCoordination rather than forcing a pattern into it: an escalation means 'needs human attention NOW', and a once-a-day standing ranked list is not that — rendering a routine digest as an emergency is how a feed teaches people to scroll past the real ones. The runner unifies the five lanes nothing else unifies — pending showings, approvals awaiting a human, unconsumed manager signals, never-touched leads, and leads whose next push is overdue — and had never been computed against a live tenant because it had no caller. Published by /api/cron/nothing-dropped-sweep (wave 26), campaign_orchestrator → data_steward, at most one per brokerage per UTC day, with the ranked top-N carried on the payload. FEED-ONLY BY DESIGN: every entry already belongs to a lane that owns its own remediation, so a handler here would either duplicate that lane's action or invent a second owner for it — the digest exists so a human sees the five lanes AT ONCE, which no single lane can show. Contacts and transactions are deliberately out of scope; the stale-contact monitor and the deadline watcher own those" },
  geo_visibility_gap:             { consumers: ["campaign_orchestrator"], disposition: "handled", kind: "update", what: "the GEO loop closed — a published lead-magnet/FAQ landing page has been checked enough times across enough days by AI search and is STILL never cited (persistently invisible); the Campaign Orchestrator PROPOSES a one-tap gated regenerate_faq action (rebuild the FAQ + schema.org block from fresh demand topics) so monitoring becomes remediation a human approves, not just a number" },
  lead_magnet_handoff:            { consumers: [], disposition: "feed_only", kind: "handoff",     what: "a lead-magnet conversion routed to the right manager by INTENT — a buyer guide / listing alert / open-house RSVP hands the new buyer lead to the Shopping Agent; a seller guide / market report hands the seller lead to the Listing Concierge (a home-value request gets the stronger precise-CMA handoff instead). The kernel also stamps the contact's intent so the portal view + education match; the gated lead-magnet sequence provides the follow-up touches" },
  lead_source_waste:              { consumers: ["campaign_orchestrator"], disposition: "handled", kind: "update", what: "the lead-source learner closed its loop — a scrape source is a proven money-pit (trusted ROI below the floor) or a proven winner that's off; the Campaign Orchestrator proposes a one-tap GATED reallocate_lead_sources action (turn the winners on / the money-pits off for that market's enabled_sources) a human approves. Never acts on thin samples" },

  // ── Round-34 CROSS-MANAGEMENT: the first-class governed referral ──
  cross_manager_referral:         { consumers: ["deal_coordinator", "cron_manager", "shopping_agent", "listing_concierge", "sphere_of_influence", "campaign_orchestrator", "marketing_agent", "asset_manager", "ads_manager", "ai_isa", "data_steward", "recruiting_manager", "compliance_officer", "finance_manager"], disposition: "handled", kind: "update", what: "CROSS-MANAGEMENT REFERRAL — a manager's sweep found something inside a PEER's domain and raises it INTO that domain through the bus (owner: 'managers should be working together and can cross manage'). Governed, not a free-for-all: the shared handler consults MANAGER_COLLABORATIONS (manager-registry) and REFUSES any from→to pair outside a declared collaboration edge, recording the refusal as the consumed action; a declared referral is accepted and surfaced as a prioritized follow-up to the supervising principals, with who-asked-whom-for-what + state visible on the managers governance surface. Every registered manager can RECEIVE a referral (one shared handler per inbox key). First live emitter: the Cron Manager's approval-queue SLA sweep referring >48h-aging approval kinds to their owning managers (approval_queue_slo domain); payload carries collab_domain + ask; recency-deduped per (to_manager, queue kind) so a standing breach never spams" },

  // ── Round-24 platform rails on the governed bus (outbound webhooks / affiliate accrual / custom domains) ──
  webhook_endpoint_dead:          { consumers: [], disposition: "feed_only", kind: "alert",  what: "a tenant's OUTBOUND webhook endpoint went DEAD — a signed delivery exhausted all 5 POST attempts (the backoff ladder is done, the row is dead, the subscription's failure_count bumped). Feed-only BY DESIGN: the only real fix lives on the subscriber's OWN server (fix the endpoint, then re-test from Settings → API & Webhooks), so there is no governed in-OS deliverable a manager could propose — a handler here would be a dead promise. The Data Steward (tenant_webhook_* table owner) announces it to the Cron Manager (loop-health owner); idempotent per open (subscription) via the bus dedupe. Every failed attempt ALSO ledgers self_heal_events (flow webhook_delivery) so the repair digest ranks flaky endpoints" },
  affiliate_commission_accrued:   { consumers: [], disposition: "feed_only", kind: "update", what: "the monthly affiliate-accrual cron (finance_manager-owned) wrote a commission event — the PLATFORM accrued its external referral partner's cut of this workspace's MRR for the period (platform-funded; never billed to the tenant). manager_signals is tenant-anchored (brokerage_id NOT NULL), so the run's outcome rides the bus per referred tenant, with the RUN summary (accrued count + total cents) carried in the payload. Feed-only: the money already moved on the ledger (affiliate_commission_events, UNIQUE(referral_id, period) — idempotent), there is nothing for an automated consumer to do; idempotent per commission-event id" },
  custom_domain_verified:         { consumers: [], disposition: "feed_only", kind: "update", what: "a white-label custom domain flipped to ACTIVE — Vercel verified it and the tenant's storefront now serves on their own domain. The Data Steward (tenant_custom_domains owner) announces the completed state change to the Marketing Manager (brand owner). Feed-only: the transition is already done, nothing to consume; idempotent per open (domain row) via the bus dedupe" },
  custom_domain_error:            { consumers: [], disposition: "feed_only", kind: "alert",  what: "a white-label custom domain hit an ERROR during registration/verification (bad DNS, domain owned by another Vercel account, Vercel API failure) — surfaced feed-only so the HUMAN fixes DNS/ownership at their registrar and re-runs Check status: nothing in-OS can change third-party DNS, so no automated consumer exists by design. Vercel API failures ALSO ledger self_heal_events (flow custom_domain_vercel); idempotent per open (domain row) via the bus dedupe" },

  // ── Manual CRM sync-out (Connection Center "Sync now") — Data Steward → Sphere ──
  contact_crm_synced:             { consumers: [], disposition: "feed_only", kind: "update", what: "the Data Steward pushed a contact OUT to the connected CRM via a MANUAL 'Sync a contact now' (sync-out only — nothing syncs back in). Announced to the Sphere Manager (lifetime-relationship owner) so the Command Center feed shows the record was mirrored to the external CRM. Feed-only: the push already completed, nothing for an automated consumer to do — and the AUTONOMOUS per-update sync stays silent to avoid feed spam, so ONLY the human-triggered manual sync surfaces here. Idempotent per (contact) via the bus dedupe" },
}

/** Look up a signal's spec (undefined = uncatalogued, which test:signal-integrity fails on). */
export function signalSpec(signalType: string): SignalSpec | undefined {
  return SIGNAL_REGISTRY[signalType]
}

/** Every catalogued signal_type.
 *  CENSUS NOTE: guard-consumed — scripts/signal-integrity-simulator.ts:20 (guard chain). */
export function registeredSignalTypes(): string[] {
  return Object.keys(SIGNAL_REGISTRY)
}
