// lib/kernel/signal-registry.ts
//
// THE SIGNAL REGISTRY — the declared catalog of every inter-manager signal_type on the bus, exactly
// as manager-registry catalogs every egress burn-domain. The Command Center's whole differentiator is
// that managers COORDINATE; this makes that coordination GOVERNED: every signal a manager publishes is
// declared here with its disposition (does a manager CONSUME it, or is it surfaced for a HUMAN on the
// feed?) and the coordination KIND the feed renders it as. test:signal-integrity then proves zero
// orphans — every published signal_type is catalogued, every "handled" type has a real handler, every
// handler is catalogued, and the declared kind matches the live classifier. Pure data (no I/O).

import type { CoordinationKind } from "./coordination-kind"

export type SignalDisposition = "handled" | "feed_only"

export interface SignalSpec {
  /** the manager(s) whose inbox CONSUMES this signal via SIGNAL_HANDLERS (empty = feed-only). */
  consumers: string[]
  /** "handled" = an automated consumer acts on it; "feed_only" = surfaced for a human on the feed. */
  disposition: SignalDisposition
  /** the coordination kind the feed should render it as (must match classifyCoordination). */
  kind: CoordinationKind
  /** one-line purpose, for the catalog. */
  what: string
}

/**
 * Every inter-manager signal_type, declared. Add a row here when you publish a new signal_type —
 * test:signal-integrity fails on any published type that isn't catalogued (the orphan guard).
 */
export const SIGNAL_REGISTRY: Record<string, SignalSpec> = {
  // ── Handled — an automated manager inbox consumes and acts (gated) ──
  isa_call_appointment:    { consumers: ["shopping_agent", "listing_concierge"], disposition: "handled", kind: "handoff",    what: "AI ISA booked an appointment on a dial-batch call — concierge proposes the prep follow-up" },
  deal_closed:             { consumers: ["sphere_of_influence"],                 disposition: "handled", kind: "update",     what: "a deal closed — the client crosses into lifetime territory; Sphere proposes the welcome" },
  long_horizon_nurture_handoff: { consumers: ["sphere_of_influence"],            disposition: "handled", kind: "handoff",    what: "a lead went a year+ without replying to the ISA — instead of abandoning it the ISA HANDS the long-tail to the Sphere of Influence manager (no reply ≠ no future); Sphere proposes ONE gated light value-touch to keep the relationship warm for whenever they're ready" },
  price_reduced:           { consumers: ["shopping_agent"],                      disposition: "handled", kind: "update",     what: "price drop on an in-house listing — Shopping Agent re-matches buyers who saved it" },
  listing_stall_reprospect:{ consumers: ["shopping_agent"],                      disposition: "handled", kind: "update",     what: "a listing is STALLING (the early predictor, before any price cut) — the Listing Concierge tells the Shopping Agent (inventory→demand) to re-prospect the buyers who SAVED it with a gated alert (a stall often precedes a price move); the two sides of the team work the stall together instead of a solo seller nudge" },
  seller_intent_hot:       { consumers: ["ai_isa", "listing_concierge"],         disposition: "handled", kind: "update",     what: "a seller's intent went hot — routed for an ISA call + listing concierge prep" },
  content_winner:          { consumers: ["ads_manager"],                         disposition: "handled", kind: "update",     what: "a winning organic post — Ads Manager proposes promoting it (gated paid spend)" },
  video_ready:             { consumers: ["campaign_orchestrator", "ads_manager"],disposition: "handled", kind: "handoff",    what: "a Director video finished — distribute (orchestrator) + promote promotable kinds (ads)" },
  lead_creative_handoff:   { consumers: ["asset_manager"],                       disposition: "handled", kind: "handoff",    what: "the AI ISA qualified a lead and DELEGATES the persona-matched 1:1 intro reel to the Asset Manager (video director) — commissionVideo stages a gated reel from the lead's real facts (book-a-consult QR, compliance gate); nothing auto-publishes" },
  contact_reel_handoff:    { consumers: ["asset_manager"],                       disposition: "handled", kind: "handoff",    what: "the AI ISA re-engages a CONTACT and DELEGATES a TRULY SITUATIONAL reel to the Asset Manager — the reel KIND fits the persona (buyer→explainer / seller→cma / both→market_update / lifetime→anniversary), fronted by the ASSIGNED AGENT's avatar/voice; commissionVideo stages it gated, idempotent per (contact, kind), nothing auto-publishes. Managers delegating, not the ISA making videos itself" },
  buyer_welcome_reel_handoff:{ consumers: ["asset_manager"],                     disposition: "handled", kind: "handoff",    what: "a buyer LEAD just became a CONTACT — the Shopping Agent DELEGATES the very first touch, a personal WELCOME avatar reel (Director 'lead_intro' — a calm 'A Quick Hello' fronted by the ASSIGNED agent), to the Asset Manager; commissionVideo stages it gated, and on completion the existing video-coordination routes contact_outreach_ready → the Campaign Orchestrator's gated 1:1 invite email embedding the reel + the portal CTA, so a newly converted buyer is never dropped between conversion and first contact" },
  offer_confidence_reel_handoff:{ consumers: ["asset_manager"],                  disposition: "handled", kind: "handoff",    what: "a buyer reached the OFFER-STRATEGY moment (found the one) — alongside the agent's concrete comps-grounded offer plan, the Shopping Agent DELEGATES a personal, number-free 'offer confidence' avatar reel (fronted by the assigned agent — 'you found it, you're ready, here's how we write a strong offer') to the Asset Manager; staged gated, and on completion routes contact_outreach_ready → the Campaign Orchestrator's gated 1:1 email + portal CTA. The analytical plan + the human push, working together to get the buyer to write" },
  lead_outreach_ready:     { consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "a lead's persona intro reel finished — the Campaign Orchestrator proposes ONE gated, 1:1 follow-up EMAIL embedding it (email only: an unconsented lead is never SMS/phone/social and a personalized reel is never broadcast); a human approves before it sends" },
  contact_outreach_ready:  { consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "a CONTACT's situational reel finished — the Asset Manager hands the finished reel to the Campaign Orchestrator (the manager that SENDS it), which proposes ONE gated, 1:1 email embedding the reel + its thumbnail to that client (personal, never a social broadcast — it's their CMA/equity/buyer-match reel); a human approves before send" },
  saved_home_reel_handoff: { consumers: ["asset_manager"],                        disposition: "handled", kind: "handoff",    what: "a home the buyer SAVED changed in a HIGH-EMOTION way (price_drop / back_on_market / coming_soon first-look) — the Shopping Agent DELEGATES to the Asset Manager (video director) to commission a PERSONAL avatar reel from the assigned agent; on completion the existing video-coordination routes contact_outreach_ready → the Campaign Orchestrator SENDS it. Shopping decides → Asset creates → Campaign sends; the ISA never makes the video. No-spam (fires on a REAL change to a home they already engaged), idempotent per (contact,kind)" },
  saved_home_message:      { consumers: ["campaign_orchestrator"],                 disposition: "handled", kind: "update",     what: "a lower-emotion saved-home change (under_contract / new_match / open_house) — the Shopping Agent routes it to the Campaign Orchestrator (the manager that SENDS), which proposes a warm, persona-aware, gated text nudge that drives back to the portal. RealScout sends a generic alert; we send a personal note from the buyer's own agent. No-spam, idempotent per (contact,kind)" },
  newsletter_touch_handoff:{ consumers: ["campaign_orchestrator"],               disposition: "handled", kind: "handoff",    what: "the AI ISA decided a lead/contact's NEXT-BEST touch is the passive newsletter (the nurture downshift — stop pestering with 1:1s, keep value flowing) and HANDS the relationship to the Campaign Orchestrator (the content-channel owner) to ensure enrollment (idempotent; honors unsubscribe + opt-out). Works for both leads and contacts (audience in payload) — managers working together on the newsletter channel" },
  video_compliance_failed: { consumers: ["campaign_orchestrator"],              disposition: "handled", kind: "alert",      what: "a video failed compliance — escalate to the approval queue, never auto-publish" },
  recruit_activated:       { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a recruited agent was provisioned — Deal Coordinator wires them into production tracking" },
  agent_book_reassigned:   { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a departing agent's IN-FLIGHT deals moved to a successor (admin deactivation) — Deal Coordinator alerts the deal-coordination owners to confirm the transaction team so a live deal is never dropped mid-transaction" },
  agent_first_close:       { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "update",     what: "a recruited agent closed their first deal — recruiting ROI's first datapoint + celebrate" },
  agent_crushed_cap:       { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "escalation", what: "a current agent blew past cap — surface as recruiting proof to the broker" },
  agent_stalling:          { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "escalation", what: "a recruited agent is stalling on production — flag for a check-in" },
  deal_autopsy_completed:  { consumers: ["recruiting_manager"],                  disposition: "handled", kind: "alert",      what: "a won/lost-deal autopsy finished — feed the coaching/recruiting learning" },
  contact_withdrawn:       { consumers: ["sphere_of_influence"],                 disposition: "handled", kind: "alert",      what: "every channel revoked + no new contact info — mark withdrawn, inform the agent, preserve history" },
  loan_milestone:          { consumers: ["deal_coordinator"],                    disposition: "handled", kind: "update",     what: "a financing milestone landed (application → approval → clear-to-close → funded, or denial/delay) — Deal Coordinator keeps the buyer + agent on the same page through the loan: a gated buyer update + an agent prompt; a denial NEVER auto-messages the buyer (the agent calls personally)" },
  transaction_action_pending: { consumers: ["finance_manager", "compliance_officer"], disposition: "handled", kind: "escalation", what: "an URGENT/HIGH closing-orchestration pending action owned by the lender (→ Finance opens a gated task) or a deadline-bearing vendor — title/escrow/inspection (→ Compliance flags the TC + agent). Routed by suggested_recipient; the TC's own buyer/seller items stay in the closing-concierge UI" },
  deal_save_huddle:        { consumers: ["finance_manager", "compliance_officer"], disposition: "handled", kind: "escalation", what: "a deal worsened into at_risk/critical — the Deal Coordinator convenes a huddle routed by the FAILING health component: Finance works the loan side (opens a TC-assigned task), Compliance flags the deadline/contingency exposure; EVERY play keeps the TC + the deal's agent aware (NOT the broker — operational), and earnest money also proposes an URGENT gated buyer warning. The coordinator drives its own docs/title/earnest bucket directly" },
  showing_feedback_routed: { consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "the week's buyer-showing feedback routed a play (price pressure / strong interest / presentation) — concierge proposes a gated seller recommendation (manager-orchestrated, not a passive task)" },
  listing_stall_predicted: { consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "a listing is heading for a stall (DOM past the area's pace, showings drying up, no offers) BEFORE expiry — concierge proposes an early gated marketing-refresh/price-strategy recommendation" },
  home_value_seller_intent:{ consumers: ["listing_concierge"],                   disposition: "handled", kind: "update",     what: "a homeowner requested a home value (home-value tool / valuation magnet) — the strongest INBOUND seller signal; concierge proposes a gated precise-CMA follow-up so the team responds like a listing lead, not a lead left in the inbox" },
  buyer_stall_predicted:   { consumers: ["shopping_agent"],                       disposition: "handled", kind: "update",     what: "a buyer has toured a lot with no offer written (fatigue / expectations / drifting away) — the buyer-side counterpart to listing-stall; Shopping Agent proposes a gated reset (recalibrate expectations or re-energize with fresh matches)" },

  // ── Feed-only — surfaced on the Command Center for a HUMAN (no automated consumer by design) ──
  creative_fatigue:               { consumers: [], disposition: "feed_only", kind: "alert",      what: "an ad creative's performance is fatiguing — refresh advised" },
  first_touch_deferred:           { consumers: [], disposition: "feed_only", kind: "deferral",   what: "a manager yielded the first touch to another (soft dissent — 'you've got this')" },
  deferral_stall_nudge:           { consumers: [], disposition: "feed_only", kind: "deferral",   what: "a deferred touch has stalled past its window — nudge to pick it back up" },
  relist_recovery:                { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a listing expired/withdrawn — the Listing Concierge routes the ACUTE re-list call to the AI ISA, which picks it up via the canonical consent-gated contact engagement (the seller re-launch message already went out separately)" },
  offer_rejection_recovery:       { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a buyer's offer was rejected — the Shopping Agent routes the ACUTE same-day regroup call to the AI ISA, which picks it up via the canonical consent-gated contact engagement" },
  rate_lock_watch:                { consumers: ["finance_manager"],            disposition: "handled",   kind: "handoff",    what: "a financing client's rate lock is expiring vs the closing date — Finance opens a gated drive-to-done task to confirm an extension/relock before the rate (or the deal) is lost" },
  reverse_prospecting_call_candidate:{ consumers: ["ai_isa"], disposition: "handled", kind: "handoff", what: "an MLS reverse-prospecting match (a new listing fits a saved buyer) — the Shopping Agent routes the call candidate to the AI ISA, which picks it up via the canonical consent-gated contact engagement (strike while the listing is fresh)" },
  open_house_lead_handoff:        { consumers: ["ai_isa"], disposition: "handled", kind: "handoff", what: "the hot, unrepresented buyer leads from a Listing Concierge open house — handed to the AI ISA, which now PICKS THEM UP and qualifies each (consent-gated contact engagement) instead of the leads dying as a dashboard count; the seller-event → buyer-pipeline bridge" },
  stale_preapproval_reengage:     { consumers: ["ai_isa"], disposition: "handled", kind: "handoff",    what: "a pre-approval went stale (no active deal) — the Shopping Agent routes the EXPIRED case to the AI ISA for a re-qualification call, picked up via the canonical consent-gated contact engagement" },
  referral_reciprocity:           { consumers: [], disposition: "feed_only", kind: "update",     what: "a referral partner is owed reciprocity — surface the give-back" },
  channel_order_recommendation:   { consumers: [], disposition: "feed_only", kind: "update",     what: "the learned best lead channel for this brokerage (advisory)" },
  copy_variant_promoted:          { consumers: [], disposition: "feed_only", kind: "update",     what: "an A/B copy variant won on reply rate and was promoted" },
  health_lifecycle_play:          { consumers: [], disposition: "feed_only", kind: "update",     what: "a decaying relationship routed to the right manager for a re-engagement play" },
  second_opinion_requested:       { consumers: [], disposition: "feed_only", kind: "update",     what: "a strategic play asked a second manager for a complementary read (the huddle)" },
  source_allocation_advice:       { consumers: [], disposition: "feed_only", kind: "update",     what: "lead-source enable/disable advice from real conversion + ROI" },
  source_lifetime_health_advice:  { consumers: [], disposition: "feed_only", kind: "update",     what: "lead-source lifetime-quality advice (relationships that LAST, not just first close)" },
  win_story:                      { consumers: [], disposition: "feed_only", kind: "update",     what: "a farm-area win worth telling the neighborhood (social proof)" },
  trid_disclosure_clock:          { consumers: [], disposition: "feed_only", kind: "update",     what: "a TRID disclosure clock is ticking on a deal — keep the timeline honest" },
  journey_conformance_violation:  { consumers: [], disposition: "feed_only", kind: "alert",      what: "a contact's journey drifted off its required path — flag for review" },
  net_sheet_surprise:             { consumers: [], disposition: "feed_only", kind: "alert",      what: "a net-sheet figure shifted enough to surprise the seller — get ahead of it" },
  wire_fraud_risk:                { consumers: [], disposition: "feed_only", kind: "update",     what: "a wire-fraud risk signal on a closing — verify before any funds move" },
  document_compliance_finding:    { consumers: [], disposition: "feed_only", kind: "alert",      what: "a document-compliance audit finding needs a human's eyes" },
  regulatory_change_detected:     { consumers: [], disposition: "feed_only", kind: "alert",      what: "a real-estate regulatory change was detected that touches the gates" },
  license_risk_escalated:         { consumers: [], disposition: "feed_only", kind: "escalation", what: "an AI-sentinel license/authority risk escalated for review" },
  launch_war_room_convened:       { consumers: [], disposition: "feed_only", kind: "escalation", what: "a listing launch war-room convened the team" },
  fire_drill_opened:              { consumers: [], disposition: "feed_only", kind: "escalation", what: "a fire-drill opened — the team converges on an urgent situation" },
  farm_play_convened:             { consumers: [], disposition: "feed_only", kind: "escalation", what: "a farm play convened the managers around a neighborhood opportunity" },
  bidding_war_convened:           { consumers: [], disposition: "feed_only", kind: "escalation", what: "a bidding-war concierge convened the team around multiple offers" },
  first_touch_claimed:            { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a manager claimed the first touch on a new lead (the bullpen race resolved)" },
  dual_transaction_timing:        { consumers: [], disposition: "feed_only", kind: "update",     what: "MOVE-UP coordination — a 'both' contact selling their current home AND buying the next; the Listing Concierge ↔ Shopping Agent timing play (ramp the buyer search as the sale closes, prep a sale-contingent offer, or align close dates) made visible on the bus so the two sides never drift out of sync" },
  stage_stalled:                  { consumers: [], disposition: "feed_only", kind: "update",     what: "a contact has sat in a legal lifecycle stage TOO LONG with nothing in motion (the quiet failure journey-conformance's illegal-transition check misses) — surfaced to the manager who owns that stage (AI ISA / Shopping Agent / Listing Concierge / Deal Coordinator) by dwell-vs-ceiling" },
  listing_marketing_ready:        { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a listing reached coming-soon or went live — the Listing Concierge → Campaign Orchestrator marketing handoff, made visible on the bus (the kernel-event fanout still enrolls the sequences; this makes the team coordination legible)" },
  offer_docs_ready:               { consumers: [], disposition: "feed_only", kind: "handoff",    what: "a signed offer packet passed the completeness scan (all required forms present + signed) — the Deal Coordinator handoff that the docs are verified and ready to send to the listing agent (the agent is also notified)" },
  agent_overloaded:               { consumers: [], disposition: "feed_only", kind: "escalation", what: "capacity guardian flagged an agent's load — surfaced for the broker (advisory)" },
  geo_visibility_gap:             { consumers: ["campaign_orchestrator"], disposition: "handled", kind: "update", what: "the GEO loop closed — a published lead-magnet/FAQ landing page has been checked enough times across enough days by AI search and is STILL never cited (persistently invisible); the Campaign Orchestrator PROPOSES a one-tap gated regenerate_faq action (rebuild the FAQ + schema.org block from fresh demand topics) so monitoring becomes remediation a human approves, not just a number" },
  lead_magnet_handoff:            { consumers: [], disposition: "feed_only", kind: "handoff",     what: "a lead-magnet conversion routed to the right manager by INTENT — a buyer guide / listing alert / open-house RSVP hands the new buyer lead to the Shopping Agent; a seller guide / market report hands the seller lead to the Listing Concierge (a home-value request gets the stronger precise-CMA handoff instead). The kernel also stamps the contact's intent so the portal view + education match; the gated lead-magnet sequence provides the follow-up touches" },
  lead_source_waste:              { consumers: ["campaign_orchestrator"], disposition: "handled", kind: "update", what: "the lead-source learner closed its loop — a scrape source is a proven money-pit (trusted ROI below the floor) or a proven winner that's off; the Campaign Orchestrator proposes a one-tap GATED reallocate_lead_sources action (turn the winners on / the money-pits off for that market's enabled_sources) a human approves. Never acts on thin samples" },
}

/** Look up a signal's spec (undefined = uncatalogued, which test:signal-integrity fails on). */
export function signalSpec(signalType: string): SignalSpec | undefined {
  return SIGNAL_REGISTRY[signalType]
}

/** Every catalogued signal_type. */
export function registeredSignalTypes(): string[] {
  return Object.keys(SIGNAL_REGISTRY)
}
