"use client"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Loader2, Send, Bot, User } from "lucide-react"
import { Badge } from "@/components/ui/badge"

interface Message {
  role: "user" | "assistant"
  content: string
  isUnderstandingPhase?: boolean
}

export function ThemFirstChatAssistant({ prospectId }: { prospectId?: string }) {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content:
        "Hi! Before I help you, I want to make sure I understand your situation. Can you tell me what brings you here today?",
      isUnderstandingPhase: true,
    },
  ])
  const [input, setInput] = useState("")
  const [loading, setLoading] = useState(false)
  const [understandingPhase, setUnderstandingPhase] = useState(true)
  const [contextGathered, setContextGathered] = useState<any>({})
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [messages])

  const handleSend = async () => {
    if (!input.trim() || loading) return

    const userMessage: Message = { role: "user", content: input }
    setMessages((prev) => [...prev, userMessage])
    setInput("")
    setLoading(true)

    try {
      // In understanding phase, ask follow-up questions
      if (understandingPhase) {
        const response = await getUnderstandingResponse(input, messages.length)
        setMessages((prev) => [...prev, { role: "assistant", content: response, isUnderstandingPhase: true }])

        // After 3-4 questions, move to solution phase
        if (messages.length >= 6) {
          setUnderstandingPhase(false)
          setMessages((prev) => [
            ...prev,
            {
              role: "assistant",
              content:
                "Thank you for sharing that with me. Now I understand your situation better. How can I help you move forward?",
              isUnderstandingPhase: false,
            },
          ])
        }
      } else {
        // Provide solutions with context
        const response = await getSolutionResponse(input, contextGathered, prospectId)
        setMessages((prev) => [...prev, { role: "assistant", content: response }])
      }
    } catch (error) {
      console.error("[v0] Chat error:", error)
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "I apologize, but I encountered an error. Can you try rephrasing that?",
        },
      ])
    } finally {
      setLoading(false)
    }
  }

  const getUnderstandingResponse = async (userInput: string, messageCount: number): Promise<string> => {
    // Simple question flow - in production, use AI to make this dynamic
    const questions = [
      "What's your current situation? Are you looking to buy, sell, or both?",
      "What's the biggest concern or worry you have right now about this process?",
      "What's your timeline? When do you need to make this happen?",
      "What would make this easier for you? What kind of support are you looking for?",
    ]

    const questionIndex = Math.floor(messageCount / 2)
    if (questionIndex < questions.length) {
      return questions[questionIndex]
    }

    return "Thank you for sharing all of that with me."
  }

  const getSolutionResponse = async (userInput: string, context: any, prospectId?: string): Promise<string> => {
    // In production, this would call the AI SDK with full context
    return `Based on what you've told me about your situation, here's what I recommend... [This would be a them-first response generated by the AI using their context]`
  }

  return (
    <Card className="w-full max-w-2xl h-[600px] flex flex-col">
      <CardHeader>
        <CardTitle className="flex items-center justify-between">
          <span>THEM-FIRST Chat Assistant</span>
          {understandingPhase && <Badge variant="secondary">Understanding Phase</Badge>}
        </CardTitle>
      </CardHeader>
      <CardContent className="flex-1 flex flex-col p-0">
        <ScrollArea className="flex-1 p-4" ref={scrollRef}>
          <div className="space-y-4">
            {messages.map((message, i) => (
              <div key={i} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>
                {message.role === "assistant" && (
                  <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                    <Bot className="h-4 w-4 text-primary-foreground" />
                  </div>
                )}
                <div
                  className={`max-w-[80%] rounded-lg p-3 ${
                    message.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted"
                  }`}
                >
                  <p className="text-sm leading-relaxed">{message.content}</p>
                </div>
                {message.role === "user" && (
                  <div className="w-8 h-8 rounded-full bg-secondary flex items-center justify-center flex-shrink-0">
                    <User className="h-4 w-4" />
                  </div>
                )}
              </div>
            ))}
            {loading && (
              <div className="flex gap-3 justify-start">
                <div className="w-8 h-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                  <Bot className="h-4 w-4 text-primary-foreground" />
                </div>
                <div className="bg-muted rounded-lg p-3">
                  <Loader2 className="h-4 w-4 animate-spin" />
                </div>
              </div>
            )}
          </div>
        </ScrollArea>
        <div className="p-4 border-t">
          <div className="flex gap-2">
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && handleSend()}
              placeholder="Type your message..."
              disabled={loading}
            />
            <Button onClick={handleSend} disabled={loading || !input.trim()}>
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
