// Demo mode configuration
export const DEMO_CONFIG = {
  ENABLED: true,
  MODE: 'password', // password | magic-link | oauth
  AUTO_LOGIN: false,
};

// 20 Demo Users - Real Estate Personas
export const DEMO_USERS = [
  // Agents
  {
    id: '1',
    email: 'agent1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'agent',
    agency: 'VIP Real Estate Group',
    specialization: 'Luxury Homes',
    state: 'CA',
  },
  {
    id: '2',
    email: 'agent2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Michael',
    lastName: 'Chen',
    role: 'agent',
    agency: 'VIP Real Estate Group',
    specialization: 'Commercial',
    state: 'TX',
  },
  {
    id: '3',
    email: 'agent3@vipos.com',
    password: 'Demo@123456',
    firstName: 'Jennifer',
    lastName: 'Martinez',
    role: 'agent',
    agency: 'VIP Real Estate Group',
    specialization: 'Residential',
    state: 'FL',
  },
  {
    id: '4',
    email: 'agent4@vipos.com',
    password: 'Demo@123456',
    firstName: 'David',
    lastName: 'Patel',
    role: 'agent',
    agency: 'VIP Real Estate Group',
    specialization: 'Investment',
    state: 'NY',
  },
  {
    id: '5',
    email: 'agent5@vipos.com',
    password: 'Demo@123456',
    firstName: 'Amanda',
    lastName: 'Williams',
    role: 'agent',
    agency: 'VIP Real Estate Group',
    specialization: 'Relocation',
    state: 'CO',
  },

  // Team Leads
  {
    id: '6',
    email: 'lead1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Robert',
    lastName: 'Thompson',
    role: 'team_lead',
    agency: 'VIP Real Estate Group',
    specialization: 'Team Management',
    state: 'CA',
  },
  {
    id: '7',
    email: 'lead2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Lisa',
    lastName: 'Anderson',
    role: 'team_lead',
    agency: 'VIP Real Estate Group',
    specialization: 'Team Management',
    state: 'TX',
  },

  // Brokers
  {
    id: '8',
    email: 'broker1@vipos.com',
    password: 'Demo@123456',
    firstName: 'James',
    lastName: 'Wilson',
    role: 'broker',
    agency: 'VIP Real Estate Group',
    specialization: 'Brokerage',
    state: 'CA',
  },
  {
    id: '9',
    email: 'broker2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Patricia',
    lastName: 'Davis',
    role: 'broker',
    agency: 'VIP Real Estate Group',
    specialization: 'Brokerage',
    state: 'NY',
  },

  // Managers
  {
    id: '10',
    email: 'manager1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Richard',
    lastName: 'Brown',
    role: 'manager',
    agency: 'VIP Real Estate Group',
    specialization: 'Operations',
    state: 'CA',
  },

  // Transaction Coordinators
  {
    id: '11',
    email: 'tc1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Karen',
    lastName: 'Miller',
    role: 'tc',
    agency: 'VIP Real Estate Group',
    specialization: 'Transactions',
    state: 'CA',
  },
  {
    id: '12',
    email: 'tc2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Thomas',
    lastName: 'Moore',
    role: 'tc',
    agency: 'VIP Real Estate Group',
    specialization: 'Transactions',
    state: 'TX',
  },

  // Clients - Buyers
  {
    id: '13',
    email: 'buyer1@vipos.com',
    password: 'Demo@123456',
    firstName: 'John',
    lastName: 'Smith',
    role: 'buyer',
    agency: 'VIP Real Estate Group',
    specialization: 'First-Time Buyer',
    state: 'CA',
  },
  {
    id: '14',
    email: 'buyer2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Emily',
    lastName: 'Taylor',
    role: 'buyer',
    agency: 'VIP Real Estate Group',
    specialization: 'Luxury Buyer',
    state: 'FL',
  },

  // Clients - Sellers
  {
    id: '15',
    email: 'seller1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Margaret',
    lastName: 'Jackson',
    role: 'seller',
    agency: 'VIP Real Estate Group',
    specialization: 'Home Seller',
    state: 'NY',
  },
  {
    id: '16',
    email: 'seller2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Charles',
    lastName: 'White',
    role: 'seller',
    agency: 'VIP Real Estate Group',
    specialization: 'Investment Property',
    state: 'TX',
  },

  // Admin Users
  {
    id: '17',
    email: 'admin1@vipos.com',
    password: 'Demo@123456',
    firstName: 'Christopher',
    lastName: 'Harris',
    role: 'admin',
    agency: 'VIP Real Estate Group',
    specialization: 'System Admin',
    state: 'CA',
  },
  {
    id: '18',
    email: 'admin2@vipos.com',
    password: 'Demo@123456',
    firstName: 'Jessica',
    lastName: 'Clark',
    role: 'admin',
    agency: 'VIP Real Estate Group',
    specialization: 'System Admin',
    state: 'CA',
  },

  // Support
  {
    id: '19',
    email: 'support@vipos.com',
    password: 'Demo@123456',
    firstName: 'Daniel',
    lastName: 'Lewis',
    role: 'support',
    agency: 'VIP Real Estate Group',
    specialization: 'Support',
    state: 'CA',
  },

  // Super Admin
  {
    id: '20',
    email: 'superadmin@vipos.com',
    password: 'Demo@123456',
    firstName: 'William',
    lastName: 'Walker',
    role: 'superadmin',
    agency: 'VIP Real Estate Group',
    specialization: 'Super Admin',
    state: 'CA',
  },
];
