"use client"

// components/portal/MarketPositionCard.tsx
// Displays market position analysis for seller portal.

import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/card"
import { Badge } from "@/app/components/ui/badge"
import { Skeleton } from "@/app/components/ui/skeleton"
import {
  TrendingUp,
  TrendingDown,
  Minus,
  BarChart3,
  Home,
  MapPin,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { formatPrice } from "@/lib/portal/seller-context-presentation"

interface NeighborhoodReport {
  id: string
  listing_id: string
  median_home_price: number | null
  ai_summary: string | null
  generated_at: string
  comparable_count?: number
}

interface MarketPositionCardProps {
  report: NeighborhoodReport | null
  comparison: "above" | "below" | "at" | null
  listPrice: number | null
  isLoading?: boolean
}

export function MarketPositionCard({
  report,
  comparison,
  listPrice,
  isLoading = false,
}: MarketPositionCardProps) {
  if (isLoading) {
    return <MarketPositionCardSkeleton />
  }

  // No report available
  if (!report) {
    return (
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-base flex items-center gap-2">
            <BarChart3 className="h-4 w-4" />
            Market Position
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-6">
            <MapPin className="h-8 w-8 text-muted-foreground mx-auto mb-2" />
            <p className="text-sm text-muted-foreground">
              Market analysis will appear here once generated by your agent.
            </p>
          </div>
        </CardContent>
      </Card>
    )
  }

  const ComparisonIcon = comparison === "above"
    ? TrendingUp
    : comparison === "below"
    ? TrendingDown
    : Minus

  const comparisonConfig = {
    above: { label: "Above Market", color: "bg-green-100 text-green-700" },
    below: { label: "Below Market", color: "bg-amber-100 text-amber-700" },
    at: { label: "At Market", color: "bg-blue-100 text-blue-700" },
  }

  const config = comparison ? comparisonConfig[comparison] : null

  // Calculate difference percentage
  let diffPct: number | null = null
  if (report.median_home_price && listPrice) {
    diffPct = ((listPrice - report.median_home_price) / report.median_home_price) * 100
  }

  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base flex items-center gap-2">
            <BarChart3 className="h-4 w-4" />
            Market Position
          </CardTitle>
          {config && (
            <Badge variant="secondary" className={cn("text-xs", config.color)}>
              <ComparisonIcon className="h-3 w-3 mr-1" />
              {config.label}
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {/* Price Comparison */}
          <div className="grid grid-cols-2 gap-4">
            <div className="p-3 rounded-lg bg-muted/50 text-center">
              <p className="text-xs text-muted-foreground mb-1">Your List Price</p>
              <p className="text-lg font-semibold">{formatPrice(listPrice)}</p>
            </div>
            <div className="p-3 rounded-lg bg-muted/50 text-center">
              <p className="text-xs text-muted-foreground mb-1">Area Median</p>
              <p className="text-lg font-semibold">{formatPrice(report.median_home_price)}</p>
            </div>
          </div>

          {/* Difference */}
          {diffPct !== null && (
            <div className="flex items-center justify-center gap-2 text-sm">
              <ComparisonIcon className={cn(
                "h-4 w-4",
                diffPct > 0 ? "text-green-600" : diffPct < 0 ? "text-amber-600" : "text-blue-600"
              )} />
              <span className={cn(
                "font-medium",
                diffPct > 0 ? "text-green-600" : diffPct < 0 ? "text-amber-600" : "text-blue-600"
              )}>
                {diffPct > 0 ? "+" : ""}{diffPct.toFixed(1)}% vs neighborhood median
              </span>
            </div>
          )}

          {/* Comparable count */}
          {report.comparable_count && report.comparable_count > 0 && (
            <div className="flex items-center justify-center gap-2 text-sm text-muted-foreground">
              <Home className="h-3.5 w-3.5" />
              <span>Based on {report.comparable_count} comparable listings</span>
            </div>
          )}

          {/* AI Summary */}
          {report.ai_summary && (
            <div className="p-3 rounded-lg border bg-card">
              <p className="text-sm text-muted-foreground line-clamp-3">
                {report.ai_summary}
              </p>
            </div>
          )}

          {/* Generated date */}
          <p className="text-xs text-muted-foreground text-center">
            Updated {new Date(report.generated_at).toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
              year: "numeric",
            })}
          </p>
        </div>
      </CardContent>
    </Card>
  )
}

function MarketPositionCardSkeleton() {
  return (
    <Card>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <Skeleton className="h-5 w-32" />
          <Skeleton className="h-5 w-24 rounded-full" />
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <Skeleton className="h-20 w-full rounded-lg" />
            <Skeleton className="h-20 w-full rounded-lg" />
          </div>
          <Skeleton className="h-4 w-48 mx-auto" />
          <Skeleton className="h-16 w-full rounded-lg" />
        </div>
      </CardContent>
    </Card>
  )
}

export { MarketPositionCardSkeleton }
