/**
 * scripts/agent-fk-columns.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * WHICH ID CLASS DOES THIS COLUMN HOLD? The schema is split-brain: some columns named agent_id
 * FK agents(id) and others FK users(id) — activities.agent_user_id is a users.id,
 * net_sheet_calculations.agent_id is an agents.id. You cannot tell from the column NAME, which is
 * exactly how wrong-class writes keep shipping, and `agents.id` and `users.id` are DISJOINT id
 * spaces (23503), not two names for one row. scripts/agent-id-class-guard.ts reads the three maps
 * below; m366 re-pointed 20 columns from users(id) to agents(id) and this map went stale the
 * moment it landed — a stale map makes the guard flag correct writes and, worse, bless wrong ones.
 *
 * Built from the same live reading as scripts/schema-fk-map.ts — public.live_foreign_keys_json() — so the two
 * files cannot disagree about an edge. SINGLE-COLUMN foreign keys only: a composite FK constrains
 * a TUPLE, and no one column in it carries the target's id on its own. 0 composite FK(s)
 * to these three targets were skipped at this reading.
 *
 * This file is a CACHE OF THE LIVE DATABASE, not a second opinion about it. CI holds no database
 * credentials, so without the cache the identity-class guard goes blind — that is the only reason
 * it is committed.
 *
 * MEASURED AT GENERATION: 213 agents(id) columns across 204 tables, 33 agent-ish users(id) columns across 31 tables, 164 contact_id tables.
 *
 * ── PROVENANCE — this file is MACHINE-WRITTEN. Do not hand-edit it. ──────────
 * generated: 2026-08-24
 * source: public.live_foreign_keys_json()
 * body-sha256: 2eb529d2f00e5b8e5966fdc3574a9edb1c51aaca201ab92d97f160e27ccf8fb1
 *
 * scripts/schema-cache-drift-guard.ts recomputes body-sha256 from the bytes below and compares
 * this file against the LIVE database. A hand-edit fails the first check even with no credentials;
 * a schema change the cache has not absorbed fails the second wherever credentials exist.
 * To update: regenerate (`npm run schema:regen`), review the diff, commit it.
 * `generated:` is carried forward when a regeneration changes nothing, so a no-op regen writes
 * no bytes.
 */
// ─── BODY — body-sha256 covers every byte from the next line to EOF ─────────
/** `AGENT_FK_COLUMNS[table] = [column, …]` — every column that FOREIGN KEYs public.agents(id).
 *  Anything else named `agent_id` is a different animal; check the map below before assuming. */
export const AGENT_FK_COLUMNS: Record<string, string[]> = {
  activities: ["agent_id"],
  agent_api_credentials: ["agent_id"],
  agent_assistant_sessions: ["agent_id"],
  agent_avatar_assets: ["agent_id"],
  agent_badges: ["agent_id"],
  agent_cap_tracking: ["agent_id"],
  agent_ce_completions: ["agent_id"],
  agent_certifications: ["agent_id"],
  agent_chat_preferences: ["agent_id"],
  agent_commission_profiles: ["agent_id"],
  agent_commissions: ["agent_id"],
  agent_credit_budgets: ["agent_id"],
  agent_did_consents: ["agent_id"],
  agent_earnings: ["agent_id"],
  agent_fee_assignments: ["agent_id"],
  agent_fee_charges: ["agent_id"],
  agent_goals: ["agent_id"],
  agent_handoffs: ["human_agent_id"],
  agent_intro_videos: ["agent_id"],
  agent_learning_paths: ["agent_id"],
  agent_licenses: ["agent_id"],
  agent_mentor_relationships: ["mentee_agent_id", "mentor_agent_id"],
  agent_metrics: ["agent_id"],
  agent_monthly_earnings: ["agent_id"],
  agent_notifications: ["agent_id"],
  agent_onboarding: ["agent_id"],
  agent_onboarding_sessions: ["agent_id"],
  agent_onboarding_steps: ["agent_id"],
  agent_performance_reports: ["agent_id"],
  agent_pl_snapshot: ["agent_id"],
  agent_points_log: ["agent_id"],
  agent_quiz_attempts: ["agent_id"],
  agent_relationships: ["agent_id", "sponsor_agent_id"],
  agent_reviews: ["agent_id"],
  agent_step_completions: ["agent_id"],
  agent_voice_profiles: ["agent_id"],
  agents: ["covering_agent_id"],
  ai_autopilot_actions: ["agent_id"],
  ai_autopilot_plans: ["agent_id"],
  ai_daily_briefings: ["agent_id"],
  ai_feedback_log: ["agent_id"],
  ai_insights: ["agent_id"],
  ai_isa_call_batches: ["proposed_by_agent_id"],
  ai_isa_qualifications: ["agent_id"],
  ai_isa_settings: ["agent_id"],
  ai_search_citation_observations: ["agent_id"],
  ai_search_landing_citation_observations: ["agent_id"],
  ai_subscription_tier: ["agent_id"],
  ai_suggestions: ["agent_id"],
  ai_tool_usage: ["agent_id"],
  ai_usage_log: ["agent_id"],
  ai_usage_monthly: ["agent_id"],
  ai_video_projects: ["agent_id"],
  appointments: ["agent_id"],
  approval_items: ["agent_id"],
  assignment_log: ["agent_id"],
  auto_response_settings: ["agent_id"],
  brand_voice_profile: ["agent_id"],
  budgets: ["agent_id"],
  business_card_scans: ["agent_id"],
  business_expenses: ["agent_id"],
  buyer_behavior_log: ["agent_id"],
  buyer_behavior_predictions: ["agent_id"],
  buyer_broker_agreements: ["agent_id"],
  buyer_fatigue_scores: ["agent_id"],
  calendar_blocks: ["agent_id"],
  call_analyses: ["agent_id"],
  call_coaching_insights: ["agent_id"],
  chat_sessions: ["agent_id"],
  chat_templates: ["agent_id"],
  client_detailed_personas: ["agent_id"],
  client_engagement_scores: ["agent_id"],
  client_gifts: ["agent_id"],
  client_portal_activity: ["agent_id"],
  client_portal_messages: ["agent_id"],
  closing_disclosure_agreement: ["agent_id"],
  closing_gifts: ["agent_id"],
  cma_packages: ["agent_id"],
  cma_reports: ["agent_id"],
  commission_adjustments: ["approved_by_agent_id", "created_by_agent_id"],
  commission_calculations: ["agent_id"],
  commission_distributions: ["agent_id"],
  commission_rules: ["agent_id"],
  commission_splits: ["agent_id"],
  communication_audit_log: ["agent_id"],
  communications: ["agent_id"],
  compliance_flags: ["agent_id"],
  compliance_tasks: ["agent_id"],
  contact_portal_modules: ["enabled_by_agent_id"],
  contact_vendors: ["agent_id"],
  contacts: ["agent_id"],
  content_ab_tests: ["agent_id"],
  content_calendar: ["agent_id"],
  content_generation_logs: ["agent_id"],
  content_performance_tracking: ["agent_id"],
  content_templates: ["agent_id"],
  content_topic_uses: ["agent_id"],
  contract_reviews: ["agent_id"],
  contract_signatures: ["agent_id"],
  conversation_insights: ["agent_id"],
  conversation_intelligence: ["agent_id"],
  conversation_logs: ["agent_id"],
  conversations: ["agent_id"],
  copilot_plans: ["agent_id"],
  cost_allocation: ["agent_id"],
  credit_accounts: ["agent_id"],
  deposits: ["agent_id"],
  direct_mail_campaigns: ["agent_id"],
  drip_campaigns: ["agent_id"],
  embed_widgets: ["agent_id", "last_routed_agent_id"],
  fair_housing_logs: ["agent_id"],
  farm_territories: ["agent_id"],
  financial_reports: ["agent_id"],
  generated_content: ["agent_id"],
  generated_documents: ["agent_id"],
  gift_vendors: ["agent_id"],
  hashtag_performance: ["agent_id"],
  home_value_page_configs: ["agent_id"],
  income_forecast_gap_analysis: ["agent_id"],
  income_forecast_snapshots: ["agent_id"],
  income_gap_recommended_actions: ["agent_id"],
  isa_outreach_log: ["agent_id"],
  lead_capture_forms: ["agent_id"],
  lead_imports: ["agent_id"],
  lead_scores: ["agent_id"],
  lead_scraping_markets: ["agent_id"],
  lead_sla_tracking: ["agent_id"],
  leaderboard_rankings: ["agent_id"],
  leads: ["agent_id"],
  lifetime_customer_npv_scores: ["agent_id"],
  lifetime_customer_touchpoints: ["agent_id"],
  listing_health_interventions: ["agent_id"],
  listing_health_scores: ["agent_id"],
  listing_price_changes: ["agent_id"],
  listing_promo_videos: ["agent_id"],
  listings: ["agent_id"],
  market_insights: ["agent_id"],
  meeting_briefs: ["agent_id"],
  messages: ["agent_id"],
  net_sheet_calculations: ["agent_id"],
  newsletter_campaigns: ["agent_id"],
  newsletter_scheduled_sends: ["agent_id"],
  newsletter_subscribers: ["agent_id"],
  newsletter_templates: ["agent_id"],
  newsletter_video_renders: ["agent_id"],
  objection_scenario_agents: ["agent_id"],
  offer_comparison: ["agent_id"],
  offers: ["agent_id", "presented_to_seller_by_agent_id"],
  onboarding_ai_chats: ["agent_id"],
  open_house_events: ["agent_id"],
  pattern_adoptions: ["agent_id"],
  pattern_detections: ["agent_id"],
  pattern_predictions: ["agent_id"],
  phone_number_events: ["agent_id"],
  photo_enhancement_jobs: ["agent_id"],
  photo_ordering_rules: ["agent_id"],
  podcast_auto_runs: ["agent_id"],
  podcast_episodes: ["agent_id"],
  podcast_templates: ["agent_id"],
  portal_access_logs: ["agent_id"],
  property_preferences: ["agent_id"],
  prospects: ["agent_id"],
  qr_codes: ["agent_id"],
  recruiting_analytics: ["recruited_agent_id"],
  recruiting_costs: ["recruited_agent_id"],
  recruiting_roi: ["recruited_agent_id"],
  recruits: ["recruiter_agent_id"],
  referral_partners: ["agent_id"],
  referrals: ["agent_id", "referring_agent_id"],
  revenue_protection_snapshots: ["agent_id"],
  review_requests: ["agent_id"],
  showing_briefings: ["agent_id"],
  showing_routes: ["agent_id"],
  showings: ["agent_id"],
  smart_assistant_suggestions: ["agent_id"],
  social_media_accounts: ["agent_id"],
  social_posts: ["agent_id"],
  studio_sessions: ["agent_id"],
  support_tickets: ["agent_id"],
  tasks: ["assigned_to_agent_id", "created_by_agent_id"],
  team_cap_tracking: ["agent_id"],
  team_earnings: ["top_agent_id"],
  team_heatmap_snapshots: ["agent_id"],
  team_members: ["agent_id"],
  thank_you_note_templates: ["agent_id"],
  thank_you_notes: ["agent_id"],
  tours: ["agent_id"],
  transaction_agent_roles: ["agent_id"],
  transaction_pending_actions: ["agent_id"],
  transactions: ["agent_id", "buyer_agent_id", "seller_agent_id"],
  transparency_updates: ["agent_id"],
  usage_events: ["agent_id"],
  usage_logs: ["agent_id"],
  valuation_requests: ["agent_id"],
  value_delivered_daily: ["agent_id"],
  vendor_assignments: ["assigned_by_agent_id"],
  vendor_usage_tracking: ["agent_id"],
  video_assets: ["agent_id"],
  video_completion_tracking: ["agent_id"],
  video_scripts_library: ["agent_id"],
  voice_assistant_config: ["agent_id"],
  voice_assistant_sessions: ["agent_id"],
  voice_calls: ["agent_id"],
  website_visitors: ["agent_id"],
}

/** `USERS_FK_AGENTISH_COLUMNS[table] = [column, …]` — columns that FK public.users(id) whose
 *  NAME contains "agent", so they read as agents(id) and are not. The REVERSE-direction hazard:
 *  writing a resolved agents.id here is as broken as the forward case. `contacts.source_agent_id`
 *  is the sharpest — it sits on the same row as `contacts.agent_id`, which IS an agents.id.
 *  A misleading users column whose name lacks "agent" (teams.team_lead_id,
 *  closing_disclosure_agreement.broker_id) is deliberately NOT here — see AGENTISH in
 *  scripts/schema-cache-builders.ts. */
export const USERS_FK_AGENTISH_COLUMNS: Record<string, string[]> = {
  activities: ["agent_user_id"],
  ad_campaigns: ["agent_user_id"],
  agent_social_shares: ["agent_user_id"],
  ai_isa_qualifications: ["assigned_to_agent_id"],
  ai_message_drafts: ["agent_user_id"],
  blog_posts: ["agent_user_id"],
  buyer_financial_profiles: ["agent_user_id"],
  buyer_intake_tokens: ["agent_user_id"],
  campaign_calendar: ["agent_user_id"],
  closing_disclosure_agreement: ["agent_signed_off_by", "agent_submitted_by"],
  contacts: ["source_agent_id"],
  fatigue_alerts: ["agent_user_id"],
  learning_assignments: ["agent_user_id"],
  listing_agreements: ["agent_user_id"],
  listing_packet_jobs: ["agent_user_id"],
  listing_presentations: ["agent_user_id"],
  marketing_assets: ["agent_user_id"],
  marketing_campaigns: ["agent_user_id"],
  negotiation_strategies: ["agent_user_id"],
  neighbor_notification_campaigns: ["agent_user_id"],
  objection_training_sessions: ["agent_user_id"],
  platform_credentials: ["agent_user_id"],
  portal_event_stream: ["agent_action_completed_by", "agent_user_id"],
  property_alerts: ["agent_user_id"],
  property_interests: ["agent_user_id"],
  repurpose_pipelines: ["agent_user_id"],
  seo_keywords: ["agent_user_id"],
  strategy_recommendations: ["agent_user_id"],
  tours: ["agent_approved_by"],
  workflow_intake_sessions: ["agent_user_id"],
  workflow_runs: ["agent_user_id"],
}

/** Tables whose `contact_id` FKs public.contacts(id).
 *  A LEAD is not a CONTACT: writing a lead id here is FK-rejected and the row is silently lost,
 *  because supabase-js RESOLVES a refusal. The repo's correct shape for a lead-era row is
 *  `contact_id: null, entity_type: "lead", entity_id: <leadId>`.
 *  Only `contact_id` is listed — the other columns that FK contacts (seller_contact_id,
 *  buyer_contact_id, viewer_contact_id, …) name their side and do not read as a lead id. */
export const CONTACT_FK_TABLES: string[] = [
  "activities",
  "agent_intro_videos",
  "agent_reviews",
  "ai_assistant_notes",
  "ai_autopilot_plans",
  "ai_insights",
  "ai_isa_activities",
  "ai_isa_calls",
  "ai_isa_engagement_tracking",
  "ai_isa_qualifications",
  "ai_message_drafts",
  "ai_video_projects",
  "appointments",
  "behavioral_signals",
  "business_card_scans",
  "buyer_behavior_log",
  "buyer_behavior_predictions",
  "buyer_fatigue_scores",
  "buyer_financial_profiles",
  "buyer_intake_tokens",
  "calculator_history",
  "call_analyses",
  "chat_sessions",
  "client_detailed_personas",
  "client_documents",
  "client_engagement_scores",
  "client_gifts",
  "client_portal_activity",
  "client_portal_messages",
  "closing_gifts",
  "cma_reports",
  "collaborative_searches",
  "communication_audit_log",
  "communications",
  "compliance_flags",
  "contact_consent_events",
  "contact_enrichment_queue",
  "contact_notes",
  "contact_portal_modules",
  "contact_portal_preferences",
  "contact_segments",
  "contact_suppression_list",
  "contact_vendors",
  "conversation_insights",
  "conversation_logs",
  "conversations",
  "copilot_plans",
  "credit_accounts",
  "credit_conversation_logs",
  "credit_partner_referrals",
  "credit_status",
  "data_health_logs",
  "deconflict_suppression_log",
  "direct_mail_recipients",
  "direct_mail_responses",
  "document_requests",
  "documents",
  "drip_campaigns",
  "email_sends",
  "email_tracking",
  "embed_sessions",
  "external_behavior",
  "fair_housing_logs",
  "fatigue_alerts",
  "form_submissions",
  "generated_content",
  "generated_documents",
  "home_value_estimates",
  "income_gap_recommended_actions",
  "intelligence_signals_log",
  "intelligent_outreach_log",
  "isa_outreach_log",
  "journey_stage_progress",
  "journey_states",
  "journey_task_completions",
  "lead_enrichment_queue",
  "lead_score_history",
  "lead_scores",
  "lead_value_journey",
  "leads",
  "learning_assignments",
  "lender_applications",
  "lifetime_customer_npv_scores",
  "lifetime_customer_touchpoints",
  "listing_engagement",
  "listing_landing_pages",
  "listing_presentations",
  "listings",
  "mail_response_tracking",
  "manager_signals",
  "marketing_attribution_credits",
  "marketing_campaign_touchpoints",
  "messages",
  "motivated_seller_signals",
  "negotiation_strategies",
  "net_sheet_calculations",
  "newsletter_sends",
  "newsletter_subscribers",
  "notifications",
  "offers",
  "open_house_attendees",
  "open_house_feedback",
  "open_house_invitations",
  "open_house_rsvp_tracking",
  "outbound_message_compliance_log",
  "outcome_reconciliations",
  "outside_agent_contact_links",
  "portal_access_logs",
  "portal_contact_invites",
  "portal_event_stream",
  "predictive_listing_actions",
  "predictive_listing_scores",
  "privacy_acceptances",
  "property_alert_delivery_log",
  "property_alert_results",
  "property_alerts",
  "property_feedback",
  "property_intelligence",
  "property_interactions",
  "property_interests",
  "property_matches",
  "property_preferences",
  "property_search_log",
  "property_views",
  "qr_scan_events",
  "real_estate_events",
  "referral_sources",
  "review_requests",
  "saved_properties",
  "scheduled_touchpoints",
  "seller_share_feed",
  "seller_updates",
  "seller_weekly_reports",
  "sequence_enrollments",
  "sequence_step_executions",
  "showing_requests",
  "showings",
  "signal_reactivations",
  "signature_requests",
  "site_activity",
  "smart_landing_sessions",
  "smart_showing_recommendations",
  "social_intelligence",
  "strategy_recommendations",
  "support_tickets",
  "tasks",
  "thank_you_notes",
  "tour_stops",
  "tours",
  "transactions",
  "transparency_updates",
  "unified_lead_profile",
  "usage_events",
  "valuation_requests",
  "vendor_bookings",
  "vendor_contact_assignments",
  "vendor_invoices",
  "video_engagement_events",
  "voice_calls",
  "wealth_advisor_recommendations",
  "website_visitors",
  "workflow_intake_sessions",
  "workflow_runs",
  "workflow_webhook_events",
]
