// scripts/agent-fk-columns.ts
//
// Every column that FOREIGN KEYs public.agents(id), snapshotted from the live
// database. Committed rather than queried so the guard runs offline and the map
// is reviewable in a diff.
//
// WHY THIS EXISTS. The schema is split-brain: some columns named agent_id FK
// agents(id) and others FK users(id) — newsletter_scheduled_sends.agent_id is a
// users.id, net_sheet_calculations.agent_id is an agents.id. You cannot tell from
// the column name, which is exactly how wrong-class writes keep shipping. Only the
// columns BELOW are agents(id); anything else named agent_id is a different animal.
//
// Regenerate from:
//   select con.conrelid::regclass::text, (the conkey attname)
//   from pg_constraint con where con.contype='f'
//     and con.confrelid='public.agents'::regclass;
export const AGENT_FK_COLUMNS: Record<string, string[]> = {
  activities: ["agent_id"],
  agent_achievements: ["agent_id"],
  agent_api_credentials: ["agent_id"],
  agent_assistant_sessions: ["agent_id"],
  agent_avatar_assets: ["agent_id"],
  agent_badges: ["agent_id"],
  agent_cap_tracking: ["agent_id"],
  agent_ce_completions: ["agent_id"],
  agent_certifications: ["agent_id"],
  agent_chat_preferences: ["agent_id"],
  agent_commission_profiles: ["agent_id"],
  agent_commissions: ["agent_id"],
  agent_credit_budgets: ["agent_id"],
  agent_earnings: ["agent_id"],
  agent_fee_assignments: ["agent_id"],
  agent_fee_charges: ["agent_id"],
  agent_goals: ["agent_id"],
  agent_handoffs: ["human_agent_id"],
  agent_learning_paths: ["agent_id"],
  agent_licenses: ["agent_id"],
  agent_mentor_relationships: ["mentee_agent_id", "mentor_agent_id"],
  agent_metrics: ["agent_id"],
  agent_monthly_earnings: ["agent_id"],
  agent_notifications: ["agent_id"],
  agent_onboarding: ["agent_id"],
  agent_onboarding_sessions: ["agent_id"],
  agent_onboarding_steps: ["agent_id"],
  agent_performance_reports: ["agent_id"],
  agent_pl_snapshot: ["agent_id"],
  agent_points_log: ["agent_id"],
  agent_quiz_attempts: ["agent_id"],
  agent_relationships: ["agent_id", "sponsor_agent_id"],
  agent_reviews: ["agent_id"],
  agent_step_completions: ["agent_id"],
  agent_voice_profiles: ["agent_id"],
  agents: ["covering_agent_id"],
  ai_autopilot_actions: ["agent_id"],
  ai_autopilot_plans: ["agent_id"],
  ai_content_outputs: ["agent_id"],
  ai_daily_briefings: ["agent_id"],
  ai_feedback_log: ["agent_id"],
  ai_insights: ["agent_id"],
  ai_isa_call_batches: ["proposed_by_agent_id"],
  ai_isa_qualifications: ["agent_id"],
  ai_subscription_tier: ["agent_id"],
  ai_suggestions: ["agent_id"],
  ai_tool_usage: ["agent_id"],
  ai_usage_log: ["agent_id"],
  ai_usage_monthly: ["agent_id"],
  appointments: ["agent_id"],
  approval_items: ["agent_id"],
  assignment_log: ["agent_id"],
  auto_response_settings: ["agent_id"],
  brand_voice_profile: ["agent_id"],
  budgets: ["agent_id"],
  business_card_scans: ["agent_id"],
  business_expenses: ["agent_id"],
  buyer_behavior_log: ["agent_id"],
  buyer_behavior_predictions: ["agent_id"],
  buyer_broker_agreements: ["agent_id"],
  buyer_fatigue_scores: ["agent_id"],
  buyer_tours: ["agent_id"],
  calendar_blocks: ["agent_id"],
  call_analyses: ["agent_id"],
  call_coaching_insights: ["agent_id"],
  chat_sessions: ["agent_id"],
  chat_templates: ["agent_id"],
  client_detailed_personas: ["agent_id"],
  client_engagement_scores: ["agent_id"],
  client_gifts: ["agent_id"],
  client_portal_activity: ["agent_id"],
  client_portal_messages: ["agent_id"],
  closing_gifts: ["agent_id"],
  cma_packages: ["agent_id"],
  cma_reports: ["agent_id"],
  commission_adjustments: ["approved_by_agent_id", "created_by_agent_id"],
  commission_calculations: ["agent_id"],
  commission_distributions: ["agent_id"],
  commission_rules: ["agent_id"],
  commission_splits: ["agent_id"],
  communication_audit_log: ["agent_id"],
  communications: ["agent_id"],
  compliance_flags: ["agent_id"],
  compliance_tasks: ["agent_id"],
  contact_portal_modules: ["enabled_by_agent_id"],
  contact_vendors: ["agent_id"],
  contacts: ["agent_id"],
  content_ab_tests: ["agent_id"],
  content_calendar: ["agent_id"],
  content_generation_logs: ["agent_id"],
  content_performance_tracking: ["agent_id"],
  content_templates: ["agent_id"],
  contract_reviews: ["agent_id"],
  contract_signatures: ["agent_id"],
  conversation_insights: ["agent_id"],
  conversation_intelligence: ["agent_id"],
  conversations: ["agent_id"],
  copilot_plans: ["agent_id"],
  cost_allocation: ["agent_id"],
  deposits: ["agent_id"],
  direct_mail_campaigns: ["agent_id"],
  drip_campaigns: ["agent_id"],
  earnings_history: ["agent_id"],
  embed_widgets: ["agent_id", "last_routed_agent_id"],
  fair_housing_logs: ["agent_id"],
  farm_territories: ["agent_id"],
  financial_reports: ["agent_id"],
  generated_content: ["agent_id"],
  generated_documents: ["agent_id"],
  gift_vendors: ["agent_id"],
  hashtag_performance: ["agent_id"],
  home_value_page_configs: ["agent_id"],
  income_forecast_gap_analysis: ["agent_id"],
  income_gap_recommended_actions: ["agent_id"],
  isa_outreach_log: ["agent_id"],
  lead_capture_forms: ["agent_id"],
  lead_imports: ["agent_id"],
  lead_scores: ["agent_id"],
  lead_scraping_markets: ["agent_id"],
  lead_sla_tracking: ["agent_id"],
  leaderboard_rankings: ["agent_id"],
  leads: ["agent_id"],
  lifetime_customer_touchpoints: ["agent_id"],
  listing_price_changes: ["agent_id"],
  listings: ["agent_id"],
  market_insights: ["agent_id"],
  meeting_briefs: ["agent_id"],
  messages: ["agent_id"],
  net_sheet_calculations: ["agent_id"],
  newsletter_campaigns: ["agent_id"],
  newsletter_subscribers: ["agent_id"],
  newsletter_templates: ["agent_id"],
  objection_scenario_agents: ["agent_id"],
  offer_comparison: ["agent_id"],
  offers: ["agent_id"],
  onboarding_ai_chats: ["agent_id"],
  open_house_events: ["agent_id"],
  open_houses: ["agent_id"],
  pattern_detections: ["agent_id"],
  pattern_predictions: ["agent_id"],
  phone_number_events: ["agent_id"],
  photo_enhancement_jobs: ["agent_id"],
  photo_ordering_rules: ["agent_id"],
  portal_access_logs: ["agent_id"],
  prospects: ["agent_id"],
  qr_codes: ["agent_id"],
  quickbooks_sync_log: ["agent_id"],
  recruiting_analytics: ["recruited_agent_id"],
  recruiting_costs: ["recruited_agent_id"],
  recruiting_roi: ["recruited_agent_id"],
  recruits: ["recruiter_agent_id"],
  referral_partners: ["agent_id"],
  referrals: ["agent_id", "referring_agent_id"],
  showing_briefings: ["agent_id"],
  showing_routes: ["agent_id"],
  showings: ["agent_id"],
  smart_assistant_suggestions: ["agent_id"],
  social_accounts: ["agent_id"],
  social_media_accounts: ["agent_id"],
  social_posts: ["agent_id"],
  support_tickets: ["agent_id"],
  tasks: ["assigned_to_agent_id", "created_by_agent_id"],
  team_earnings: ["top_agent_id"],
  team_heatmap_snapshots: ["agent_id"],
  team_members: ["agent_id"],
  thank_you_note_templates: ["agent_id"],
  thank_you_notes: ["agent_id"],
  tours: ["agent_id"],
  transaction_agent_roles: ["agent_id"],
  transaction_pending_actions: ["agent_id"],
  transactions: ["agent_id", "buyer_agent_id", "seller_agent_id"],
  usage_events: ["agent_id"],
  usage_logs: ["agent_id"],
  valuation_requests: ["agent_id"],
  value_delivered_daily: ["agent_id"],
  vendor_assignments: ["assigned_by_agent_id"],
  vendor_usage_tracking: ["agent_id"],
  video_assets: ["agent_id"],
  video_completion_tracking: ["agent_id"],
  video_content: ["agent_id"],
  video_scripts_library: ["agent_id"],
  voice_assistant_config: ["agent_id"],
  voice_assistant_sessions: ["agent_id"],
  voice_calls: ["agent_id"],
  website_visitors: ["agent_id"],
}

/**
 * Columns that FK public.users(id) but whose NAME reads agent-ish — the confusable
 * half of the split-brain. Snapshotted from the live database.
 *
 * These are the REVERSE-direction hazard: writing a resolved agents.id here is just
 * as broken as writing a user.id into an agents(id) FK. listing_promo_videos.agent_id
 * is the case that killed the entire lifecycle-promo path, and
 * listing_health_scores.agent_id / listing_health_interventions.agent_id are why the
 * listing-health scorer had never persisted a score.
 *
 * Only agent-ish NAMES are listed. A column called `created_by` or `uploaded_by` is
 * not going to be confused for an agents.id, and listing every users FK would bury
 * the ones that actually mislead.
 */
export const USERS_FK_AGENTISH_COLUMNS: Record<string, string[]> = {
  activities: ["agent_user_id"],
  ad_campaigns: ["agent_user_id"],
  agent_intro_videos: ["agent_id"],
  agent_social_shares: ["agent_user_id"],
  ai_isa_qualifications: ["assigned_to_agent_id"],
  ai_message_drafts: ["agent_user_id"],
  ai_video_projects: ["agent_id"],
  blog_posts: ["agent_user_id"],
  buyer_financial_profiles: ["agent_user_id"],
  buyer_intake_tokens: ["agent_user_id"],
  campaign_calendar: ["agent_user_id"],
  closing_disclosure: ["title_agent_id"],
  closing_disclosure_agreement: ["agent_id"],
  conversation_logs: ["agent_id"],
  fatigue_alerts: ["agent_user_id"],
  income_forecast_snapshots: ["agent_id"],
  learning_assignments: ["agent_user_id"],
  lifetime_customer_npv_scores: ["agent_id"],
  listing_agreements: ["agent_user_id"],
  listing_health_interventions: ["agent_id"],
  listing_health_scores: ["agent_id"],
  listing_packet_jobs: ["agent_user_id"],
  listing_presentations: ["agent_user_id"],
  listing_promo_videos: ["agent_id"],
  marketing_assets: ["agent_user_id"],
  marketing_campaigns: ["agent_user_id"],
  message_threads: ["agent_user_id"],
  negotiation_strategies: ["agent_user_id"],
  neighbor_notification_campaigns: ["agent_user_id"],
  newsletter_scheduled_sends: ["agent_id"],
  newsletter_video_renders: ["agent_id"],
  objection_training_sessions: ["agent_user_id"],
  pattern_adoptions: ["agent_id"],
  platform_credentials: ["agent_user_id"],
  podcast_auto_runs: ["agent_id"],
  podcast_episodes: ["agent_id"],
  podcast_templates: ["agent_id"],
  portal_event_stream: ["agent_user_id"],
  property_alerts: ["agent_user_id"],
  property_interests: ["agent_user_id"],
  property_preferences: ["agent_id"],
  repurpose_pipelines: ["agent_user_id"],
  revenue_protection_snapshots: ["agent_id"],
  review_requests: ["agent_id"],
  seo_keywords: ["agent_user_id"],
  strategy_recommendations: ["agent_user_id"],
  studio_sessions: ["agent_id"],
  transparency_updates: ["agent_id"],
  workflow_intake_sessions: ["agent_user_id"],
  workflow_runs: ["agent_user_id"],
}

/**
 * Tables whose `contact_id` FKs public.contacts(id), snapshotted from live.
 *
 * A LEAD is not a CONTACT. Writing a lead id here is FK-rejected and the row is
 * silently lost — the registry records a pass that fixed this, but three sites
 * survived it: the ISA inbound-intent nurture log, three ISA tool writes, and every
 * lead-readiness transition. The repo's own correct shape is
 * `contact_id: null, entity_type: "lead", entity_id: <leadId>`.
 */
export const CONTACT_FK_TABLES: string[] = [
  "activities",
  "ai_assistant_notes",
  "ai_autopilot_plans",
  "ai_isa_activities",
  "ai_isa_calls",
  "ai_isa_engagement_tracking",
  "ai_isa_qualifications",
  "ai_message_drafts",
  "appointments",
  "behavioral_signals",
  "calculator_history",
  "call_analyses",
  "chat_sessions",
  "client_portal_messages",
  "communication_audit_log",
  "communications",
  "compliance_flags",
  "contact_consent_events",
  "contact_notes",
  "conversation_insights",
  "conversation_logs",
  "conversations",
  "copilot_plans",
  "documents",
  "drip_campaigns",
  "email_sends",
  "email_tracking",
  "fair_housing_logs",
  "fatigue_alerts",
  "form_submissions",
  "generated_content",
  "isa_outreach_log",
  "journey_states",
  "lead_enrichment_queue",
  "lead_score_history",
  "lead_scores",
  "lead_value_journey",
  "message_threads",
  "messages",
  "notifications",
  "property_alerts",
  "property_interests",
  "property_search_log",
  "property_views",
  "scheduled_touchpoints",
  "sequence_enrollments",
  "sequence_step_executions",
  "signal_reactivations",
  "site_activity",
  "smart_showing_recommendations",
  "tasks",
  "transactions",
  "unified_lead_profile",
  "usage_events",
  "voice_calls",
  "website_visitors",
  "workflow_runs",
]
