/**
 * scripts/schema-fk-map.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * GENERATED from the live Postgres schema (public) — the FOREIGN-KEY half of the
 * schema-drift guard's static picture of the database.
 *
 * WHY THIS FILE EXISTS
 * scripts/schema-snapshot.ts answers "does table T have column C?". It cannot answer
 * "what table does this PostgREST embed point at?", and that question is the whole
 * reason embedded selects went unchecked for so long. PostgREST lets an embed name its
 * target three ways:
 *
 *     brokerages(name, city)                 — by TABLE name        → resolved by SCHEMA_SNAPSHOT
 *     brokerage_id(name, city)               — by FK COLUMN name    → resolved by THIS map
 *     brokerage:brokerage_id(name, city)     — aliased FK column    → resolved by THIS map
 *
 * Only the first form is resolvable from the column snapshot alone. The other two need
 * the FK graph, so it is committed here rather than read from a live connection: the
 * guard must keep running offline, with no credentials, exactly as it does today.
 *
 * SAFETY PROPERTY
 * A missing or stale entry can only cause the guard to SKIP an embed (reported on the
 * "unresolved embeds" line), never to fail one. Staleness costs coverage, not trust.
 *
 * MEASURED WHEN GENERATED: 1792 foreign keys in `public`, every one single-column, and
 * NO (table, column) pair carries FKs to two different targets — so this map is total
 * and unambiguous. No FK column name in the schema collides with a table name, so the
 * table-name and FK-column resolution paths cannot disagree.
 *
 * REGENERATE after any schema change that adds/drops/renames a foreign key:
 *
 *   WITH fk AS (
 *     SELECT DISTINCT src.relname AS src_table, a.attname AS src_col, tgt.relname AS tgt_table
 *     FROM pg_constraint c
 *     JOIN pg_class src ON src.oid = c.conrelid
 *     JOIN pg_namespace sn ON sn.oid = src.relnamespace
 *     JOIN pg_class tgt ON tgt.oid = c.confrelid
 *     JOIN pg_namespace tn ON tn.oid = tgt.relnamespace
 *     JOIN unnest(c.conkey) AS k(attnum) ON true
 *     JOIN pg_attribute a ON a.attrelid = src.oid AND a.attnum = k.attnum
 *     WHERE c.contype='f' AND sn.nspname='public' AND tn.nspname='public'
 *   ), per AS (
 *     SELECT src_table, json_object_agg(src_col, tgt_table ORDER BY src_col) AS cols
 *     FROM fk GROUP BY src_table
 *   )
 *   SELECT json_object_agg(src_table, cols ORDER BY src_table) FROM per;
 *
 * Last synced: 2026-08-15.
 */

/** `SCHEMA_FK_MAP[sourceTable][fkColumn] = targetTable` */
export const SCHEMA_FK_MAP: Record<string, Record<string, string>> = {
  "accounting_sync_log": { "brokerage_id": "brokerages" },
  "activities": { "agent_id": "agents", "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions" },
  "ad_campaigns": { "agent_user_id": "users", "brokerage_id": "brokerages", "created_by": "users", "marketing_campaign_id": "marketing_campaigns", "team_id": "teams" },
  "ad_creative_variations": { "ad_campaign_id": "ad_campaigns", "brokerage_id": "brokerages", "competitor_ad_id": "competitor_ads", "source_marketing_asset_id": "marketing_assets" },
  "ad_insights": { "brokerage_id": "brokerages" },
  "ad_manager_actions": { "approved_by": "users", "brokerage_id": "brokerages" },
  "ad_performance": { "ad_campaign_id": "ad_campaigns", "brokerage_id": "brokerages", "creative_variation_id": "ad_creative_variations" },
  "ad_performance_history": { "brokerage_id": "brokerages" },
  "ad_retarget_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events", "facebook_audience_id": "facebook_custom_audiences" },
  "affiliate_commission_events": { "affiliate_id": "platform_affiliates", "brokerage_id": "brokerages", "referral_id": "affiliate_referrals" },
  "affiliate_referrals": { "affiliate_id": "platform_affiliates", "brokerage_id": "brokerages" },
  "agent_achievements": { "achievement_id": "achievements", "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_api_credentials": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_assistant_sessions": { "agent_id": "agents", "brokerage_id": "brokerages", "context_contact_id": "contacts", "context_listing_id": "listings", "context_transaction_id": "transactions", "user_id": "users" },
  "agent_assistant_tool_calls": { "brokerage_id": "brokerages", "session_id": "agent_assistant_sessions" },
  "agent_avatar_assets": { "agent_id": "agents", "approved_by": "users", "brokerage_id": "brokerages" },
  "agent_badges": { "agent_id": "agents", "badge_id": "gamification_badges", "brokerage_id": "brokerages" },
  "agent_cap_tracking": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_ce_completions": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_certifications": { "agent_id": "agents", "brokerage_id": "brokerages", "issued_by": "users" },
  "agent_chat_preferences": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_client_messages": { "approved_by": "users", "brokerage_id": "brokerages" },
  "agent_commission_profiles": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_commissions": { "agent_id": "agents", "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "agent_coordination_log": { "brokerage_id": "brokerages" },
  "agent_credentials": { "brokerage_id": "brokerages" },
  "agent_credit_budgets": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_did_consents": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_earnings": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_fee_assignments": { "agent_id": "agents", "brokerage_id": "brokerages", "fee_type_id": "brokerage_fee_types" },
  "agent_fee_charges": { "agent_id": "agents", "brokerage_id": "brokerages", "fee_type_id": "brokerage_fee_types" },
  "agent_goals": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_handoffs": { "brokerage_id": "brokerages", "human_agent_id": "agents" },
  "agent_intro_videos": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "video_project_id": "ai_video_projects" },
  "agent_learning_paths": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_licenses": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_mentor_relationships": { "brokerage_id": "brokerages", "mentee_agent_id": "agents", "mentor_agent_id": "agents" },
  "agent_metrics": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_monthly_earnings": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_notifications": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_onboarding": { "agent_id": "agents", "brokerage_id": "brokerages", "user_id": "users" },
  "agent_onboarding_sessions": { "agent_id": "agents", "brokerage_id": "brokerages", "facilitator_user_id": "users" },
  "agent_onboarding_steps": { "agent_id": "agents", "brokerage_id": "brokerages", "session_id": "agent_onboarding_sessions" },
  "agent_outcome_evaluations": { "brokerage_id": "brokerages", "managed_agent_session_id": "managed_agent_sessions" },
  "agent_performance_reports": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_pl_snapshot": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_points_log": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agent_quiz_attempts": { "agent_id": "agents", "brokerage_id": "brokerages", "quiz_id": "onboarding_quizzes" },
  "agent_relationships": { "agent_id": "agents", "brokerage_id": "brokerages", "sponsor_agent_id": "agents" },
  "agent_reviews": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions" },
  "agent_social_shares": { "agent_user_id": "users", "brokerage_id": "brokerages", "social_post_id": "social_posts" },
  "agent_state_machine": { "brokerage_id": "brokerages" },
  "agent_step_completions": { "agent_id": "agents", "brokerage_id": "brokerages", "step_id": "onboarding_steps" },
  "agent_voice_profiles": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "agents": { "brokerage_id": "brokerages", "covering_agent_id": "agents", "location_id": "locations", "team_id": "teams", "user_id": "users" },
  "ai_agent_templates": { "brokerage_id": "brokerages" },
  "ai_assistant_notes": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads", "listing_id": "listings", "transaction_id": "transactions" },
  "ai_autopilot_actions": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "ai_autopilot_plans": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "ai_comp_scores": { "brokerage_id": "brokerages", "cma_id": "cma_reports", "comparable_id": "cma_comparables", "listing_id": "listings" },
  "ai_content_outputs": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "ai_daily_briefings": { "agent_id": "agents", "brokerage_id": "brokerages", "user_id": "users" },
  "ai_feedback_log": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "ai_generated_content": { "user_id": "users" },
  "ai_identity_profiles": { "brokerage_id": "brokerages", "parent_scope_id": "ai_identity_profiles" },
  "ai_improvement_metrics": { "brokerage_id": "brokerages" },
  "ai_insights": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "ai_isa_activities": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "ai_isa_call_batches": { "approved_by": "users", "brokerage_id": "brokerages", "proposed_by_agent_id": "agents" },
  "ai_isa_calls": { "contact_id": "contacts", "lead_id": "leads", "voice_call_id": "voice_calls" },
  "ai_isa_campaigns": { "brokerage_id": "brokerages" },
  "ai_isa_engagement_tracking": { "brokerage_id": "brokerages", "campaign_id": "ai_isa_campaigns", "contact_id": "contacts", "lead_id": "leads", "outreach_id": "isa_outreach_log" },
  "ai_isa_qualifications": { "agent_id": "agents", "assigned_to_agent_id": "users", "brokerage_id": "brokerages", "campaign_id": "ai_isa_campaigns", "contact_id": "contacts", "lead_id": "leads" },
  "ai_isa_settings": { "brokerage_id": "brokerages" },
  "ai_listing_optimizations": { "transaction_id": "transactions" },
  "ai_message_drafts": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "conversation_id": "conversations", "listing_id": "listings", "sent_message_id": "messages", "source_message_id": "messages" },
  "ai_predictions": { "brokerage_id": "brokerages" },
  "ai_quota_overrides": { "approved_by": "users", "brokerage_id": "brokerages", "requested_by": "users" },
  "ai_search_citation_observations": { "agent_id": "agents", "brokerage_id": "brokerages", "project_id": "ai_video_projects", "team_id": "teams" },
  "ai_search_landing_citation_observations": { "agent_id": "agents", "brokerage_id": "brokerages", "form_id": "lead_capture_forms", "team_id": "teams" },
  "ai_subscription_tier": { "admin_user_id": "users", "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "ai_suggestions": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "ai_tool_usage": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams", "user_id": "users" },
  "ai_usage_log": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "ai_usage_monthly": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "ai_video_projects": { "agent_id": "agents", "approved_by": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "marketing_campaign_id": "marketing_campaigns", "rejected_by": "users", "source_script_id": "scripts", "studio_session_id": "studio_sessions" },
  "api_response_logs": { "brokerage_id": "brokerages" },
  "appointments": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "approval_items": { "agent_id": "agents", "brokerage_id": "brokerages", "reviewed_by": "users" },
  "approved_content_library": { "brokerage_id": "brokerages", "created_by": "users" },
  "asset_manager_actions": { "brokerage_id": "brokerages" },
  "asset_persona_renders": { "brokerage_id": "brokerages" },
  "assignment_log": { "agent_id": "agents", "brokerage_id": "brokerages", "lead_id": "leads", "rule_id": "assignment_rules" },
  "assignment_rules": { "brokerage_id": "brokerages", "created_by": "users", "team_id": "teams" },
  "audience_members": { "audience_id": "facebook_custom_audiences", "brokerage_id": "brokerages" },
  "audience_sync_runs": { "audience_id": "facebook_custom_audiences", "brokerage_id": "brokerages" },
  "audit_log": { "user_id": "users" },
  "auto_response_settings": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "automation_errors": { "assigned_by": "users", "assigned_to": "users", "brokerage_id": "brokerages", "dismissed_by": "users", "lead_id": "leads", "resolved_by": "users" },
  "automation_logs": { "brokerage_id": "brokerages" },
  "batchdata_motivated_sellers_raw": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "behavioral_patterns": { "brokerage_id": "brokerages" },
  "behavioral_signals": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "billing_invoices": { "brokerage_id": "brokerages", "subscription_id": "subscriptions" },
  "billing_usage": { "brokerage_id": "brokerages", "subscription_id": "subscriptions" },
  "blog_cadence_policy": { "updated_by": "users" },
  "blog_post_keywords": { "blog_post_id": "blog_posts", "brokerage_id": "brokerages", "seo_keyword_id": "seo_keywords" },
  "blog_post_share_clicks": { "blog_post_id": "blog_posts", "brokerage_id": "brokerages", "viewer_contact_id": "contacts" },
  "blog_post_views": { "blog_post_id": "blog_posts", "brokerage_id": "brokerages", "viewer_contact_id": "contacts" },
  "blog_posts": { "agent_user_id": "users", "brokerage_id": "brokerages", "created_by": "users", "marketing_campaign_id": "marketing_campaigns", "team_id": "teams" },
  "brand_asset_library": { "brokerage_id": "brokerages" },
  "brand_templates": { "brokerage_id": "brokerages" },
  "brand_voice_profile": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "brokerage_brand_settings": { "brokerage_id": "brokerages" },
  "brokerage_cda_template_fields": { "template_id": "brokerage_cda_templates" },
  "brokerage_cda_templates": { "brokerage_id": "brokerages", "uploaded_by": "users" },
  "brokerage_earnings": { "brokerage_id": "brokerages" },
  "brokerage_fee_types": { "brokerage_id": "brokerages" },
  "brokerage_form_library": { "brokerage_id": "brokerages", "uploaded_by": "users" },
  "brokerage_forms": { "brokerage_id": "brokerages", "created_by": "users" },
  "brokerage_integrations": { "brokerage_id": "brokerages" },
  "brokerage_intelligence_insights": { "brokerage_id": "brokerages", "dismissed_by": "users" },
  "brokerage_p_l": { "brokerage_id": "brokerages" },
  "brokerage_required_documents": { "brokerage_id": "brokerages", "created_by": "users", "template_form_id": "brokerage_form_library" },
  "brokerage_settings": { "brokerage_id": "brokerages" },
  "brokerages": { "ai_isa_system_user_id": "users" },
  "budgets": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "business_card_scans": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "reviewed_by": "users" },
  "business_expenses": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "buyer_behavior_log": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "buyer_behavior_predictions": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "buyer_broker_agreements": { "agent_id": "agents", "brokerage_id": "brokerages", "buyer_contact_id": "contacts", "cancelled_by": "users", "created_by": "users", "superseded_by": "buyer_broker_agreements" },
  "buyer_fatigue_scores": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "buyer_financial_profiles": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "lender_referred_partner_id": "referral_partners", "verified_by": "users" },
  "buyer_intake_tokens": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "buyer_stage_coaching": { "brokerage_id": "brokerages" },
  "buyer_tours": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "calculator_history": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "calendar_blocks": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "calendar_provider_accounts": { "brokerage_id": "brokerages", "user_id": "users" },
  "calendar_sync_conflicts": { "brokerage_id": "brokerages", "calendar_event_id": "calendar_events", "provider_account_id": "calendar_provider_accounts", "resolved_by_user_id": "users" },
  "calendar_sync_logs": { "brokerage_id": "brokerages", "provider_account_id": "calendar_provider_accounts" },
  "calendar_sync_mappings": { "brokerage_id": "brokerages", "calendar_event_id": "calendar_events", "provider_account_id": "calendar_provider_accounts" },
  "call_analyses": { "agent_id": "agents", "contact_id": "contacts", "voice_call_id": "voice_calls" },
  "call_coaching_insights": { "agent_id": "agents", "call_analysis_id": "call_analyses" },
  "call_transcriptions": { "voice_call_id": "voice_calls" },
  "call_whisper_logs": { "voice_call_id": "voice_calls" },
  "campaign_bundle_dispatches": { "brokerage_id": "brokerages", "bundle_id": "campaign_bundles" },
  "campaign_bundle_items": { "brokerage_id": "brokerages", "bundle_id": "campaign_bundles" },
  "campaign_bundles": { "brokerage_id": "brokerages" },
  "campaign_calendar": { "agent_user_id": "users", "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns", "team_id": "teams" },
  "campaign_roi": { "brokerage_id": "brokerages", "marketing_campaign_id": "marketing_campaigns" },
  "campaign_sequence_steps": { "sequence_id": "campaign_sequences" },
  "campaign_sequences": { "brokerage_id": "brokerages", "created_by": "users" },
  "cda_comparison_results": { "cda_id": "closing_disclosure_agreement" },
  "challenge_participants": { "challenge_id": "challenges" },
  "channel_performance": { "brokerage_id": "brokerages" },
  "chat_messages": { "session_id": "chat_sessions" },
  "chat_sessions": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "chat_templates": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "client_detailed_personas": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "client_documents": { "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions", "uploaded_by": "users", "verified_by": "users" },
  "client_engagement_scores": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "client_friendly_updates": { "transaction_id": "transactions" },
  "client_gifts": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions" },
  "client_portal_activity": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "client_portal_messages": { "agent_id": "agents", "contact_id": "contacts" },
  "closing_checklist_items": { "transaction_id": "transactions" },
  "closing_cost_accuracy_observations": { "brokerage_id": "brokerages" },
  "closing_disclosure": { "brokerage_id": "brokerages", "title_agent_id": "users", "transaction_id": "transactions" },
  "closing_disclosure_agreement": { "agent_id": "agents", "agent_signed_off_by": "users", "agent_submitted_by": "users", "broker_id": "users", "brokerage_id": "brokerages", "cda_template_id": "brokerage_cda_templates", "changes_requested_by": "users", "compliance_approved_by": "users", "final_cd_uploaded_by": "users", "manual_override_by": "users", "preliminary_cd_document_id": "transaction_documents", "preliminary_cd_uploaded_by": "users", "transaction_id": "transactions" },
  "closing_disclosure_agreement_revisions": { "acted_by": "users", "cda_id": "closing_disclosure_agreement" },
  "closing_gifts": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "closing_notifications": { "brokerage_id": "brokerages", "sent_to_user_id": "users", "transaction_id": "transactions" },
  "cma_comparables": { "cma_id": "cma_reports" },
  "cma_packages": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "cma_price_adjustments": { "cma_report_id": "cma_reports" },
  "cma_reports": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "collaborative_search_members": { "collaborative_search_id": "collaborative_searches" },
  "collaborative_search_properties": { "added_by_contact_id": "contacts", "collaborative_search_id": "collaborative_searches" },
  "collaborative_searches": { "brokerage_id": "brokerages", "contact_id": "contacts", "created_by_contact_id": "contacts" },
  "commission_adjustments": { "approved_by_agent_id": "agents", "brokerage_id": "brokerages", "created_by_agent_id": "agents", "transaction_id": "transactions" },
  "commission_calculations": { "agent_id": "agents", "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "commission_distributions": { "agent_id": "agents", "brokerage_id": "brokerages", "commission_id": "agent_commissions", "rule_id": "commission_rules", "team_id": "teams", "transaction_id": "transactions" },
  "commission_rules": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "commission_splits": { "agent_id": "agents", "brokerage_id": "brokerages", "location_id": "locations", "transaction_id": "transactions" },
  "commission_structures": { "brokerage_id": "brokerages" },
  "communication_audit_log": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "user_id": "users" },
  "communications": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "comp_risk_flags": { "brokerage_id": "brokerages", "cma_id": "cma_reports", "listing_id": "listings" },
  "competitor_ads": { "brokerage_id": "brokerages", "competitor_id": "competitor_brokerages" },
  "competitor_brokerages": { "brokerage_id": "brokerages" },
  "competitor_content": { "brokerage_id": "brokerages", "competitor_id": "competitor_profiles" },
  "competitor_posts": { "brokerage_id": "brokerages" },
  "competitor_profiles": { "brokerage_id": "brokerages" },
  "competitors": { "brokerage_id": "brokerages" },
  "compliance_alerts": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "compliance_checklists": { "transaction_id": "transactions" },
  "compliance_checks": { "brokerage_id": "brokerages" },
  "compliance_events": { "actor_user_id": "users", "brokerage_id": "brokerages" },
  "compliance_flags": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "user_id": "users" },
  "compliance_tasks": { "agent_id": "agents", "brokerage_id": "brokerages", "completed_by": "users", "transaction_id": "transactions" },
  "connector_health_log": { "brokerage_id": "brokerages" },
  "contact_consent_events": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "contact_enrichment_queue": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "contact_memory": { "brokerage_id": "brokerages" },
  "contact_notes": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "contact_portal_modules": { "brokerage_id": "brokerages", "contact_id": "contacts", "enabled_by_agent_id": "agents" },
  "contact_portal_preferences": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "contact_segments": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "contact_suppression_list": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "contact_vendors": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions", "vendor_id": "vendors" },
  "contacts": { "agent_id": "agents", "brokerage_id": "brokerages", "campaign_attribution_id": "marketing_campaigns", "compliance_officer_id": "users", "embed_widget_id": "embed_widgets", "isa_reengage_marked_by": "users", "location_id": "locations", "source_agent_id": "users", "tc_user_id": "users", "tcpa_marked_by": "users", "team_id": "teams", "user_id": "users" },
  "content_ab_tests": { "agent_id": "agents", "brokerage_id": "brokerages", "variant_a_id": "ai_generated_content", "variant_b_id": "ai_generated_content", "winner_id": "ai_generated_content" },
  "content_asset_persona_performance": { "topic_id": "content_topic_bank" },
  "content_calendar": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "content_generation_logs": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "content_ideas": { "brokerage_id": "brokerages", "created_by": "users" },
  "content_performance_predictions": { "brokerage_id": "brokerages" },
  "content_performance_tracking": { "agent_id": "agents", "brokerage_id": "brokerages", "content_id": "ai_generated_content" },
  "content_templates": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "content_topic_bank": { "brokerage_id": "brokerages", "source_id": "content_topic_sources" },
  "content_topic_sources": { "brokerage_id": "brokerages" },
  "content_topic_uses": { "agent_id": "agents", "brokerage_id": "brokerages", "topic_id": "content_topic_bank" },
  "contract_reviews": { "agent_id": "agents", "brokerage_id": "brokerages", "document_id": "transaction_documents", "transaction_id": "transactions" },
  "contract_signatures": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "conversation_audit_flags": { "conversation_id": "conversation_logs", "reviewed_by": "users" },
  "conversation_insights": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "conversation_id": "conversations" },
  "conversation_intelligence": { "agent_id": "agents", "brokerage_id": "brokerages", "lead_id": "leads" },
  "conversation_logs": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "conversations": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "copilot_plans": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "cost_allocation": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "cost_breakdown_tracking": { "transaction_id": "transactions" },
  "credit_accounts": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "credit_conversation_logs": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "credit_partner_referrals": { "brokerage_id": "brokerages", "contact_id": "contacts", "partner_id": "referral_partners" },
  "credit_status": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "cron_execution_logs": { "brokerage_id": "brokerages" },
  "data_health_logs": { "brokerage_id": "brokerages", "contact_id": "contacts", "scan_id": "data_health_scans" },
  "data_health_scans": { "brokerage_id": "brokerages" },
  "data_subject_requests": { "brokerage_id": "brokerages", "fulfilled_by": "users", "identity_verified_by": "users", "subject_contact_id": "contacts", "subject_user_id": "users" },
  "deal_autopsies": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "deal_autopsy_observations": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "deal_health_components": { "score_run_id": "deal_health_scores", "transaction_id": "transactions" },
  "deal_health_factors": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "deal_health_scores": { "transaction_id": "transactions" },
  "deal_health_snapshots": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "deal_team_members": { "transaction_id": "transactions" },
  "deconflict_suppression_log": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "demo_persona_contacts": { "contact_id": "contacts" },
  "deposits": { "agent_id": "agents", "brokerage_id": "brokerages", "created_by": "users", "transaction_id": "transactions" },
  "direct_mail_campaigns": { "agent_id": "agents", "brokerage_id": "brokerages", "bundle_dispatch_id": "campaign_bundle_dispatches", "compliance_event_id": "compliance_events", "created_by": "users", "lead_id": "leads", "marketing_campaign_id": "marketing_campaigns", "preset_id": "direct_mail_presets", "qr_code_id": "qr_codes", "variant_id": "direct_mail_variants" },
  "direct_mail_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "direct_mail_recipients": { "brokerage_id": "brokerages", "campaign_id": "direct_mail_campaigns", "contact_id": "contacts" },
  "direct_mail_responses": { "brokerage_id": "brokerages", "campaign_id": "direct_mail_campaigns", "contact_id": "contacts", "recipient_id": "direct_mail_recipients" },
  "direct_mail_variant_outcomes": { "brokerage_id": "brokerages", "variant_id": "direct_mail_variants" },
  "direct_mail_variants": { "brokerage_id": "brokerages" },
  "document_checklist": { "brokerage_id": "brokerages", "transaction_id": "transactions", "verified_by_user_id": "users" },
  "document_downloads": { "brokerage_id": "brokerages" },
  "document_extraction_log": { "transaction_doc_id": "transaction_documents", "transaction_id": "transactions" },
  "document_field_audit": { "document_id": "documents" },
  "document_field_extractions": { "brokerage_id": "brokerages", "document_id": "documents" },
  "document_folders": { "brokerage_id": "brokerages", "parent_folder_id": "document_folders", "related_contact_id": "contacts", "related_lead_id": "leads", "related_transaction_id": "transactions" },
  "document_requests": { "brokerage_id": "brokerages", "contact_id": "contacts", "transaction_id": "transactions" },
  "document_retention": { "brokerage_id": "brokerages" },
  "document_sharing_links": { "brokerage_id": "brokerages" },
  "documents": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions" },
  "drip_campaigns": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "earnings_history": { "agent_id": "agents", "brokerage_id": "brokerages", "commission_id": "agent_commissions", "transaction_id": "transactions" },
  "email_campaigns": { "brokerage_id": "brokerages", "marketing_campaign_id": "marketing_campaigns", "parent_campaign_id": "email_campaigns" },
  "email_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "email_sends": { "brokerage_id": "brokerages", "campaign_id": "email_campaigns", "contact_id": "contacts" },
  "email_templates": { "brokerage_id": "brokerages" },
  "email_tracking": { "brokerage_id": "brokerages", "contact_id": "contacts", "email_send_id": "email_sends" },
  "embed_sessions": { "brokerage_id": "brokerages", "contact_id": "contacts", "embed_widget_id": "embed_widgets" },
  "embed_widgets": { "agent_id": "agents", "brokerage_id": "brokerages", "default_twin_id": "agent_avatar_assets", "last_routed_agent_id": "agents", "team_id": "teams" },
  "error_resolution_log": { "action_by_user_id": "users", "brokerage_id": "brokerages", "error_id": "automation_errors" },
  "error_stack_traces": { "brokerage_id": "brokerages", "error_id": "automation_errors" },
  "event_processing_log": { "brokerage_id": "brokerages", "event_id": "lifecycle_events" },
  "external_behavior": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "facebook_custom_audiences": { "ad_campaign_id": "ad_campaigns", "brokerage_id": "brokerages", "lookalike_seed_audience_id": "facebook_custom_audiences" },
  "fair_housing_logs": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "farm_territories": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "fatigue_alerts": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "dismissed_by": "users" },
  "feature_access_overrides": { "brokerage_id": "brokerages", "created_by": "users", "feature_key": "feature_flags", "team_id": "teams", "user_id": "users" },
  "feature_usage_tracking": { "brokerage_id": "brokerages", "feature_key": "feature_flags", "team_id": "teams", "user_id": "users" },
  "financial_reports": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "form_submissions": { "brokerage_id": "brokerages", "contact_id": "contacts", "form_id": "lead_capture_forms" },
  "gamification_badges": { "brokerage_id": "brokerages" },
  "generated_content": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "prospect_id": "prospects" },
  "generated_documents": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions" },
  "gift_vendors": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "global_settings": { "brokerage_id": "brokerages", "created_by_user_id": "users" },
  "google_search_activity": { "brokerage_id": "brokerages" },
  "google_search_intelligence": { "brokerage_id": "brokerages" },
  "hashtag_performance": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "health_check_history": { "brokerage_id": "brokerages" },
  "health_metrics": { "brokerage_id": "brokerages" },
  "help_topics_kb": { "brokerage_id": "brokerages" },
  "home_value_estimates": { "brokerage_id": "brokerages", "contact_id": "contacts", "valuation_request_id": "valuation_requests" },
  "home_value_page_configs": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "income_forecast_gap_analysis": { "agent_id": "agents", "brokerage_id": "brokerages", "forecast_snapshot_id": "income_forecast_snapshots" },
  "income_forecast_snapshots": { "agent_id": "agents", "brokerage_id": "brokerages", "previous_snapshot_id": "income_forecast_snapshots" },
  "income_gap_recommended_actions": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "gap_analysis_id": "income_forecast_gap_analysis", "listing_id": "listings", "transaction_id": "transactions" },
  "integration_credentials": { "brokerage_id": "brokerages" },
  "intelligence_signals_log": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "intelligent_outreach_log": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "isa_outreach_log": { "agent_id": "agents", "brokerage_id": "brokerages", "calendar_event_id": "calendar_events", "contact_id": "contacts", "lead_id": "leads" },
  "journey_stage_progress": { "contact_id": "contacts" },
  "journey_states": { "brokerage_id": "brokerages", "contact_id": "contacts", "deal_id": "transactions", "listing_id": "listings" },
  "journey_task_completions": { "brokerage_id": "brokerages", "contact_id": "contacts", "stage_progress_id": "journey_stage_progress" },
  "keyword_intelligence": { "brokerage_id": "brokerages" },
  "knowledge_articles": { "author_id": "users", "brokerage_id": "brokerages" },
  "lead_behavioral_data": { "brokerage_id": "brokerages" },
  "lead_capture_forms": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "lead_conversation_history": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "lead_deduplication_log": { "brokerage_id": "brokerages" },
  "lead_engagement_scores": { "brokerage_id": "brokerages" },
  "lead_enrichment_queue": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "lead_external_behavior": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "lead_idx_property_interactions": { "brokerage_id": "brokerages" },
  "lead_imports": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "lead_intelligence": { "brokerage_id": "brokerages" },
  "lead_magnet_submissions": { "brokerage_id": "brokerages", "form_id": "lead_magnets" },
  "lead_magnets": { "brokerage_id": "brokerages" },
  "lead_motivated_seller_signals": { "brokerage_id": "brokerages" },
  "lead_osint_data": { "brokerage_id": "brokerages" },
  "lead_people_data": { "brokerage_id": "brokerages" },
  "lead_property_ownership": { "brokerage_id": "brokerages" },
  "lead_property_searches": { "brokerage_id": "brokerages" },
  "lead_score_history": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "lead_scores": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "lead_scraping_jobs": { "brokerage_id": "brokerages", "market_id": "lead_scraping_markets" },
  "lead_scraping_keywords": { "brokerage_id": "brokerages" },
  "lead_scraping_markets": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "lead_scraping_motivated_params": { "market_id": "lead_scraping_markets" },
  "lead_scraping_property_params": { "market_id": "lead_scraping_markets" },
  "lead_sla_tracking": { "agent_id": "agents", "brokerage_id": "brokerages", "lead_id": "leads" },
  "lead_social_intelligence": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "lead_value_journey": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "leaderboard_rankings": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "leads": { "agent_id": "agents", "brokerage_id": "brokerages", "campaign_attribution_id": "marketing_campaigns", "contact_id": "contacts", "distribution_brokerage_id": "brokerages" },
  "learning_assignments": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "module_id": "learning_modules", "staff_user_id": "users" },
  "learning_module_channel_publications": { "brokerage_id": "brokerages", "module_id": "learning_modules" },
  "learning_modules": { "approved_by": "users", "authored_by": "users", "brokerage_id": "brokerages", "rejected_by": "users", "team_id": "teams" },
  "lender_applications": { "brokerage_id": "brokerages", "contact_id": "contacts", "lender_id": "vendors", "transaction_id": "transactions" },
  "license_verifications": { "brokerage_id": "brokerages", "license_id": "agent_licenses", "verified_by_user_id": "users" },
  "lifecycle_events": { "actor_user_id": "users", "brokerage_id": "brokerages" },
  "lifecycle_promo_policy": { "updated_by": "users" },
  "lifetime_customer_npv_scores": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "lifetime_customer_touchpoints": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "related_transaction_id": "transactions" },
  "listing_agreements": { "agent_user_id": "users", "brokerage_id": "brokerages", "listing_id": "listings", "seller_contact_id": "contacts" },
  "listing_engagement": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "listing_health_interventions": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings", "resolved_by": "users" },
  "listing_health_scores": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_inquiries": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_landing_pages": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "listing_marketing_content": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_marketing_packages": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "listing_marketing_services": { "brokerage_id": "brokerages", "package_id": "listing_marketing_packages", "transaction_id": "transactions", "vendor_id": "vendors" },
  "listing_marketing_tiers": { "brokerage_id": "brokerages" },
  "listing_media": { "approved_by": "users", "brokerage_id": "brokerages", "listing_id": "listings", "template_id": "video_templates", "uploaded_by": "users" },
  "listing_metrics": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_packet_jobs": { "agent_user_id": "users", "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_page_analytics": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_presentations": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "delivery_approved_by": "users", "packet_document_id": "documents" },
  "listing_price_changes": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings" },
  "listing_promo_videos": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings", "video_project_id": "ai_video_projects" },
  "listing_stage_history": { "brokerage_id": "brokerages", "completed_by": "users", "listing_id": "listings" },
  "listing_syndication_tracking": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "listing_task_templates": { "brokerage_id": "brokerages" },
  "listings": { "agent_id": "agents", "appointment_event_id": "calendar_events", "brokerage_id": "brokerages", "contact_id": "contacts", "location_id": "locations", "marketing_tier_id": "listing_marketing_tiers", "seller_contact_id": "contacts", "team_id": "teams" },
  "local_news_sources": { "brokerage_id": "brokerages" },
  "locations": { "brokerage_id": "brokerages" },
  "long_form_videos": { "script_id": "scripts" },
  "mail_response_tracking": { "brokerage_id": "brokerages", "campaign_id": "direct_mail_campaigns", "contact_id": "contacts" },
  "mail_tracking": { "brokerage_id": "brokerages", "campaign_id": "direct_mail_campaigns" },
  "managed_agent_sessions": { "brokerage_id": "brokerages", "managed_agent_id": "managed_agents" },
  "managed_agents": { "brokerage_id": "brokerages" },
  "manager_signals": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "market_data": { "brokerage_id": "brokerages" },
  "market_data_sources": { "brokerage_id": "brokerages" },
  "market_insights": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "market_pulse": { "brokerage_id": "brokerages" },
  "market_trends": { "brokerage_id": "brokerages" },
  "marketing_agent_actions": { "approved_by": "users", "brokerage_id": "brokerages", "managed_agent_session_id": "managed_agent_sessions" },
  "marketing_agent_weekly_outcomes": { "brokerage_id": "brokerages" },
  "marketing_asset_qr_links": { "brokerage_id": "brokerages", "marketing_asset_id": "marketing_assets", "qr_code_id": "qr_codes" },
  "marketing_assets": { "agent_user_id": "users", "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns", "created_by": "users", "team_id": "teams" },
  "marketing_attribution_credits": { "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns", "contact_id": "contacts", "transaction_id": "transactions" },
  "marketing_campaign_comments": { "author_user_id": "users", "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns" },
  "marketing_campaign_tasks": { "assigned_user_id": "users", "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns" },
  "marketing_campaign_touchpoints": { "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns", "contact_id": "contacts", "sequence_id": "campaign_sequences" },
  "marketing_campaign_triggers": { "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns" },
  "marketing_campaigns": { "agent_user_id": "users", "brokerage_id": "brokerages", "created_by": "users", "listing_id": "listings", "source_script_id": "video_scripts_library", "source_video_project_id": "ai_video_projects", "team_id": "teams" },
  "marketing_channel_settings": { "brokerage_id": "brokerages" },
  "meeting_briefs": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "mentor_sessions": { "relationship_id": "agent_mentor_relationships" },
  "message_provider_logs": { "brokerage_id": "brokerages", "message_id": "messages", "outreach_log_id": "isa_outreach_log" },
  "message_threads": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "messages": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "conversation_id": "conversations" },
  "meter_readings": { "brokerage_id": "brokerages" },
  "milestone_template_items": { "template_id": "transaction_milestone_templates" },
  "model_retraining_log": { "brokerage_id": "brokerages" },
  "motivated_seller_signals": { "brokerage_id": "brokerages" },
  "narration_cache": { "brokerage_id": "brokerages" },
  "negotiation_strategies": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "offer_id": "offers" },
  "neighbor_notification_campaigns": { "agent_user_id": "users", "brokerage_id": "brokerages", "direct_mail_campaign_id": "direct_mail_campaigns", "listing_id": "listings" },
  "neighbor_notification_recipients": { "brokerage_id": "brokerages", "campaign_id": "neighbor_notification_campaigns", "direct_mail_recipient_id": "direct_mail_recipients" },
  "neighborhood_data_sources": { "brokerage_id": "brokerages" },
  "neighborhood_reports": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "net_sheet_calculations": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "net_sheet_reconciliations": { "brokerage_id": "brokerages" },
  "newsletter_brokers_templates": { "approved_by": "users", "brokerage_id": "brokerages", "created_by": "users" },
  "newsletter_campaigns": { "agent_id": "agents", "brokerage_id": "brokerages", "created_by": "users", "marketing_campaign_id": "marketing_campaigns" },
  "newsletter_local_content": { "brokerage_id": "brokerages", "newsletter_id": "newsletter_campaigns" },
  "newsletter_scheduled_sends": { "agent_id": "agents", "brokerage_id": "brokerages", "newsletter_id": "newsletter_campaigns", "template_id": "newsletter_brokers_templates" },
  "newsletter_sections": { "brokerage_id": "brokerages", "newsletter_id": "newsletter_campaigns" },
  "newsletter_sends": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "newsletter_seo_scores": { "scheduled_send_id": "newsletter_scheduled_sends" },
  "newsletter_subscribers": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "newsletter_templates": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "newsletter_video_renders": { "agent_id": "agents", "brokerage_id": "brokerages", "newsletter_campaign_id": "newsletter_campaigns", "video_project_id": "ai_video_projects" },
  "newsletters": { "brokerage_id": "brokerages" },
  "nextdoor_activity": { "brokerage_id": "brokerages" },
  "notification_log": { "brokerage_id": "brokerages", "notification_id": "notifications" },
  "notification_preferences": { "user_id": "users" },
  "notification_queue": { "notification_id": "notifications" },
  "notification_rules": { "brokerage_id": "brokerages" },
  "notifications": { "activity_id": "activities", "brokerage_id": "brokerages", "compliance_event_id": "compliance_events", "contact_id": "contacts", "lifecycle_event_id": "lifecycle_events", "user_id": "users" },
  "objection_scenario_agents": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "objection_training_sessions": { "agent_user_id": "users", "brokerage_id": "brokerages" },
  "objection_training_turns": { "session_id": "objection_training_sessions" },
  "offer_comparison": { "agent_id": "agents", "brokerage_id": "brokerages", "created_by": "users", "listing_id": "listings", "recommended_offer_id": "offers" },
  "offer_strategy_templates": { "brokerage_id": "brokerages" },
  "offers": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "parent_offer_id": "offers", "presented_to_seller_by_agent_id": "agents", "strategy_recommendation_id": "strategy_recommendations", "transaction_id": "transactions", "uploaded_by": "users" },
  "onboarding_ai_chats": { "agent_id": "agents", "agent_onboarding_id": "agent_onboarding", "brokerage_id": "brokerages" },
  "onboarding_quizzes": { "step_id": "onboarding_steps" },
  "onboarding_steps": { "brokerage_id": "brokerages" },
  "open_house_analytics": { "event_id": "open_house_events" },
  "open_house_attendees": { "brokerage_id": "brokerages", "contact_id": "contacts", "event_id": "open_house_events" },
  "open_house_events": { "agent_id": "agents", "brokerage_id": "brokerages", "created_by": "users", "listing_id": "listings", "qr_code_id": "qr_codes" },
  "open_house_feedback": { "attendee_id": "open_house_attendees", "brokerage_id": "brokerages", "contact_id": "contacts", "event_id": "open_house_events" },
  "open_house_invitations": { "brokerage_id": "brokerages", "contact_id": "contacts", "event_id": "open_house_events" },
  "open_house_rsvp_tracking": { "brokerage_id": "brokerages", "contact_id": "contacts", "event_id": "open_house_events" },
  "open_houses": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings", "property_id": "listings" },
  "orchestrator_tasks": { "brokerage_id": "brokerages" },
  "organization_members": { "brokerage_id": "brokerages", "team_id": "teams", "user_id": "users" },
  "outbound_message_compliance_log": { "brokerage_id": "brokerages", "contact_id": "contacts", "initiated_by": "users" },
  "outcome_reconciliations": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "outside_agent_contact_links": { "brokerage_id": "brokerages", "contact_id": "contacts", "outside_agent_id": "outside_agents" },
  "outside_agents": { "brokerage_id": "brokerages" },
  "pattern_adoptions": { "adopted_by": "users", "agent_id": "agents", "brokerage_id": "brokerages", "insight_id": "brokerage_intelligence_insights" },
  "pattern_detections": { "agent_id": "agents", "brokerage_id": "brokerages", "pattern_id": "behavioral_patterns" },
  "pattern_predictions": { "agent_id": "agents", "brokerage_id": "brokerages", "detection_id": "pattern_detections" },
  "phone_number_events": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "photo_enhancement_jobs": { "agent_id": "agents", "brokerage_id": "brokerages", "photo_id": "listing_media" },
  "photo_ordering_rules": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "plan_tasks": { "brokerage_id": "brokerages", "plan_id": "copilot_plans" },
  "platform_affiliates": { "created_by": "users" },
  "platform_config_snapshots": { "captured_by": "users", "source_brokerage_id": "brokerages" },
  "platform_coupon_redemptions": { "brokerage_id": "brokerages", "coupon_id": "platform_coupons", "redeemed_by": "users" },
  "platform_coupons": { "created_by": "users" },
  "platform_credentials": { "agent_user_id": "users", "brokerage_id": "brokerages" },
  "platform_dunning_events": { "brokerage_id": "brokerages", "subscription_id": "subscriptions" },
  "platform_impersonation_sessions": { "actor_user_id": "users", "target_brokerage_id": "brokerages", "target_user_id": "users" },
  "platform_lead_distributions": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "platform_nps_responses": { "brokerage_id": "brokerages", "user_id": "users" },
  "platform_prospects": { "converted_brokerage_id": "brokerages" },
  "platform_reception_calls": { "prospect_id": "platform_prospects" },
  "platform_role_capability_overrides": { "updated_by": "users" },
  "platform_sentinel_actions": { "acted_by": "users", "brokerage_id": "brokerages" },
  "platform_social_accounts": { "connected_by": "users" },
  "platform_staff_profiles": { "created_by": "users", "user_id": "users" },
  "playbooks": { "created_by": "users" },
  "podcast_analytics_events": { "brokerage_id": "brokerages", "episode_id": "podcast_episodes", "listener_contact_id": "contacts" },
  "podcast_auto_runs": { "agent_id": "agents", "brokerage_id": "brokerages", "podcast_episode_id": "podcast_episodes" },
  "podcast_distribution_channels": { "brokerage_id": "brokerages" },
  "podcast_distribution_log": { "brokerage_id": "brokerages", "podcast_episode_id": "podcast_episodes" },
  "podcast_episode_presets": { "brokerage_id": "brokerages" },
  "podcast_episodes": { "agent_id": "agents", "brokerage_id": "brokerages", "marketing_campaign_id": "marketing_campaigns", "source_video_asset_id": "video_assets", "source_video_project_id": "ai_video_projects", "template_id": "podcast_templates" },
  "podcast_segments": { "brokerage_id": "brokerages", "episode_id": "podcast_episodes" },
  "podcast_templates": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "policy_decisions": { "brokerage_id": "brokerages", "document_id": "documents" },
  "portal_access_logs": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "portal_contact_invites": { "brokerage_id": "brokerages", "contact_id": "contacts", "invited_by": "users" },
  "portal_event_stream": { "agent_action_completed_by": "users", "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "source_activity_id": "activities", "source_event_id": "lifecycle_events", "transaction_id": "transactions" },
  "portal_push_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "prediction_accuracy_log": { "brokerage_id": "brokerages", "prediction_id": "content_performance_predictions" },
  "predictive_lead_scores": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "predictive_listing_actions": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "predictive_listing_scores": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "presentation_sections": { "presentation_id": "listing_presentations", "render_id": "remotion_composition_renders" },
  "price_predictions": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "price_trend_alerts": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "pricing_history": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "privacy_acceptances": { "brokerage_id": "brokerages", "contact_id": "contacts", "user_id": "users" },
  "proactive_interventions": { "transaction_id": "transactions" },
  "prohibited_phrases": { "brokerage_id": "brokerages" },
  "property_alert_delivery_log": { "alert_id": "property_alerts", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_alert_results": { "alert_id": "property_alerts", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "property_alerts": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_consensus": { "collaborative_search_id": "collaborative_searches" },
  "property_family_ratings": { "collaborative_search_id": "collaborative_searches" },
  "property_feedback": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "property_intelligence": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_interactions": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "property_interests": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_matches": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_preferences": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "property_search_log": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "property_smart_insights": { "brokerage_id": "brokerages" },
  "property_upgrades": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "property_views": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "prospect_context": { "prospect_id": "prospects" },
  "prospects": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "push_notification_queue": { "brokerage_id": "brokerages" },
  "push_subscriptions": { "brokerage_id": "brokerages", "user_id": "users" },
  "qr_codes": { "agent_id": "agents", "brokerage_id": "brokerages", "listing_id": "listings", "marketing_campaign_id": "marketing_campaigns" },
  "qr_scan_events": { "brokerage_id": "brokerages", "contact_id": "contacts", "qr_code_id": "qr_codes" },
  "quickbooks_sync_log": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "raw_recruit_prospects": { "brokerage_id": "brokerages", "market_id": "lead_scraping_markets", "recruit_id": "recruits" },
  "raw_scraped_leads": { "brokerage_id": "brokerages", "lead_id": "leads", "market_id": "lead_scraping_markets", "scraper_execution_id": "scraper_executions" },
  "real_estate_events": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "recruiting_analytics": { "brokerage_id": "brokerages", "recruit_id": "recruits", "recruited_agent_id": "agents" },
  "recruiting_costs": { "brokerage_id": "brokerages", "recruit_id": "recruits", "recruited_agent_id": "agents" },
  "recruiting_roi": { "brokerage_id": "brokerages", "recruited_agent_id": "agents" },
  "recruits": { "brokerage_id": "brokerages", "provisioned_user_id": "users", "recruiter_agent_id": "agents" },
  "referral_partners": { "agent_id": "agents", "brokerage_id": "brokerages", "vendor_id": "vendors" },
  "referral_sources": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "referrals": { "agent_id": "agents", "brokerage_id": "brokerages", "partner_id": "referral_partners", "referred_contact_id": "contacts", "referred_lead_id": "leads", "referrer_contact_id": "contacts", "referring_agent_id": "agents" },
  "reg_change_observations": { "brokerage_id": "brokerages" },
  "remotion_composition_renders": { "brokerage_id": "brokerages", "composition_id": "remotion_compositions", "refreshed_from_render_id": "remotion_composition_renders", "served_from_render_id": "remotion_composition_renders", "used_intro_asset_id": "video_assets", "used_music_asset_id": "video_assets", "used_outro_asset_id": "video_assets" },
  "repurpose_pipelines": { "agent_user_id": "users", "brokerage_id": "brokerages", "created_by": "users", "team_id": "teams" },
  "repurposed_content_log": { "brokerage_id": "brokerages", "created_by": "users" },
  "revenue_protection_snapshots": { "agent_id": "agents", "brokerage_id": "brokerages", "previous_snapshot_id": "revenue_protection_snapshots", "team_id": "teams" },
  "review_requests": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "saved_ai_outputs": { "user_id": "users" },
  "saved_calculations": { "brokerage_id": "brokerages" },
  "saved_properties": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "scheduled_touchpoints": { "contact_id": "contacts" },
  "scraper_executions": { "brokerage_id": "brokerages", "triggered_by": "users" },
  "script_variations": { "brokerage_id": "brokerages", "created_by": "users", "script_library_id": "video_scripts_library" },
  "scripts": { "brokerage_id": "brokerages", "created_by": "users" },
  "seller_share_feed": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "seller_stage_coaching": { "brokerage_id": "brokerages" },
  "seller_updates": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "seller_weekly_reports": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "seo_keywords": { "agent_user_id": "users", "brokerage_id": "brokerages", "created_by": "users", "team_id": "teams" },
  "seo_optimization_log": { "blog_post_id": "blog_posts", "brokerage_id": "brokerages" },
  "sequence_enrollments": { "brokerage_id": "brokerages", "contact_id": "contacts", "enrolled_by": "users", "lead_id": "leads", "sequence_id": "campaign_sequences" },
  "sequence_step_executions": { "brokerage_id": "brokerages", "contact_id": "contacts", "enrollment_id": "sequence_enrollments", "sequence_id": "campaign_sequences", "step_id": "campaign_sequence_steps" },
  "service_status": { "brokerage_id": "brokerages" },
  "showing_analytics": { "brokerage_id": "brokerages", "listing_id": "listings" },
  "showing_briefings": { "agent_id": "agents", "brokerage_id": "brokerages", "showing_id": "showings" },
  "showing_communications": { "brokerage_id": "brokerages", "showing_id": "showing_requests" },
  "showing_feedback": { "brokerage_id": "brokerages", "showing_id": "showings" },
  "showing_feedback_requests": { "brokerage_id": "brokerages", "showing_id": "showings" },
  "showing_requests": { "brokerage_id": "brokerages", "contact_id": "contacts", "converted_showing_id": "showings", "listing_id": "listings", "saved_property_id": "saved_properties", "tour_id": "tours" },
  "showing_routes": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "showings": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "tour_id": "tours" },
  "signal_reactivations": { "contact_id": "contacts", "lead_id": "leads" },
  "signature_requests": { "brokerage_id": "brokerages", "contact_id": "contacts", "document_id": "client_documents", "transaction_id": "transactions" },
  "site_activity": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "smart_assistant_suggestions": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "smart_checklists": { "transaction_id": "transactions" },
  "smart_landing_sessions": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings" },
  "smart_showing_recommendations": { "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "sms_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "social_accounts": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "social_engagement_tracking": { "brokerage_id": "brokerages", "social_post_id": "social_posts" },
  "social_intelligence": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "social_media_accounts": { "agent_id": "agents", "brokerage_id": "brokerages", "user_id": "users" },
  "social_media_analytics": { "brokerage_id": "brokerages", "post_id": "social_posts" },
  "social_post_analytics": { "brokerage_id": "brokerages", "social_post_id": "social_posts" },
  "social_post_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "social_posts": { "agent_id": "agents", "approved_by": "users", "brokerage_id": "brokerages", "listing_id": "listings", "marketing_campaign_id": "marketing_campaigns", "social_account_id": "social_media_accounts", "user_id": "users" },
  "social_publish_log": { "account_id": "social_media_accounts", "brokerage_id": "brokerages", "campaign_id": "marketing_campaigns", "social_post_id": "social_posts" },
  "social_search_raw_results": { "brokerage_id": "brokerages", "lead_id": "leads" },
  "storage_orphaned_objects": { "brokerage_id": "brokerages" },
  "strategy_outcomes": { "brokerage_id": "brokerages", "offer_id": "offers", "recommendation_id": "strategy_recommendations" },
  "strategy_recommendations": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "offer_id": "offers", "template_id": "offer_strategy_templates" },
  "studio_sessions": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "subscriber_service_areas": { "brokerage_id": "brokerages" },
  "subscriptions": { "brokerage_id": "brokerages", "tier_id": "subscription_tiers" },
  "support_ticket_messages": { "ticket_id": "support_tickets" },
  "support_tickets": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "sync_errors": { "brokerage_id": "brokerages", "sync_log_id": "accounting_sync_log" },
  "system_health_checks": { "brokerage_id": "brokerages" },
  "task_items": { "checklist_id": "smart_checklists" },
  "tasks": { "assigned_to_agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "created_by_agent_id": "agents", "listing_id": "listings", "transaction_id": "transactions" },
  "tax_categories": { "brokerage_id": "brokerages" },
  "team_activity_snapshots": { "brokerage_id": "brokerages" },
  "team_commission_profiles": { "brokerage_id": "brokerages", "team_id": "teams" },
  "team_earnings": { "brokerage_id": "brokerages", "team_id": "teams", "top_agent_id": "agents" },
  "team_heatmap_snapshots": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "team_members": { "agent_id": "agents", "brokerage_id": "brokerages", "team_id": "teams" },
  "team_performance": { "brokerage_id": "brokerages", "team_id": "teams" },
  "teams": { "brokerage_id": "brokerages", "team_lead_id": "users" },
  "template_feedback": { "template_id": "template_marketplace" },
  "template_marketplace": { "brokerage_id": "brokerages" },
  "tenant_ai_teammates": { "brokerage_id": "brokerages", "created_by": "users" },
  "tenant_custom_domains": { "added_by": "users", "brokerage_id": "brokerages" },
  "tenant_phone_numbers": { "brokerage_id": "brokerages" },
  "tenant_safety_findings": { "resolved_by": "users" },
  "tenant_sso_connections": { "brokerage_id": "brokerages", "created_by": "users" },
  "tenant_webhook_deliveries": { "brokerage_id": "brokerages", "subscription_id": "tenant_webhook_subscriptions" },
  "tenant_webhook_subscriptions": { "brokerage_id": "brokerages", "created_by": "users" },
  "team_cap_tracking": { "brokerage_id": "brokerages", "team_id": "teams", "agent_id": "agents" },
  "territory_metrics": { "brokerage_id": "brokerages" },
  "thank_you_note_templates": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "thank_you_notes": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "email_queue_id": "email_queue", "template_id": "thank_you_note_templates", "transaction_id": "transactions" },
  "tier_budgets": { "brokerage_id": "brokerages", "tier_id": "listing_marketing_tiers" },
  "tier_distributions": { "brokerage_id": "brokerages", "tier_id": "listing_marketing_tiers" },
  "timeline_transparency": { "transaction_id": "transactions" },
  "title_company_users": { "transaction_id": "transactions", "user_id": "users" },
  "title_orders": { "brokerage_id": "brokerages", "transaction_id": "transactions", "vendor_id": "vendors" },
  "tool_shares": { "calculation_id": "saved_calculations" },
  "tool_usage_sessions": { "brokerage_id": "brokerages" },
  "tour_stops": { "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "showing_id": "showings", "tour_id": "tours" },
  "tours": { "agent_approved_by": "users", "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "training_videos": { "ai_video_project_id": "ai_video_projects", "brokerage_id": "brokerages", "created_by": "users", "provider_project_id": "ai_video_projects" },
  "transaction_agent_roles": { "agent_id": "agents", "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "transaction_assignments": { "brokerage_id": "brokerages", "coordinator_id": "transaction_coordinators", "transaction_id": "transactions" },
  "transaction_closing_prep": { "transaction_id": "transactions" },
  "transaction_commissions": { "transaction_id": "transactions" },
  "transaction_communications": { "transaction_id": "transactions" },
  "transaction_compliance_log": { "manual_override_by": "users", "transaction_id": "transactions" },
  "transaction_coordinators": { "brokerage_id": "brokerages", "user_id": "users" },
  "transaction_cost_breakdown": { "transaction_id": "transactions" },
  "transaction_deadlines": { "source_document_id": "documents", "transaction_id": "transactions" },
  "transaction_documents": { "transaction_id": "transactions" },
  "transaction_health_factors": { "transaction_id": "transactions" },
  "transaction_inspections": { "transaction_id": "transactions" },
  "transaction_lenders": { "transaction_id": "transactions" },
  "transaction_milestone_templates": { "brokerage_id": "brokerages" },
  "transaction_milestones": { "brokerage_id": "brokerages", "completed_by": "users", "override_by": "users", "transaction_id": "transactions" },
  "transaction_participants": { "transaction_id": "transactions" },
  "transaction_pending_actions": { "agent_id": "agents", "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "transaction_repair_negotiations": { "transaction_id": "transactions" },
  "transaction_tasks": { "transaction_id": "transactions" },
  "transaction_timeline": { "transaction_id": "transactions" },
  "transaction_title_escrow": { "transaction_id": "transactions" },
  "transaction_vendor_services": { "transaction_id": "transactions", "vendor_id": "vendors" },
  "transactions": { "agent_id": "agents", "brokerage_id": "brokerages", "buyer_agent_id": "agents", "buyer_contact_id": "contacts", "contact_id": "contacts", "coordinator_id": "transaction_coordinators", "listing_id": "listings", "offer_id": "offers", "seller_agent_id": "agents", "seller_contact_id": "contacts" },
  "transparency_updates": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions", "transparency_video_id": "transparency_videos" },
  "trend_alerts": { "brokerage_id": "brokerages" },
  "trid_timeline": { "brokerage_id": "brokerages", "transaction_id": "transactions" },
  "unified_lead_profile": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "usage_counters": { "brokerage_id": "brokerages" },
  "usage_events": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "team_id": "teams", "user_id": "users" },
  "usage_logs": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "user_activity": { "user_id": "users" },
  "user_brokerage_roles": { "brokerage_id": "brokerages" },
  "user_invitations": { "accepted_user_id": "users", "brokerage_id": "brokerages", "invited_by": "users", "team_id": "teams" },
  "user_profiles": { "brokerage_id": "brokerages", "user_id": "users" },
  "user_role_assignments": { "brokerage_id": "brokerages", "team_id": "teams", "user_id": "users" },
  "users": { "brokerage_id": "brokerages", "created_by": "users", "location_id": "locations", "team_id": "teams" },
  "valuation_requests": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts" },
  "value_delivered_daily": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "vendor_access_logs": { "brokerage_id": "brokerages", "vendor_id": "vendor_marketplace_profiles" },
  "vendor_assignments": { "assigned_by_agent_id": "agents", "brokerage_id": "brokerages", "transaction_id": "transactions", "vendor_id": "vendors" },
  "vendor_bookings": { "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions", "vendor_id": "vendors" },
  "vendor_communications": { "brokerage_id": "brokerages", "service_id": "listing_marketing_services", "vendor_id": "vendors" },
  "vendor_contact_assignments": { "assigned_by": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "revoked_by": "users", "transaction_id": "transactions", "vendor_id": "vendors" },
  "vendor_earnings": { "brokerage_id": "brokerages", "invoice_id": "vendor_invoices", "vendor_id": "vendors" },
  "vendor_invitations": { "brokerage_id": "brokerages", "invited_by": "users", "vendor_id": "vendors" },
  "vendor_invoices": { "booking_id": "vendor_bookings", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions", "vendor_id": "vendors" },
  "vendor_jobs": { "assignment_id": "vendor_assignments", "brokerage_id": "brokerages", "transaction_id": "transactions", "vendor_id": "vendors" },
  "vendor_messages": { "brokerage_id": "brokerages", "contact_vendor_id": "contact_vendors", "vendor_id": "vendors" },
  "vendor_payouts": { "brokerage_id": "brokerages", "vendor_id": "vendors" },
  "vendor_plans": { "vendor_id": "vendor_marketplace_profiles" },
  "vendor_ratings": { "vendor_id": "vendors" },
  "vendor_review_flags": { "review_id": "vendor_reviews" },
  "vendor_reviews": { "brokerage_id": "brokerages", "user_id": "users", "vendor_id": "vendors" },
  "vendor_subscriptions": { "brokerage_id": "brokerages", "plan_id": "vendor_plans", "vendor_id": "vendor_marketplace_profiles" },
  "vendor_tax_documents": { "vendor_id": "vendors" },
  "vendor_transactions": { "brokerage_id": "brokerages", "subscription_id": "vendor_subscriptions", "vendor_id": "vendor_marketplace_profiles" },
  "vendor_usage_tracking": { "agent_id": "agents", "brokerage_id": "brokerages", "lead_id": "leads" },
  "vendors": { "brokerage_id": "brokerages", "invited_by_team_id": "teams", "invited_by_user_id": "users", "team_id": "teams", "verified_by": "users" },
  "video_assets": { "agent_id": "agents", "brokerage_id": "brokerages", "created_by": "users", "team_id": "teams" },
  "video_completion_tracking": { "agent_id": "agents", "brokerage_id": "brokerages", "training_video_id": "training_videos" },
  "video_content": { "agent_id": "agents", "brokerage_id": "brokerages" },
  "video_engagement_events": { "brokerage_id": "brokerages", "contact_id": "contacts", "video_asset_id": "video_assets" },
  "video_generation_queue": { "project_id": "ai_video_projects" },
  "video_performance_tracking": { "brokerage_id": "brokerages", "video_asset_id": "video_assets", "video_project_id": "ai_video_projects" },
  "video_render_log": { "brokerage_id": "brokerages", "project_id": "ai_video_projects" },
  "video_scripts_library": { "agent_id": "agents", "approved_by": "users", "brokerage_id": "brokerages", "created_by": "users", "rejected_by": "users", "template_id": "video_templates" },
  "video_snippets": { "brokerage_id": "brokerages", "created_by": "users", "source_video_asset_id": "video_assets", "video_project_id": "ai_video_projects" },
  "video_streaming_status": { "brokerage_id": "brokerages", "video_project_id": "ai_video_projects" },
  "voice_assistant_config": { "agent_id": "agents" },
  "voice_assistant_sessions": { "agent_id": "agents" },
  "voice_calls": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "voice_clone_training": { "brokerage_id": "brokerages", "voice_profile_id": "agent_voice_profiles" },
  "voice_commands": { "brokerage_id": "brokerages", "user_id": "users" },
  "voicedrop_presets": { "brokerage_id": "brokerages", "compliance_event_id": "compliance_events" },
  "wealth_advisor_recommendations": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "website_visitors": { "agent_id": "agents", "brokerage_id": "brokerages", "contact_id": "contacts", "lead_id": "leads" },
  "workflow_automations": { "brokerage_id": "brokerages", "created_by": "users" },
  "workflow_intake_sessions": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "document_id": "documents" },
  "workflow_run_steps": { "run_id": "workflow_runs" },
  "workflow_runs": { "agent_user_id": "users", "brokerage_id": "brokerages", "contact_id": "contacts", "listing_id": "listings", "transaction_id": "transactions", "trigger_event_id": "lifecycle_events" },
  "workflow_webhook_events": { "brokerage_id": "brokerages", "contact_id": "contacts" },
  "zenrows_property_search_raw": { "brokerage_id": "brokerages", "lead_id": "leads" },
}

/**
 * ── FK CARDINALITY PER TABLE PAIR ───────────────────────────────────────────────────
 * GENERATED from the same live schema, by the same rule, in the same pass as the map above.
 *
 * WHY A SECOND STRUCTURE
 * SCHEMA_FK_MAP answers "where does this FK column point?". It cannot answer "how many
 * different ways can these two tables be joined?", and that is the question behind PostgREST's
 * PGRST201:
 *
 *     "Could not embed because more than one relationship was found for 'contacts' and
 *      'transactions'" — hint: use `!<constraint>` to disambiguate
 *
 * `transactions` carries THREE foreign keys to `contacts` (contact_id, buyer_contact_id,
 * seller_contact_id). A `.from("contacts").select("transactions(id)")` names a relation that
 * genuinely exists and columns that genuinely exist, and PostgREST still refuses the WHOLE
 * request — the same silent-dead-read outcome as a phantom column, out of a schema that is
 * entirely valid. Nothing in SCHEMA_FK_MAP or SCHEMA_SNAPSHOT can see it: both are keyed by
 * a single table, and ambiguity is a property of the PAIR.
 *
 * THE KEY IS AN UNORDERED PAIR, and that is the whole point. PostgREST resolves an embed by
 * collecting every relationship between the two tables REGARDLESS OF DIRECTION — the M2O side
 * of each FK the parent holds AND the O2M side of each FK the target holds. So
 * `contacts.select("transactions(…)")` and `transactions.select("contacts(…)")` are ambiguous
 * for the same reason and by the same count. Sorting the two names and joining with "|" makes
 * that symmetry structural instead of something every caller has to remember. `|` is safe as a
 * separator: every relname in this schema matches /^[a-z0-9_]+$/.
 *
 * ONLY PAIRS ABOVE ONE ARE STORED. A pair with exactly one FK is unambiguous and is the
 * overwhelming majority (1642 of 1698 pairs) — storing them would be 30× the bytes to encode
 * "nothing to see here". An absent key therefore means "one FK or none", i.e. NOT ambiguous.
 * A self-referential pair (a === b) is stored under "t|t" and is included: two self-FKs on one
 * table are ambiguous exactly like two FKs between different tables (remotion_composition_renders
 * is the live instance). One self-FK is a pair count of 1 and is correctly absent.
 *
 * SAFETY PROPERTY (the mirror of the map's, and the reason for the > 1 filter)
 * A missing or stale entry can only cause a check to SKIP a pair, never to invent an ambiguity.
 * Staleness costs coverage, not trust — the same bargain SCHEMA_FK_MAP makes.
 *
 * DELIBERATELY NOT COUNTED — each of these makes the number an UNDER-estimate, never an over-
 * estimate, so the failure mode stays "missed detection" and never "false alarm":
 *   • many-to-many relationships PostgREST infers THROUGH a junction table. Those add further
 *     candidate relationships to a pair, so a pair recorded here as 1 can still be ambiguous.
 *   • foreign keys crossing out of `public` (there are none in the guarded surface).
 *
 * MEASURED WHEN GENERATED: 1773 foreign-key constraints in `public`, every one single-column,
 * and no two constraints sharing a (source table, source column, target table) triple — so a
 * pair's count is exactly its number of distinct join paths. 1698 unordered table pairs carry
 * at least one FK; 56 carry more than one and are listed below. 12 of the 1773 are self-
 * referential. (This re-measurement also supersedes the "1792 foreign keys" figure in the
 * header above: the committed SCHEMA_FK_MAP holds exactly 1773 entries, which agrees with the
 * count here and not with that line.)
 *
 * REGENERATE alongside SCHEMA_FK_MAP, from the same `pg_constraint` scan:
 *
 *   WITH fk AS (
 *     SELECT c.oid, src.relname AS src_table, a.attname AS src_col, tgt.relname AS tgt_table
 *     FROM pg_constraint c
 *     JOIN pg_class src ON src.oid = c.conrelid
 *     JOIN pg_namespace sn ON sn.oid = src.relnamespace
 *     JOIN pg_class tgt ON tgt.oid = c.confrelid
 *     JOIN pg_namespace tn ON tn.oid = tgt.relnamespace
 *     JOIN unnest(c.conkey) AS k(attnum) ON true
 *     JOIN pg_attribute a ON a.attrelid = src.oid AND a.attnum = k.attnum
 *     WHERE c.contype='f' AND sn.nspname='public' AND tn.nspname='public'
 *   )
 *   SELECT LEAST(src_table, tgt_table) AS a, GREATEST(src_table, tgt_table) AS b, count(*) AS n
 *   FROM fk GROUP BY 1, 2 HAVING count(*) > 1 ORDER BY 1, 2;
 *
 * Last synced: 2026-08-15.
 */

/** `SCHEMA_FK_PAIR_CARDINALITY["a|b"] = n` for the SORTED pair (a <= b), n > 1 only.
 *  Read it through fkPairCount() — the key encoding is this file's business, not its callers'. */
export const SCHEMA_FK_PAIR_CARDINALITY: Record<string, number> = {
  "ad_campaigns|users": 2,
  "agent_mentor_relationships|agents": 2,
  "agent_relationships|agents": 2,
  "agents|commission_adjustments": 2,
  "agents|embed_widgets": 2,
  "agents|offers": 2,
  "agents|referrals": 2,
  "agents|tasks": 2,
  "agents|transactions": 3,
  "ai_generated_content|content_ab_tests": 3,
  "ai_message_drafts|messages": 2,
  "ai_quota_overrides|users": 2,
  "ai_video_projects|marketing_campaigns": 2,
  "ai_video_projects|training_videos": 2,
  "ai_video_projects|users": 2,
  "automation_errors|users": 4,
  "blog_posts|users": 2,
  "brokerages|leads": 2,
  "brokerages|users": 2,
  "buyer_broker_agreements|users": 2,
  "buyer_financial_profiles|users": 2,
  "client_documents|users": 2,
  "closing_disclosure_agreement|users": 8,
  "collaborative_searches|contacts": 2,
  "contacts|listings": 2,
  "contacts|referrals": 2,
  "contacts|transactions": 3,
  "contacts|users": 6,
  "data_subject_requests|users": 3,
  "fatigue_alerts|users": 2,
  "feature_access_overrides|users": 2,
  "learning_assignments|users": 2,
  "learning_modules|users": 3,
  "listing_media|users": 2,
  "listing_presentations|users": 2,
  "listings|open_houses": 2,
  "marketing_assets|users": 2,
  "marketing_campaigns|users": 2,
  "newsletter_brokers_templates|users": 2,
  "offers|strategy_recommendations": 2,
  "offers|transactions": 2,
  "platform_impersonation_sessions|users": 2,
  "platform_staff_profiles|users": 2,
  "portal_event_stream|users": 2,
  "remotion_composition_renders|remotion_composition_renders": 2,
  "remotion_composition_renders|video_assets": 3,
  "repurpose_pipelines|users": 2,
  "seo_keywords|users": 2,
  "social_posts|users": 2,
  "teams|users": 2,
  "teams|vendors": 2,
  "transaction_milestones|users": 2,
  "user_invitations|users": 2,
  "users|vendor_contact_assignments": 2,
  "users|vendors": 2,
  "users|video_scripts_library": 3,
}

/** How many distinct foreign keys join these two tables, in EITHER direction.
 *  Returns 1 for any pair not in the table above — see the "only pairs above one are stored"
 *  note: absent means "one FK or none", and both are unambiguous to PostgREST. Argument order
 *  is irrelevant by construction. */
export function fkPairCount(t1: string, t2: string): number {
  const key = t1 <= t2 ? `${t1}|${t2}` : `${t2}|${t1}`
  return SCHEMA_FK_PAIR_CARDINALITY[key] ?? 1
}
