/**
 * scripts/schema-snapshot.ts
 *
 * GENERATED from the live Postgres schema (public). The schema-drift guard checks the
 * codebase's column references against this snapshot so the "code references a column the
 * table doesn't have → query silently errors" bug class (which broke buyer matching) can't
 * come back.
 *
 * REGENERATE when a guarded table's columns change:
 *   select table_name, json_agg(column_name order by column_name) as cols
 *   from information_schema.columns where table_schema='public'
 *   and table_name = ANY(ARRAY[...guarded tables...]) group by table_name;
 *
 * Last synced: 2026-06-09.
 */
export const SCHEMA_SNAPSHOT: Record<string, string[]> = {
  contacts: [
    "next_followup_at", "next_followup_reason",
    "address", "age_range", "agent_id", "ai_autopilot_level", "ai_conversion_probability", "ai_insights",
    "avatar_url", "birthday", "home_anniversary", "preferred_contact_time", "tags", "time_zone",
    "ai_isa_enabled", "ai_outreach_paused", "ai_predicted_close_date", "nurture_status",
    "referral_approach", "referral_score",
    "brokerage_id", "budget_max", "budget_min", "buyer_stage", "call_stop_flag",
    "campaign_attribution_id", "city", "compliance_officer_id", "confidence_score", "contact_id",
    "contact_persona", "contact_type", "contact_user_id", "cost_per_record", "court_records",
    "created_at", "credit_pipeline_stage", "credit_score_band", "credit_status",
    "data_source", "deleted_at", "direct_mail_opt_out", "dl_image_url", "dnc_status",
    "education_level", "email", "email_opt_out", "email_unsubscribed", "email_unsubscribed_at",
    "email_verification_date", "email_verified", "embed_widget_id", "engagement_score",
    "enriched_at", "enrichment_confidence", "enrichment_profile", "enrichment_source",
    "equity_estimate", "facebook_url", "first_name", "first_touch_channel", "first_touched_at",
    "funds_max_purchase", "funds_source_type",
    "gender", "ghl_contact_id", "home_owner_status", "home_value_estimate", "household_income",
    "id", "instagram_url", "intent_score", "isa_handoff_at", "isa_handoff_brief",
    "isa_qualification_score", "isa_reengage_allowed", "isa_reengage_marked_by",
    "isa_reengage_set_at", "last_contacted_at", "last_enriched_at", "last_life_change_check",
    "last_life_event_detected", "last_name", "last_pls_scored_at",
    "last_scored_at", "lead_score", "lead_temperature", "legal_first_name", "legal_last_name",
    "legal_middle_name", "legal_name_source", "legal_name_verified_at", "lender_status",
    "length_of_residence", "life_events", "lifecycle_state", "linkedin_url", "mailing_address",
    "mailing_address_source", "mailing_address_verified", "mailing_address_verified_at",
    "mailing_city", "mailing_state", "mailing_zip",
    "marital_status", "metadata", "motivation_confidence", "motivation_type", "notes",
    "occupation", "opt_out_channels", "opt_out_reason", "opt_out_source", "opted_out_at",
    "peopledata_id", "phone", "phone_digits", "phone_opt_out", "phone_secondary",
    "phone_secondary_dnc_status", "phone_secondary_opt_out", "phone_secondary_status",
    "phone_secondary_type", "phone_secondary_verified", "phone_status", "phone_type",
    "phone_validated_at", "phone_verification_date", "phone_verified", "preferred_channel",
    "privacy_anonymized_at", "privacy_anonymized_reason", "property_records", "public_records",
    "qualification_summary", "referral_potential", "sms_opt_out", "sms_unsubscribed",
    "sms_unsubscribed_at", "social_handles", "source", "source_agent_id", "source_channel",
    "source_family", "source_subtype", "state", "status", "tc_user_id", "tcpa_consent",
    "tcpa_consent_at", "tcpa_consent_date", "tcpa_consent_ip", "tcpa_consent_source",
    "tcpa_consent_text", "tcpa_marked_at", "tcpa_marked_by", "team_id", "timeline",
    "twitter_url", "updated_at", "urgency_level", "user_id", "video_opt_out", "zip_code",
  ],
  property_preferences: [
    "agent_id", "brokerage_id", "confidence_score", "contact_id", "created_at", "id",
    "inferred_baths_min", "inferred_beds_min", "inferred_cities", "inferred_deal_breakers",
    "inferred_max_price", "inferred_min_price", "inferred_must_have_features",
    "inferred_property_types", "inferred_zip_codes", "last_calculated_at", "model_version",
    "preferred_price_max", "preferred_price_min", "signals_processed", "updated_at",
  ],
  listings: [
    "address", "agent_id", "bathrooms", "bedrooms", "brokerage_id", "city", "commission_rate",
    "appointment_at", "appointment_event_id", "appointment_notes",
    "contact_id", "created_at", "created_via", "deleted_at", "dotloop_loop_id", "estimated_close_date",
    "expiration_date", "flood_zone", "go_live_confirmed_at", "go_live_date", "has_pool", "has_septic", "has_solar",
    "hoa_dues", "id", "last_price_change_at", "lifecycle_stage", "list_price",
    "listing_agent_email", "listing_agent_name", "listing_date", "lot_size", "marketing_budget",
    "marketing_tier_id", "metadata", "mls_link", "mls_number", "open_house_event_date",
    "open_house_marketing_date", "photos", "primary_photo_url", "property_type", "public_remarks",
    "seller_contact_id", "showing_count", "showing_instructions", "slug", "sold_date", "sold_price", "sub_category",
    "sqft", "stage_entered_at", "stage_updated_at", "state", "status",
    "team_id", "transaction_provider_ref", "updated_at", "year_built", "zip",
  ],
  property_matches: [
    "ai_generated", "brokerage_id", "contact_id", "created_at", "generated_at", "id",
    "match_reasons", "match_score", "potential_concerns", "priority_factors", "property_id",
    "recommended_actions", "user_feedback",
  ],
  saved_properties: [
    "added_to_tour", "ai_match_score", "bathrooms", "bedrooms", "brokerage_id", "city",
    "contact_id", "dismissed", "dismissed_reason", "external_property_id", "id", "list_price",
    "listing_id", "listing_url", "match_reasons", "mls_number", "notes", "primary_photo_url",
    "property_address", "property_type", "saved_at", "source", "sqft", "state", "user_id",
  ],
  agent_client_messages: [
    "agent_kind", "approved_at", "approved_by", "audience", "body", "brokerage_id", "channel",
    "created_at", "entity_id", "entity_type", "id", "managed_agent_session_id", "proposed_at",
    "rationale", "recipient_contact_id", "recipient_lead_id", "send_error", "sent_at", "status", "subject",
  ],
  leads: [
    "next_followup_at", "next_followup_reason", "home_owner_status", "life_events", "dnc_status",
    "address", "agent_id", "ai_isa_owner", "ai_outreach_paused", "assigned_owner", "brokerage_id",
    "budget_max", "budget_min", "call_stop_flag", "campaign_attribution_id", "city", "contact_count",
    "contact_id", "converted_at", "cost_per_record", "created_at", "days_in_stage", "dedupe_status",
    "direct_mail_opt_out", "distributed_at", "distribution_brokerage_id", "duplicate_of_contact_id",
    "duplicate_of_lead_id", "email", "email_opt_out", "email_verified", "enrichment_confidence",
    "enrichment_profile", "enrichment_provider", "enrichment_status", "equity_estimate", "first_name",
    "first_touch_channel", "first_touched_at",
    "handed_to_agent_at", "id", "is_active", "isa_handoff_brief", "last_activity_at", "last_contacted_at",
    "last_enriched_at", "last_name", "lat", "lead_score", "lead_stage", "lead_temperature", "lead_type",
    "lender_status", "lifecycle_state", "lng", "long_term_nurture_reason", "long_term_nurture_started_at",
    "long_term_nurture_until", "mailing_address", "mailing_address_source", "mailing_address_verified",
    "mailing_city", "mailing_state", "mailing_zip", "minimum_viable_for_isa", "motivation_confidence",
    "motivation_type", "notes", "opted_out_at", "persona", "phone", "phone_digits", "phone_opt_out",
    "phone_secondary", "preferred_channel", "property_interest", "property_zip_code", "qualification_summary",
    "raw_record_id", "reengagement_attempt_count", "reengagement_status", "sms_opt_out", "source",
    "source_channel", "source_family", "source_origin", "source_page_url", "source_raw_ids", "source_subtype",
    "stage_entered_at", "state", "status", "tags", "tcpa_consent", "tcpa_consent_at", "tcpa_consent_ip",
    "tcpa_consent_source", "tcpa_consent_text", "tcpa_consent_user_agent", "timeline", "updated_at",
    "urgency_level", "utm_campaign", "utm_medium", "utm_source", "zip_code",
  ],
  raw_scraped_leads: [
    "address", "brokerage_id", "city", "cost_per_record", "created_at", "dedupe_status", "email",
    "email_verified", "enriched_at", "error_message", "first_name", "id", "last_name",
    "last_promotion_attempt_at", "lead_id", "mailing_address", "mailing_address_source",
    "mailing_address_verified", "mailing_city", "mailing_state", "mailing_zip", "market_id",
    "normalized_preview", "phone", "processed_at", "processing_status", "promotion_attempts", "raw_data",
    "scraper_execution_id", "source", "source_channel", "source_family", "source_origin",
    "source_record_id", "source_subtype", "state", "updated_at", "zip_code",
  ],
  remotion_composition_renders: [
    "agent_user_id", "brokerage_id", "completed_at", "composition_id", "created_at", "entity_id",
    "entity_type", "error_message", "id", "input_props", "is_published", "output_url",
    "public_slug", "published_at", "render_status", "requested_via", "scope_id", "scope_type",
    "thumbnail_url", "used_did_avatar", "used_intro_asset_id", "used_music_asset_id",
    "used_outro_asset_id", "used_voiceover",
  ],
  notifications: [
    "activity_id", "body", "brokerage_id", "channel", "compliance_event_id", "contact_id",
    "created_at", "delivered_at", "dismissed_at", "entity_id", "entity_type", "id", "is_read",
    "lifecycle_event_id", "priority", "read_at", "title", "type", "user_id",
  ],
  transactions: [
    "agent_id", "ai_analysis", "ai_primary_risk", "ai_risk_level", "appraisal_completed_date",
    "appraisal_contingency_removed_at", "appraisal_deadline", "appraisal_value", "brokerage_id",
    "buyer_agent_id", "buyer_contact_id", "client_name", "close_date", "commission_amount",
    "commission_percentage", "compliance_passed_at", "contact_id", "contract_date",
    "contract_date_overridden", "contract_date_override_reason", "coordinator_id", "created_at",
    "deal_name", "deal_type", "deleted_at", "earnest_money", "earnest_money_outcome",
    "estimated_close_date", "estimated_commission", "external_provider_source",
    "external_provider_transaction_id", "financing_contingency_removed_at", "financing_deadline",
    "health_score", "health_status", "id", "inspection_contingency_removed_at", "inspection_deadline",
    "last_ai_analysis", "last_provider_sync_at", "lender_id", "listing_id",
    "listing_offered_commission_percentage", "loan_amount", "lost_at", "lost_category", "lost_reason",
    "offer_id", "property_address", "property_city",
    "property_state", "property_zip", "purchase_price", "seller_agent_id", "seller_contact_id",
    "source", "source_family", "stage", "status", "updated_at", "win_probability",
  ],
  offers: [
    "agent_id", "ai_analysis", "ai_extracted_data", "ai_extraction_status", "ai_recommendation",
    "appraisal_contingency_days", "appraisal_gap", "brokerage_id", "buyer_commission_acknowledged_at",
    "buyer_commission_acknowledged_ip", "buyer_commission_acknowledged_ua", "buyer_notes",
    "buyer_signed_at", "closing_cost_contribution", "closing_date", "commission_disclosure_method",
    "compliance_passed_at", "contact_id", "contingencies", "created_at", "current_round",
    "disclosed_buyer_commission_flat", "disclosed_buyer_commission_pct", "disclosed_commission_notes",
    "disclosed_commission_payer", "down_payment_amount", "down_payment_percent", "due_diligence_fee",
    "earnest_money", "earnest_money_due_at", "earnest_money_due_days", "escalation_cap",
    "escalation_clause", "esign_completed_at", "esign_provider", "esign_sent_at", "esign_status",
    "financing_contingency_days", "financing_type", "form_provider_ref", "form_source",
    "fully_signed_contract_received_at", "has_counter", "id", "inspection_period_days",
    "is_winning_offer", "listing_id", "notes", "offer_document_name", "offer_document_url",
    "offer_documents", "offer_number", "offer_price", "offer_type", "parent_offer_id",
    "possession_terms", "property_address", "property_address_ai_filled", "provider_envelope_id",
    "ready_for_compliance_at", "responded_at", "response_deadline", "seller_net_estimate",
    "seller_response_document_url", "seller_response_received_at", "seller_response_type",
    "seller_signed_at", "seller_signed_document_url", "seller_viewed_at", "status",
    "strategy_recommendation_id", "submitted_at",
    "transaction_id", "updated_at", "uploaded_by",
  ],
  showings: [
    "access_code", "access_instructions", "access_method", "agent_id", "brokerage_id",
    "buyer_agent_email", "buyer_agent_name", "buyer_agent_phone", "buyer_interest_level",
    "completed_at", "confirmed_at", "contact_id", "created_at", "duration_minutes", "external_address",
    "external_metadata", "external_mls_id", "external_source", "feedback", "id", "is_confirmed",
    "listing_agent_company", "listing_agent_name", "listing_agent_phone",
    "listing_id", "notes", "offline_cached", "rating", "scheduled_at",
    "scheduled_date", "scheduled_time", "scheduling_method", "scheduling_reference", "showingtime_id",
    "status", "sync_source", "synced_at", "tour_id", "updated_at",
  ],
  // Buyer-side touring (Shopping Agent): the planned route + its per-property stops.
  tours: [
    "agent_approved_at", "agent_approved_by", "agent_id", "ai_plan_narrative", "all_confirmed",
    "brokerage_id", "buyer_id", "contact_id", "created_at", "id", "notes", "offline_cached_at",
    "plan_sent_at", "report_sent_at", "report_sent_via", "report_url", "scheduled_at",
    "start_address", "start_time", "status", "total_drive_time_minutes", "total_duration_minutes",
    "tour_date", "updated_at",
  ],
  tour_stops: [
    "access_code", "access_instructions", "access_method", "brokerage_id", "buyer_interest_level",
    "buyer_note", "city", "confirmed_time", "contact_id", "created_at", "drive_time_from_prev_minutes",
    "feedback", "id", "is_confirmed", "list_price", "listing_agent_company", "listing_agent_email",
    "listing_agent_name", "listing_agent_phone", "listing_id", "listing_url", "mls_number",
    "order_index", "primary_photo_url", "property_address", "rating", "scheduling_instructions",
    "scheduling_method", "scheduling_reference", "showing_id", "state", "suggested_duration_minutes", "suggested_time",
    "time_arrived_at", "time_left_at", "time_spent_minutes", "tour_id", "zip",
  ],
  tasks: [
    "assigned_to_agent_id", "assignee_type", "auto_generated", "brokerage_id", "completed_at",
    "contact_id", "created_at", "created_by_agent_id", "description", "due_date", "id", "listing_id",
    "priority", "source", "source_enrollment_id", "stage_key", "status", "tags", "title",
    "transaction_id", "updated_at",
  ],
  activities: [
    "activity_type", "agent_id", "agent_user_id", "brokerage_id", "channel", "completed_at",
    "contact_id", "created_at", "description", "duration_minutes", "entity_id", "entity_type", "id",
    "listing_id", "metadata", "notes", "outcome", "priority", "scheduled_at", "scheduled_for",
    "status", "title", "transaction_id", "updated_at",
  ],
  calendar_events: [
    "agent_user_id", "attendees", "brokerage_id", "created_at", "deadline_notified", "end_at",
    "entity_id", "entity_type", "event_type", "id", "is_system_generated", "location", "metadata",
    "start_at", "status", "timezone_name", "title",
  ],
  assignment_log: [
    "agent_id", "assignment_method", "brokerage_id", "claimed", "claimed_at", "created_at",
    "id", "lead_id", "routing_reason", "rule_id", "score_at_assignment",
  ],
  ai_daily_briefings: [
    "active_transactions_summary", "agent_id", "ai_model_used", "briefing_date", "brokerage_id",
    "deals_at_risk", "delivered_at", "generated_at", "hot_leads", "id", "isa_overnight",
    "listings_at_risk", "market_pulse", "opened_at", "summary", "tasks_overdue",
    "todays_events", "top_priority_actions", "user_id",
  ],
  ai_isa_call_batches: [
    "approved_at", "approved_by", "brokerage_id", "call_results", "completed_at", "created_at",
    "dialed_count", "id", "proposed_at", "proposed_by_agent_id", "proposed_count", "script",
    "status", "target_contacts",
  ],
  manager_signals: [
    "brokerage_id", "consumed_action", "consumed_at", "contact_id", "created_at", "entity_id",
    "entity_type", "from_manager", "id", "message", "payload", "signal_type", "status", "to_manager",
  ],
}
