-- Add SELLER_DECLINED, LISTING_CANCELLED, LISTING_EXPIRED to listings.lifecycle_stage CHECK constraint
-- Safe: DROP CONSTRAINT IF EXISTS before re-adding with expanded value list

ALTER TABLE public.listings
  DROP CONSTRAINT IF EXISTS listings_lifecycle_stage_check;

ALTER TABLE public.listings
  ADD CONSTRAINT listings_lifecycle_stage_check
  CHECK (lifecycle_stage = ANY (ARRAY[
    'LEAD','LEAD_ASSIGNED','AGENT_CONSULTATION','APPOINTMENT_SET','CMA_GENERATION',
    'LISTING_PRESENTATION_CREATED','PRESENTATION_VIDEO_GENERATED','PRESENTATION_DRIP_PREP',
    'SELLER_DECISION','SELLER_DECLINED','LISTING_AGREEMENT_INITIATED',
    'LISTING_AGREEMENT_SIGNED','MLS_DATE_CONFIRMED','COMING_SOON_PREP',
    'REPAIRS_IN_PROGRESS','COMING_SOON_ACTIVE','MEDIA_CAPTURE','MEDIA_APPROVED',
    'MLS_READY','OPEN_HOUSE_MARKETING','MLS_ACTIVE','OPEN_HOUSE_EVENT',
    'SHOWINGS_ACTIVE','OFFERS_RECEIVED','NEGOTIATION','UNDER_CONTRACT',
    'INSPECTION','APPRAISAL','FINANCING','CLOSING_PREP','CLOSED',
    'LIFETIME_CUSTOMER','LISTING_CANCELLED','LISTING_EXPIRED'
  ]));
