-- m105 — RETIRED / NO-OP (consolidated onto m1093).
--
-- ORIGINAL INTENT: add a `dedupe_key TEXT` column + a UNIQUE(contact_id, dedupe_key) index, and have
-- lib/kernel/event-fanout.ts writePortalUpdate() insert with ON CONFLICT on that key.
--
-- WHAT ACTUALLY SHIPPED: the project chose the *no-app-change* idempotency design instead —
-- migration `1093-transparency-updates-dedupe-index` (applied as schema_migrations
-- 20260529193050 `transparency_updates_dedupe_index`), a partial unique index
--     transparency_updates_dedupe_idx (contact_id, update_type, md5(title), date_trunc('minute', created_at))
-- A truly-concurrent duplicate card hits that unique violation, which the writer's swallowing insert
-- absorbs. m105 was therefore NEVER applied (the live table has no dedupe_key column).
--
-- THE DRIFT THIS FIXES: the fan-out writer still TARGETED the m105 dedupe_key column + onConflict, so
-- every portal-card insert silently failed (PostgREST: column does not exist) and NO transparency
-- card was ever written — breaking the client-portal "always know where your deal stands" promise.
-- writePortalUpdate now inserts plainly and relies on the deployed m1093 index + the app-layer SELECT.
--
-- This migration is intentionally a NO-OP so it can never re-introduce the competing dedupe_key column
-- and re-break the writer. Do NOT restore the DDL below; idempotency lives in m1093.
--
-- (former DDL, retained for history only — do not re-enable):
--   ALTER TABLE transparency_updates ADD COLUMN IF NOT EXISTS dedupe_key TEXT;
--   CREATE UNIQUE INDEX transparency_updates_contact_dedupe_key_uniq
--     ON transparency_updates(contact_id, dedupe_key) WHERE dedupe_key IS NOT NULL;

SELECT 1;  -- no-op
